### ISSUE TITLE
Broken CSS and JS

### ISSUE THREAD

**Issue by GoogleCodeExporter** [apache/incubator-pagespeed-mod#1016]
```
What steps will reproduce the problem?
1. Enable mod_pagespeed

What is the expected output? What do you see instead?
The page breaks. CSS is missing.
[Warning] Invalid CSS property declaration at: * (explore, line 12)
[Error] SyntaxError: Unexpected token '<'
    (anonym funksjon) (404, line 1)
[Error] ReferenceError: Can't find variable: mod_pagespeed_zDPdHCVuFD
    global code (explore, line 17)
[Error] ReferenceError: Can't find variable: mod_pagespeed_iQpYc3y0WS
    global code (explore, line 19)
[Error] ReferenceError: Can't find variable: mod_pagespeed_CEsjKphoff
    global code (explore, line 20)
[Error] ReferenceError: Can't find variable: mod_pagespeed_BsJQbncASZ
    global code (explore, line 21)

Disabling filters rewrite_javascript, and rewrite_images seems to fix it.

What version of the product are you using (please check X-Mod-Pagespeed
header)?
X-Mod-Pagespeed 1.8.31.5-4307

On what operating system?
Ubuntu 12.04 3.13.0-34-generic 

Which version of Apache?
Apache/2.4.10 (Ubuntu)

Which MPM?

URL of broken page:
http://cloudaud.io

```

Original issue reported on code.google.com by `tho...@ndt-lan.no` on 9 Nov 2014 at 9:50

**Comment by Ranjit-Kr** [comment]
Recently page speed has been implemented on our website-
there is a functionality for reset password on my website that triggers otp to mobile. After getting otp page redirects to reset password page. Afetr entering otp and clicking on continue i am getting the following error :


clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8 Uncaught TypeError: Illegal invocation
    at K (clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8)
    at a.fn.init.text (clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8)
    at Object.success (resetpassword.js.pagespeed.jm.b8U5GDu-kU.js:1)
    at i (clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8)
    at Object.fireWith [as resolveWith] (clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8)
    at z (clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8)
    at XMLHttpRequest.<anonymous> (clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8)
K @ clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8
text @ clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8
success @ resetpassword.js.pagespeed.jm.b8U5GDu-kU.js:1
i @ clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8
fireWith @ clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8
z @ clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8
(anonymous) @ clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8
XMLHttpRequest.send (async)
send @ clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8
ajax @ clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8
submitResetPassRequest @ resetpassword.js.pagespeed.jm.b8U5GDu-kU.js:1
(anonymous) @ resetpassword.js.pagespeed.jm.b8U5GDu-kU.js:1
dispatch @ clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8
r.handle @ clientlibs.js.pagespeed.jm.P4bq0aKKBT.js:8

**Comment by oschaaf** [comment]
@Ranjit-Kr You could try disabling the rewrite_javascript to see if that resolves the issue.
https://www.modpagespeed.com/doc/config_filters

Note that this issue is old and has been closed a long time ago -- I think it's best to move further discussion to https://groups.google.com/d/topic/mod-pagespeed-discuss
