### ISSUE TITLE
HTML parser breaks Handlebars markup in an edge case with invalid html

### ISSUE THREAD

**Issue by GoogleCodeExporter** [apache/incubator-pagespeed-mod#1041]
```
Handlebars.js markup such as '{{/if_eq}}' in an HTML tag gets converted to '{{ 
if_eq}}' when the HTML parser treats '/' as an attribute separator and renders 
it as a space.

The attached handlebars_fix.diff patch against the current trunk code fixes the 
problem and hopefully doesn't break anything else.

Code was tested with Apache 2.2.22 on Ubuntu 12.04 LTS (Precise).

The attached select.html document illustrates the problem.


```

Original issue reported on code.google.com by `glancas...@appneta.com` on 9 Jan 2015 at 9:21

Attachments:
- [handlebars_fix.diff](https://storage.googleapis.com/google-code-attachments/modpagespeed/issue-1041/comment-0/handlebars_fix.diff)
- [select.html](https://storage.googleapis.com/google-code-attachments/modpagespeed/issue-1041/comment-0/select.html)

**Comment by jeffkaufman** [comment]
Normally we handle cases like this by having PageSpeed run after the full HTML is generated. Is there a reason that won't work here?

**Comment by jeffkaufman** [comment]
Learning more about handlebars, this is a templating system that's handled in the browser, which means our usual "run pagespeed after templating" solution doesn't fit.

We need to fix this by no longer messing with ``{{/foo}}`, or at least turn ourselves off if we see something that looks like handlebar.

**Comment by jmarantz** [comment]
If you open select.html (the attachment) in Chrome, you'll see that the markup is broken in the same way by Chrome directly, without PageSpeed:

The markup in select.html:
 `<option value="2" {{#if_eq enrollmentStatus compare=2}} selected="selected"{{/if_eq}}>Audi</option>`

gets displayed by the Chrome dev tools like this:
`<option value="2" {{#if_eq="" enrollmentstatus="" compare="2}}" selected="selected" {{="" if_eq}}="">Audi</option>`

You can get this to work, both in Chrome and in PageSpeed, using this form (or similar):

`{{#if_eq enrollmentStatus compare=2}}`
`<option value="2" selected="selected">Audi</option>`
`{{else}}`
`<option value="2">Audi</option>`
`{{/if_eq}}`

I don't know if a construct like {{else}} exists in handlebar, but you get the idea.

**Comment by morlovich** [comment]
FWIW, the Handlebar docs suggest putting templates into a <script> tag with an appropriate language; which will also prevent them from being parsed as HTML.

**Comment by morlovich** [comment]
... script tag with a particular langue option. I wonder if github's doing a bit of overzealous XSS-guarding.

**Comment by jmarantz** [comment]
Somehow my comment about the workaround got mangled as well.  Basically, hoist the handlebars sequence out of the tag and repeat the tag both ways.

I do see this example:
    `<a href="/posts/{{../permalink}}#{{id}}">{{title}}</a>`
this one might be OK because it's inside double-quotes in HTML syntax, and so PageSpeed will just pass that through.  There is some risk in this case if pagespeed's DomainRewriteHyperlinks is on, that it would try and parse and rewrite the href in the example as a valid URL.  I think it will fail to do that and therefore leave that href alone.

The key thing to remember is that PageSpeed (and the browser's HTML parser) will see the handlebars markup before the JS runs, so it needs to be lexically valid HTML, which the above href= example is, even if the URL in it is invalid.

**Comment by jmarantz** [comment]
I thought of a second workaround idea which is a bit simpler than the first one:

`<option value="2" selected="{{#if_eq enrollmentStatus compare=2}}selected{{/if_eq}}">Audi</option>`

Here again, note that the '/if_eq' in inside the tag is enclosed by double-quotes, and hence should be safe from interpretation by browser & PageSpeed html parsers.
