### ISSUE TITLE
Inflation error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [apache/incubator-pagespeed-mod#1042]
```
I have noticed some new entries in my error logs today:

[Mon Jan 12 20:12:47 2015] [warn] [mod_pagespeed 1.9.32.3-4448 @28394] 
inflation failure, size=-1
[Mon Jan 12 20:12:50 2015] [warn] [mod_pagespeed 1.9.32.3-4448 @28631] 
inflation failure, size=-1
[Mon Jan 12 20:12:52 2015] [warn] [mod_pagespeed 1.9.32.3-4448 @25401] 
inflation failure, size=-1

Any idea what would cause this?
```

Original issue reported on code.google.com by `rwap.services` on 12 Jan 2015 at 8:20

**Comment by jeffkaufman** [comment]
Feel free to reopen if this comes up again.

**Comment by RWAP** [comment]
I have had some more of these, but few and far between and hard to pin down - I get a lot more:
Rewrite http://www.sellmyretro.com/uploaded/img/4023_100_2789_100px.JPG failed while fetching http://www.sellmyretro.com/uploaded/img/x4023_100_2789_100px.JPG.pagespeed.ic.CYvyebA-mT.webp

**Comment by contactmayankjain** [comment]
I am getting error messages in apache error logs.

Mon Jul 13 23:53:14.616633 2015] [pagespeed:warn] [pid 13326:tid 140040009144064] [mod_pagespeed 1.9.32.4-7251 @13326] CSS parsing error in http://ampletrails.com/hard-disk-surveillance-camera-cctv/e-learning-blog
[Mon Jul 13 23:53:20.174796 2015] [pagespeed:warn] [pid 13326:tid 140040009144064] [mod_pagespeed 1.9.32.4-7251 @13326] CSS parsing error in http://ampletrails.com/hard-disk-surveillance-camera-cctv/e-learning-blog
[Mon Jul 13 23:53:25.197732 2015] [pagespeed:warn] [pid 13327:tid 140040017536768] [mod_pagespeed 1.9.32.4-7251 @13327] CSS parsing error in http://ampletrails.com/comparison-attendance-machine-e9999-6161t-x990/e-learning-blog
[Mon Jul 13 23:53:30.323686 2015] [pagespeed:warn] [pid 13326:tid 140040009144064] [mod_pagespeed 1.9.32.4-7251 @13326] CSS parsing error in http://ampletrails.com/comparison-attendance-machine-e9999-6161t-x990/e-learning-blog
[Mon Jul 13 23:53:41.053580 2015] [pagespeed:warn] [pid 13327:tid 140040017536768] [mod_pagespeed 1.9.32.4-7251 @13327] CSS parsing error in http://ampletrails.com/fedena-shared-hosting-site5/e-learning-blog
[Mon Jul 13 23:53:50.407698 2015] [pagespeed:warn] [pid 13326:tid 140040009144064] [mod_pagespeed 1.9.32.4-7251 @13326] CSS parsing error in http://ampletrails.com/elearning-solution-productivity-problem/e-learning-blog
[Mon Jul 13 23:53:54.701117 2015] [pagespeed:warn] [pid 13326:tid 140040009144064] [mod_pagespeed 1.9.32.4-7251 @13326] CSS parsing error in http://ampletrails.com/how-to-reduce-training-cost/e-learning-blog
[Mon Jul 13 23:53:59.916288 2015] [pagespeed:warn] [pid 13326:tid 140040009144064] [mod_pagespeed 1.9.32.4-7251 @13326] CSS parsing error in http://ampletrails.com/how-to-reduce-training-cost/e-learning-blog
[Mon Jul 13 23:54:05.002216 2015] [pagespeed:warn] [pid 13326:tid 140040009144064] [mod_pagespeed 1.9.32.4-7251 @13326] CSS parsing error in http://ampletrails.com/elearning-needed/e-learning-blog
[Mon Jul 13 23:54:08.833173 2015] [pagespeed:warn] [pid 13327:tid 140040017536768] [mod_pagespeed 1.9.32.4-7251 @13327] CSS parsing error in http://ampletrails.com/elearning-needed/e-learning-blog
