### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [apache/incubator-pagespeed-mod#1055]
```
What steps will reproduce the problem?
1.  Try to Build ngx_pagespeed-release-1.9.32.3-beta from Source.  It says 
FreeBSD is not supported.


```

Original issue reported on code.google.com by `i...@narq.net` on 19 Mar 2015 at 9:11

**Comment by jeffkaufman** [comment]
Tracking this in https://github.com/pagespeed/mod_pagespeed/issues/1073

**Comment by AlbaroPereyra** [comment]
Is there a solution for this today? I am extremely interested. I am wasting a lot of money to have an AWS CentOS instance just for this. If there is no solution I will stop using this useless plugin that all it gives is Google brownie points.

**Comment by jserviceorg** [comment]
at least it compiles for me flawless on latest 11.1-STABLE, further testing will follow
