### ISSUE TITLE
check-fail on page refresh

### ISSUE THREAD

**Issue by jmarantz** [apache/incubator-pagespeed-mod#1061]
What steps will reproduce the problem?
1. install from source
2. refresh web page
3. look at log

What is the expected output? What do you see instead?

What version of the product are you using (please check X-Mod-Pagespeed
header)?

 1.9.32.3-4448 @14442

On what operating system?

CentOS release 5.11 (Final) - 64 bit

Which version of Apache?
Which MPM?
URL of broken page:

**Comment by jeffkaufman** [comment]
Is this on all pages or just a specific one you didn't include the url for?

**Comment by jeffkaufman** [comment]
Ping.

**Comment by jmarantz** [comment]
Ouch I have no idea.  I must have missed the paste.  No way to recover that data.  Closing.
