### ISSUE TITLE
mod_pagespeed incompatible with .htaccess

### ISSUE THREAD

**Issue by daveime** [apache/incubator-pagespeed-mod#1067]
So I have this situation. I want to use mod-pagespeed to optimize images, css, js etc and so far everything was performing well. However, I'm testing some htaccess directives to redirect an image request to a smaller version based on user agent. Here's an example of what I'm doing.

```
RewriteCond %{HTTP_USER_AGENT}  ^(.*)iphone(.*)$ [NC]
RewriteCond %{REQUEST_URI} ^(.*)homepage10\.jpg$ [NC]
RewriteRule ^(.*)$ /homepage10.small.jpg [R=302,L]
```

If user agent contains iphone, then redirect any request for "homepage10.jpg" to "homepage10.small.jpg".

It appears however, that mod_pagespeed essentially kills any htacess directives on those image files, even though I have these configurations set in pagespeed.conf  to prevent the filenames getting munged into some random string.

```
ModPagespeedJsPreserveURLs on
ModPagespeedImagePreserveURLs on
ModPagespeedCssPreserveURLs on
```

Why can't mod_pagespeed just behave like everything else in apache?

A request is made, any mod_rewrite directives or other directives are processed, either in httpd.conf or in .htaccess, and ONLY when the final filename / resource has been resolved, does mod_pagespeed process that request and serve an optimized resource?

Right now, all he's doing is seeing a request for "homepage10.jpg", and serving an optimized version immediately - completely IGNORING the htaccess directives that say a different image should be served under certain conditions.

It's a real shame, this module has such potential, but has now been rendered effectively useless as it doesn't respect the function of other apache modules, specifically mod_rewrite.

mod_pagespeed should be executed LAST, not FIRST, in the apache module processing order, and using the FINAL resolved resource name, not the initially requested one.

I also reference Issue #397, where it is stated "However, this does not work in mod_pagespeed because we grab the URL prior to mod_rewrite running". This is patently incorrect behaviour - all modules should respect changes made to the requested resource by other modules.

Or at least, give us a configuration option to "UseInitialRequest" or "UseFinalResolvedRequest" and let us choose our own destiny.

**Comment by jmaessen** [comment]
Actually, mod_pagespeed _should_ be running last in your module hierarchy.  I suspect there may be other things going on here.  Can you send a pointer to your page, and a clear description of the behavior you're seeing?  Are you using in-place resource optimization to serve these particular images?
What headers occur on these files when they're served?  I'm wondering if they have the appropriate vary: headers – otherwise mod_pagespeed may in fact cache the rewritten version of one image and rewrite urls to point to that one.

**Comment by daveime** [comment]
Sorry for the delay getting back to you. Okay, so here's the relevant info and debugging I've done ...

pagespeed.conf

```
ModPagespeed on

ModPagespeedInheritVHostConfig on
AddOutputFilterByType MOD_PAGESPEED_OUTPUT_FILTER text/html
ModPagespeedFileCachePath            "/var/cache/mod_pagespeed/"
ModPagespeedLogDir "/var/log/pagespeed"

ModPagespeedDisableFilters add_head,inline_import_to_link
ModPagespeedDisableFilters combine_css,fallback_rewrite_css_urls,rewrite_style_attributes_with_url,flatten_css_imports
ModPagespeedDisableFilters rewrite_javascript_inline,combine_javascript
ModPagespeedDisableFilters inline_css,inline_javascript

ModPagespeedForbidFilters add_head,inline_import_to_link
ModPagespeedForbidFilters combine_css,fallback_rewrite_css_urls,rewrite_style_attributes_with_url,flatten_css_imports
ModPagespeedForbidFilters rewrite_javascript_inline,combine_javascript
ModPagespeedForbidFilters inline_css,inline_javascript

ModPagespeedJsPreserveURLs on
ModPagespeedImagePreserveURLs on
ModPagespeedCssPreserveURLs on

ModPagespeedStatisticsLogging on
ModPagespeedMessageBufferSize 100000
```

I should clarify I setup my config that way so that pagespeed just optimizes images and doesn't touch the HTML, affect urls, use beacons or anything else - it's just a simple image optimization I'm looking for at this point.

.htaccess

```
RewriteCond %{HTTP_USER_AGENT}  ^(.*)iphone(.*)$ [NC]
RewriteCond %{REQUEST_URI} ^(.*)\.jpg$ [NC]
RewriteCond %{REQUEST_URI} !^(.*)\.small\.jpg$ [NC]
RewriteRule ^(.*)$ /iphonejpg.php?source=$1 [L]
```

The iphonejpg.php script checks to see if "small" image is on filesystem, creates if necessary, and then finally sends a 302 redirect header to the correct resource.

With pagespeed disabled, the headers are thus (domain name suppressed) ...

```
http://[MYDOMAIN.COM]/images/homepage10.jpg

GET /images/homepage10.jpg HTTP/1.1
Host: [MYDOMAIN.COM]
User-Agent: TEST iPhone TEST
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive

HTTP/1.1 302 Moved Temporarily
Date: Mon, 20 Apr 2015 03:47:06 GMT
Server: Apache/2.2.25 (Unix) mod_ssl/2.2.25 OpenSSL/1.0.0-fips DAV/2 mod_bwlimited/1.4
X-Powered-By: PHP/5.3.26
Location: http://[MYDOMAIN.COM]/images/homepage10.small.jpg
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 20
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html
```

With pagespeed enabled, the headers are thus ...

```
http://[MYDOMAIN.COM]/images/homepage10.jpg

GET /images/homepage10.jpg HTTP/1.1
Host: [MYDOMAIN.COM]
User-Agent: TEST iPhone TEST
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive

HTTP/1.1 200 OK
Date: Mon, 20 Apr 2015 03:49:46 GMT
Server: Apache/2.2.25 (Unix) mod_ssl/2.2.25 OpenSSL/1.0.0-fips DAV/2 mod_bwlimited/1.4
Vary: User-Agent
Content-Length: 205183
Etag: "1e073d-3217f-513fb6faed0c0"
Accept-Ranges: bytes
Cache-Control: max-age=300
Expires: Mon, 20 Apr 2015 03:54:30 GMT
Last-Modified: Mon, 20 Apr 2015 03:49:46 GMT
X-Content-Type-Options: nosniff
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: image/jpeg
```

So it appears that pagespeed ignores the htaccess completely, and never sends the 302 redirect back to the client for him to fetch the correct "small" resource - the original big image is served right away with a 200 header.

To me this indicates that the htaccess is being ignored, I assume because pagespeed (as stated by yourselves) works on the original requested resource i.e. homepage10.jpg and just serves it, and the rewrite portions in the htacces never get to execute (is apache saying "I'm done" and terminating early because of pagespeed already sending the image from his cache?)

Looking forward to any ideas you can suggest.

**Comment by jmaessen** [comment]
On Mon, Apr 20, 2015 at 7:02 AM, daveime notifications@github.com wrote:

> Sorry for the delay getting back to you. Okay, so here's the relevant info
> and debugging I've done ...

That's quite all right.  I'm traveling myself, so my connectivity is a bit
sporadic for which I apologize in advance.

> pagespeed.conf
> 
> ModPagespeed on
> 
> ModPagespeedInheritVHostConfig on
> AddOutputFilterByType MOD_PAGESPEED_OUTPUT_FILTER text/html
> ModPagespeedFileCachePath            "/var/cache/mod_pagespeed/"
> ModPagespeedLogDir "/var/log/pagespeed"
> 
> ModPagespeedDisableFilters add_head,inline_import_to_link
> ModPagespeedDisableFilters combine_css,fallback_rewrite_css_urls,rewrite_style_attributes_with_url,flatten_css_imports
> ModPagespeedDisableFilters rewrite_javascript_inline,combine_javascript
> ModPagespeedDisableFilters inline_css,inline_javascript
> 
> ModPagespeedForbidFilters add_head,inline_import_to_link
> ModPagespeedForbidFilters combine_css,fallback_rewrite_css_urls,rewrite_style_attributes_with_url,flatten_css_imports
> ModPagespeedForbidFilters rewrite_javascript_inline,combine_javascript
> ModPagespeedForbidFilters inline_css,inline_javascript
> 
> ModPagespeedJsPreserveURLs on
> ModPagespeedImagePreserveURLs on
> ModPagespeedCssPreserveURLs on
> 
> ModPagespeedStatisticsLogging on
> ModPagespeedMessageBufferSize 100000
> 
> .htaccess
> 
> RewriteCond %{HTTP_USER_AGENT}  ^(._)iphone(._)$ [NC]
> RewriteCond %{REQUEST_URI} ^(._).jpg$ [NC]
> RewriteCond %{REQUEST_URI} !^(._).small.jpg$ [NC]
> RewriteRule ^(.*)$ /iphonejpg.php?source=$1 [L]
> 
> The iphonejpg.php script checks to see if "small" image is on filesystem,
> creates if necessary, and then finally sends a 302 redirect header to the
> correct resource.
> 
> With pagespeed disabled, the headers are thus (domain name suppressed) ...
> 
> http://[MYDOMAIN.COM]/images/homepage10.jpg
> 
> GET /images/homepage10.jpg HTTP/1.1
> Host: [MYDOMAIN.COM]
> User-Agent: TEST iPhone TEST
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
> Accept-Language: en-US,en;q=0.5
> Accept-Encoding: gzip, deflate
> Connection: keep-alive
> 
> HTTP/1.1 302 Moved Temporarily
> Date: Mon, 20 Apr 2015 03:47:06 GMT
> Server: Apache/2.2.25 (Unix) mod_ssl/2.2.25 OpenSSL/1.0.0-fips DAV/2
> mod_bwlimited/1.4
> X-Powered-By: PHP/5.3.26
> Location: http://[MYDOMAIN.COM]/images/homepage10.small.jpg
> Vary: Accept-Encoding
> Content-Encoding: gzip
> Content-Length: 20
> Keep-Alive: timeout=5, max=100
> Connection: Keep-Alive
> Content-Type: text/html
> 
> I note that the redirect isn't served with Vary: User-Agent, which I'm
> guessing also means that the non-small image is also being served without
> vary: User-Agent.  That means that an intermediate proxy cache (and
> mod_pagespeed acts like a proxy cache in cases like this) is free to serve
> either result to all browsers.  I'm guessing that's probably not what you
> mean to do?

-Jan

**Comment by daveime** [comment]
Regarding Vary: User-Agent, it's not something I've ever used, and I'm a little confused as to the purpose. Even if the header is sent with the response, surely whatever mod_rewrite / mod_pagespeed is doing is going to happen first anyway?

I'm not trying to send a different resource with the same URL based on device, I'm trying to send either the requested resource OR a redirect to a different resource URL based on device.

I simply need these two flows to work.

Client Request == homepage10.jpg AND User-Agent != iPhone ->
Server replies with 200 status homepage10.jpg (suitably optimized by mod_pagespeed)

Client Request == homepage10.jpg AND User-Agent == IPhone ->
Server replies with 302 status redirect to homepage10.small.jpg.
And as a 2nd step, Client will follow the redirect
Client Request == homepage10.small.jpg -> Server replies with 200 status homepage10.small.jpg (suitably optimized by mod_pagespeed)

I've tried completely clearing history and cached files on both Client and Server, restarting apache so each test is a fresh run - but the mod_rewrite refuses to work, mod_pagespeed kicks in and serves exactly what was requested. It's so frustrating.

I guess I'm just going to have to suck it up, put on my C++ hat, and see if I can build a standalone program for Centos to optimize images based on the pagespeed libraries, and optimize as a regular cronjob instead.

I need to keep control on what mod_rewrite is doing, and if mod_pagespeed is stealing that control or doing unexpecting things, it'll have to go.

Thanks for you help anyway.

**Comment by jmaessen** [comment]
On Wed, Apr 22, 2015 at 7:56 AM, daveime notifications@github.com wrote:

> Regarding Vary: User-Agent, it's not something I've ever used, and I'm a
> little confused as to the purpose. Even if the header is sent with the
> response, surely whatever mod_rewrite / mod_pagespeed is doing is going to
> happen first anyway?
> 
> That depends on when mod_headers runs, which should happen before
> mod_pagespeed in normal operation.
> 
> I'm not trying to send a different resource with the same URL based on
> device, I'm trying to send either the requested resource OR a redirect to a
> different resource URL based on device.
> 
> The redirect _counts_ as a different resource.  Think about this from the
> perspective of a proxy cache (something like mod_pagespeed or varnish).  It
> sees the 200 you serve without vary: user-agent.  That tells it to serve
> this value to every browser that goes through the proxy.

It's very likely that some of your users (if you site faces the internet)
are behind such proxies and are being served the wrong content.  By turning
on mod_pagespeed you're simply seeing this behavior for yourself.

> I simply need these two flows to work.
> 
> Client Request == homepage10.jpg AND User-Agent != iPhone ->
> Server replies with 200 status homepage10.jpg (suitably optimized by
> mod_pagespeed)
> 
> Client Request == homepage10.jpg AND User-Agent == IPhone ->
> Server replies with 302 status redirect to homepage10.small.jpg.
> And as a 2nd step, Client will follow the redirect
> Client Request == homepage10.small.jpg -> Server replies with 200 status
> homepage10.small.jpg (suitably optimized by mod_pagespeed)
> 
> I've tried completely clearing history and cached files on both Client and
> Server, restarting apache so each test is a fresh run - but the mod_rewrite
> refuses to work, mod_pagespeed kicks in and serves exactly what was
> requested. It's so frustrating.
> 
> Try adding:

Header append Vary User-Agent

to your .htaccess file.  This ought to fix the problem, but is too
specific.  You should really make it jpeg-sensitive something like:

SetEnvIf Request_URI ".jpg$" object_is_jpg=true
Header append Vary User-Agent env=object_is_jpg

> I guess I'm just going to have to suck it up, put on my C++ hat, and see
> if I can build a standalone program for Centos to optimize images based on
> the pagespeed libraries, and optimize as a regular cronjob instead.
> 
> I need to keep control on what mod_rewrite is doing, and if mod_pagespeed
> is stealing that control or doing unexpecting things, it'll have to go.
> 
> As I note above, I suspect it's not that we're stealing control here, but
> that you're setting the wrong headers.  And that this is likely to be
> hurting your users, but in a way that will be difficult for them to notice.

-Jan

**Comment by jeffkaufman** [comment]
As @jmaessen points out above, the problem here isn't what order PageSpeed runs in compared to the rest of your directives but that PageSpeed is a caching proxy.  You're intentionally serving one thing (a redirect) to some user agents and something else (a jpeg) to other user agents, which means you need to set `Vary: User-Agent` in your response.

Because there are many sites out there with invalid `Vary` headers on resources, PageSpeed ignores these headers by default, so you'll also need to tell PageSpeed to [`RespectVary`](https://developers.google.com/speed/pagespeed/module/configuration#respectvary):

```
ModPagespeedRespectVary on
```
