### ISSUE TITLE
pagespeed is not able to rewritten images on CDN(CloudFront)

### ISSUE THREAD

**Issue by sligocki** [apache/incubator-pagespeed-mod#1069]
Migrated from https://code.google.com/p/modpagespeed/issues/detail?id=1062

Reported by pradeep.aradhya@relevancelab.com, Today (6 hours ago)
Hi All,

I am using mod_pagespeed 1.9.32 version. On CentOS 6 with Apache 2.2 

I am using Drupal as my CMS and serving 3 sites from the same. 

Installed mod_pagespeed. 

We have our images, css and js server from CDN - AWS CloudFront via S3 bucket. 

My pagespeed.conf file is as below: 

```
ModPagespeedEnableFilters collapse_whitespace
ModPagespeedEnableFilters convert_meta_tags
ModPagespeedEnableFilters remove_comments
ModPagespeedEnableFilters collapse_whitespace
ModPagespeedEnableFilters elide_attributes
ModPagespeedEnableFilters trim_urls
ModPagespeedEnableFilters pedantic

ModPagespeedEnableFilters combine_javascript
ModPagespeedEnableFilters canonicalize_javascript_libraries
ModPagespeedEnableFilters rewrite_javascript
ModPagespeedEnableFilters defer_javascript
ModPagespeedEnableFilters inline_javascript

ModPagespeedEnableFilters rewrite_css
ModPagespeedEnableFilters combine_css
ModPagespeedEnableFilters move_css_to_head
ModPagespeedEnableFilters inline_css
ModPagespeedEnableFilters inline_import_to_link
ModPagespeedEnableFilters move_css_above_scripts

ModPagespeedEnableFilters inline_preview_images
ModPagespeedEnableFilters insert_img_dimensions
ModPagespeedEnableFilters rewrite_images
ModPagespeedEnableFilters recompress_images
ModPagespeedEnableFilters convert_jpeg_to_progressive
ModPagespeedEnableFilters resize_mobile_images
ModPagespeedEnableFilters sprite_images

ModPagespeedDomain *.mydomain.com
ModPagespeedDomain abcd1234.cloudfront.net
ModPagespeedDomain mybucket.s3.amazonaws.com
```

ModPagespeedMapProxyDomain http://subdomain1.mydomain.com http://mybucket.s3.amazonaws.com http://abcd1234.cloudfront.net

In /pagespeed_admin/console I can see the rewrite is happening; But, If I try to access the rewritten images, the url says file not found. 

Please, let me know the config I am using is correct or this is a bug. 

--Regards,
Pradeep

In apache error_log

**Comment by jmarantz** [comment]
If you have an image http://mybucket.s3.amazonaws.com/foo.jpg, mod_pagespeed will first rewrite it to  http://subdomain1.mydomain.com/foo.jpg.pagespeed.ic.HASH.webp.  Then it will map that to your CDN, and rewrite this URL into your img tag:
    img src="http://abcd1234.cloudfront.net/foo.jpg.pagespeed.ic.HASH.webp

So far so good.  The question is what does cloudfront do when that is fetched.  If you have it set to pull from http://subdomain1.mydomain.com/ then you should  be all set.

Can you verify that:
  a) you have mod_pagespeed running with the same configuration on http://subdomain1.mydomain.com
  b) you have Cloudfront set to pull from that domain into http://abcd1234.cloudfront.net

Thanks!

**Comment by jeffkaufman** [comment]
Emailed to ask if they're still having the issue.

**Comment by tomasdev** [comment]
Is there a way for a cloudfront distribution to support both s3 bucketing and website pulling? and if so, how do i set that up in the domains rewrite/origins for pagespeed?

**Comment by jeffkaufman** [comment]
@tomasdev Could you say more about what you'd like this to do?

Is it possible to populate the s3 bucket by telling it to fetch from your origin server if the file isn't already on s3?

**Comment by tomasdev** [comment]
@jeffkaufman 

origin: website.com
s3 bucket: images.website.com
cloudfront origin: A.cloudfront.com
cloudfront s3: B.cloudfront.com

Should cloudfront s3 be deleted in favor of just the cloudfront origin one?
How should I setup pagespeed in order to have the webp and rest of optimizations cached in the CDN?
Right now it only works without the s3 bucket, the moment I enable that, pagespeed stops being able to optimize images. I've tried a couple of configs with MapRewriteDomain and MapOriginDomain with no luck. (and I bet it's my fault)

**Comment by jeffkaufman** [comment]
Could you explain a little more about how these four servers are connected?  Specifically, how do your resources get onto these servers?  Which ones do you upload to manually, and which ones pull resources from another server on demand (and if so, which servers do they pull from)?

**Comment by tomasdev** [comment]
Origin pushes the images automatically to the S3 bucket. Both cloudfronts pull automatically from origin & s3, respectively.

Again, the problem is... cloudfront origin, DOES cache the google images and everything okay, but not using S3. The cloudfront S3 doesn't have the google images, because they're dynamically generated on request, which is fine. Perhaps is an AWS question rather than pagespeed.

**Comment by jmarantz** [comment]
We have discussed pushing optimized resources to push-CDNs but that work is
not on our roadmap right now.  Currently PageSpeed works with pull CDNs not
with push CDNs.

I am not familiar enough with the various AWS options but my sense is that
CloudFront can be configured to pull but S3 is for push, but I mat have
this wrong.

josh

-Josh

**Comment by tomasdev** [comment]
@jmarantz you're absolutely right. Thank you guys!! <3
