### ISSUE TITLE
Opera Mini should not be sent lazyload_images JS

### ISSUE THREAD

**Issue by olasia** [apache/incubator-pagespeed-mod#1070]
I'm replicating my e-mail here as requested by @jmarantz.

I'm a developer for the Opera Mini Server compression cloud. The way Opera Mini works is that all the webpages are requested by the Opera Mini server, rendered by it and sent back to the client. We only allow Java Script to be run for a certain amount of time and then pause it. Once the pages has been sent to the client, there's not that much that can be still done using Java Script - we only support a few events, unfortunately `onscroll` is not one of them. As a result of that we often do not show images that are supposed to be loaded lazily.

It would be great if you could include Opera Mini User-Agents in the `LazyloadImagesBlacklist`. Information about our User-Agents can be found [here](https://dev.opera.com/articles/opera-mini-request-headers/).

**Comment by jeffkaufman** [comment]
Planning to blacklist lazyload_images for any browsers with "`Opera Mini`" in their UA string; does that sound right?

**Comment by olasia** [comment]
Yes, that would be sufficient. Thanks in advance!

**Comment by olasia** [comment]
Awesome, thanks a lot.
