### ISSUE TITLE
trim_urls rewriting incorrect URLs

### ISSUE THREAD

**Issue by Rewt0r** [apache/incubator-pagespeed-mod#1071]
I'm using mod_pagespeed version: 1.9.32.3 with nginx.

For some reason trim_urls is rewriting the URL on our forms action attribute when opening another page within a modal.

Page opened in modal (containing the form with the action element):
`/share/documents/GMSBC55379A0FAC4AB`
From:
`/share/documents/GMSBC55379A0FAC4AB`
To:
`GMSBC55379A0FAC4AB`

When visiting URL:
`/quotes/view/GMSBC55379A0FAC4AB`

**Comment by jmarantz** [comment]
trim_urls was removed from the core-set because it can break web pages when MPS does not know what the web site URL is, which can happen in an Ajax load.  I suspect that's what's happening here.

**Comment by jeffkaufman** [comment]
Yes, trim_urls doesn't work in situations like yours, and it's not practical to fix.  You're going to need to turn it off.
