### ISSUE TITLE
RSS feed being affected

### ISSUE THREAD

**Issue by RWAP** [apache/incubator-pagespeed-mod#1074]
For some reason, I have noticed that a PHP generated RSS feed is corrupted by modpagespeed - it gets `<head/>` added after 
`<?xml version=\"1.0\" encoding=\"UTF-8\"?>`

and then ends with:
`<script type="text/javascript" src="/pagespeed_static/js_defer.pbrP1whUgE.js"></script>`

**Comment by jmarantz** [comment]
What is the content-type header emitted by the PHP script?  Is it
"text/html"?

-Josh

**Comment by crowell** [comment]
do you have an example of the feed, or the script that generates it?

as a workaround, one thing that you can do is use a `<Location>...</Location>` block and turn off pagespeed for just the rss feed.

**Comment by RWAP** [comment]
An example is:
http://www.bimomotor.com/category/boats?v=rss&lang=en_US

**Comment by RWAP** [comment]
Ah the content-type header was not being set for RSS - I have added 
`header("Content-Type:application/rss+xml");`
and that has fixed it thankyou
