### ISSUE TITLE
Another Unicode value 0x0 is not valid for interchange warning issue

### ISSUE THREAD

**Issue by deajan** [apache/incubator-pagespeed-mod#1075]
Hello,

I've installed a fresh CentOS 7.1 web server and got lots of the following warnings in /var/log/httpd/error_log

```
[Wed May 06 17:52:17.727138 2015] [pagespeed:warn] [pid 5610:tid 140470898308864] [mod_pagespeed 1.9.32.3-4448 @5610] [0506/175217:WARNING:unicodetext.cc(359)] Unicode value 0x0 is not valid for interchange
[Wed May 06 17:52:17.727144 2015] [pagespeed:warn] [pid 5610:tid 140470898308864] [mod_pagespeed 1.9.32.3-4448 @5610] [0506/175217:WARNING:unicodetext.cc(359)] Unicode value 0x0 is not valid for interchange
[Wed May 06 17:52:17.727150 2015] [pagespeed:warn] [pid 5610:tid 140470898308864] [mod_pagespeed 1.9.32.3-4448 @5610] [0506/175217:WARNING:unicodetext.cc(359)] Unicode value 0x0 is not valid for interchange
[Wed May 06 17:52:17.727156 2015] [pagespeed:warn] [pid 5610:tid 140470898308864] [mod_pagespeed 1.9.32.3-4448 @5610] [0506/175217:WARNING:unicodetext.cc(359)] Unicode value 0x0 is not valid for interchange
[Wed May 06 17:52:17.727163 2015] [pagespeed:warn] [pid 5610:tid 140470898308864] [mod_pagespeed 1.9.32.3-4448 @5610] [0506/175217:WARNING:unicodetext.cc(359)] Unicode value 0x0 is not valid for interchange
[Wed May 06 17:52:17.727169 2015] [pagespeed:warn] [pid 5610:tid 140470898308864] [mod_pagespeed 1.9.32.3-4448 @5610] [0506/175217:WARNING:unicodetext.cc(359)] Unicode value 0x0 is not valid for interchange
[Wed May 06 17:52:17.727175 2015] [pagespeed:warn] [pid 5610:tid 140470898308864] [mod_pagespeed 1.9.32.3-4448 @5610] [0506/175217:WARNING:unicodetext.cc(359)] Unicode value 0x0 is not valid for interchange
[Wed May 06 17:52:17.727181 2015] [pagespeed:warn] [pid 5610:tid 140470898308864] [mod_pagespeed 1.9.32.3-4448 @5610] [0506/175217:WARNING:unicodetext.cc(359)] Unicode value 0x0 is not valid for interchange
[Wed May 06 17:52:17.727196 2015] [pagespeed:warn] [pid 5610:tid 140470898308864] [mod_pagespeed 1.9.32.3-4448 @5610] [0506/175217:WARNING:unicodetext.cc(359)] Unicode value 0x0 is not valid for interchange
```

All my virtualhosts are configured to use their own access and error log files, so i tried to grep the timestamp accross my access logs.

The only hit was the following:

```
xx.xx.xx.xx - - [06/May/2015:17:52:17 +0200] "GET / HTTP/1.1" 200 10681 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"
xx.xx.xx.xx - - [06/May/2015:17:52:17 +0200] "GET /projects/css/A.css_xE-rWrJf-fncB6ztZfd2huxqgxu4WO-qwma6Xer30m4.css+css_cQo-DlQstCPJBG1XGNOxnay8gmmC_vOIIQwImeWm5AE.css+css_e9i1o2m_GsLXCsIe3pJwpeNkUjTw8sddNBrCOrjat7I.css,Mcc.vDQ-VUzWnR.css.pagespeed.cf.QPj8Bjh5a9.css HTTP/1.1" 200 3235 "http://myhost.tld/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"
xx.xx.xx.xx - - [06/May/2015:17:52:17 +0200] "GET /pagespeed_static/js_defer.pbrP1whUgE.js HTTP/1.1" 200 4152 "http://myhost.tld/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"
xx.xx.xx.xx - - [06/May/2015:17:52:17 +0200] "GET /projects/css/A.css_2UYCXwXONt3op79voWND-9xei804ai0AgB0SdTcNUkg.css.pagespeed.cf.ByIpzxLOyr.css HTTP/1.1" 200 8407 "http://myhost.tld/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"
xx.xx.xx.xx - - [06/May/2015:17:52:17 +0200] "GET /_,Mjo.tu9jVnn0gu.js.pagespeed.jm.dtF8zJnnp2.js HTTP/1.1" 200 1404 "http://myhost.tld/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"
xx.xx.xx.xx - - [06/May/2015:17:52:17 +0200] "GET /projects/css/A.css_HbWYLgE3eV-3SySHK6OgKwIuj33rgDFExy3nekTj4-Q.css.pagespeed.cf.0OfkCuMl8e.css HTTP/1.1" 200 1612 "http://myhost.tld/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"
xx.xx.xx.xx - - [06/May/2015:17:52:17 +0200] "GET /projects/css/A.css_MQecJW9Pu6Lg5Cw9nBvo7QvqlBKakORpifS9G_UQ7IA.css.pagespeed.cf.SlhjmBNlEa.css HTTP/1.1" 200 4594 "http://myhost.tld/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"
```

I get like hundreds of those pagespeed warnings per second.
I've read multiple threads talking about the problem (most threads are old and meant for pagespeed <1.4)..
I've tried to play with CustomFetchHeader Accept-Encoding gzip and FetchWithGzip, without success.

Any thoughts ?

Additionnal info:
OS: CentOS 7.1 3.10.0-123.20.1.el7.x86_64
Apache version: httpd-2.4.6-31.el7, MPM event
Php: php-fpm-5.4.16-23.el7_0.3
mod_pagespeed version: mod-pagespeed-stable-1.9.32.3-4448
Vhost config file: https://gist.github.com/deajan/24882b86d55ecab3dfa2
Pagespeed config file: https://gist.github.com/deajan/3c3ab6a61289611f04e6

**Comment by deajan** [comment]
Anyone ?

**Comment by deajan** [comment]
Up ?

**Comment by jmarantz** [comment]
It is unfortunate that we don't reveal the name of the CSS file or
line-number in this error message.  But I'm pretty sure it's because we
found a NUL character in a CSS file.  Since you time-correlated the
results, you know the CSS file.  Are there any NUL characters in your CSS
source?

-Josh

**Comment by deajan** [comment]
I've checked for NUL characters in CSS with the follwing command without results:

```
find ./ -name "*.css" | grep -P '\x00'
```

Since i posted this in the first time i made some tests and come to the conclusion:
I use Drupal, and drupal aggregates and compresses css files to .gz.
When i disable drupal optimizations, it works.
I guess mod_pagespeed finds those .gz files and thinks they are css files, can this be true ?

**Comment by jmarantz** [comment]
Yes I think there can be a problem if the Content-Encoding headers coming
into mod_pagespeed don't reflect that the file was gzipped.

It's possible that Drupal gzips the content and counts on some other filter
that runs after mod_pagespeed to add the Content-Type encoding.

**Comment by deajan** [comment]
Thanks for the info, i guess i can't keep Drupal and mod_pagespeed happy together, as strange as this gets because this happens only on one of my servers, with the same config as i use everywhere :(

**Comment by jmarantz** [comment]
I don't know much about Drupal in particular.  But if you want Drupal to
optimize your CSS, then turn off the CSS filters in mod_pagespeed or
vice-versa.  Certainly mod_pagespeed will deliver you compressed CSS
without Drupal if that's all Drupal was doing to your CSS.

-Josh

**Comment by deajan** [comment]
That's what i did as a workaround :) Thanks.
