### ISSUE TITLE
How to prevent pagespeed from adding file suffixes in HTML when rewriting images?

### ISSUE THREAD

**Issue by jsdevel** [apache/incubator-pagespeed-mod#1079]
I've seen this come up now in several threads.

Basically we're rewriting images, and pagespeed assumes the requests for the images will come back to the same server, so it adds a suffix to the file in the HTML.  Problem is we're behind an LB.

If pagespeed didn't add suffixes to files, then this would work.

Is there an option to disable adding suffixes when rewriting images?

**Comment by jmarantz** [comment]
RE can you avoid renaming URLs when optimizing them?  Yes.  See OptimizeForBandwidth: https://developers.google.com/speed/pagespeed/module/optimize-for-bandwidth

Also see the more surgical 'preserve URLs' settings: https://developers.google.com/speed/pagespeed/module/config_filters#preserveurls

However I want to clearly point out that PageSpeed -- even when rewriting URLs -- is designed to work perfectly in the situation you describe.  You can have multiple Apache instances behind a LB, each of which has distinct caches.  Your LB sends the HTML to one Apache instance, which rewrites foo.jpg to 100x120xfoo.jpg.pagespeed.HASH.webp.  That URL can be decoded by another Apache instance, to the instructions:
1. Find foo.jpg
2. Resize it to 100x120 pixels
3. transcode it to webp
   4a. check that its md5sum is HASH, and serve it with a long cache lifetime
   4b. If the hash does not match, assume the image has changed between the two servers and serve
        it with a short private cache lifetime.
   None of this depends on sharing cache, but it does expect that all servers behind the LB see the same version of foo.jpg and have the same pagespeed image settings.

Have you found some specific symptom (e..g 404s) resulting from your multiserver setup?  That is definitely not expected.

**Comment by jeffkaufman** [comment]
This looks like it's all set?  Please re-open if you're still having problems.
