### ISSUE TITLE
Does not work with Polymer 1.0

### ISSUE THREAD

**Issue by clayjar** [apache/incubator-pagespeed-mod#1089]
Try the picture-frame.html on https://www.polymer-project.org/1.0/docs/start/quick-tour.html.  You will notice that <div> encloses pagespeed-generated tag but not the img tag as it's supposed to.

**Comment by jmarantz** [comment]
I'm not following you.  mod_pagespeed does not appear to be running on
https://www.polymer-project.org/1.0/docs/start/quick-tour.html.

Can you give more details about what your setup is, what you expect to see,
and what you actually see instead?

-Josh

**Comment by mbana** [comment]
@clayjar, what happened to this?

**Comment by clayjar** [comment]
@mbana 2.0 will be coming out soon, and I haven't touched this for a while.  I guess the status would be pending for this one?
