### ISSUE TITLE
MapProxyDomain vs Response with "Alternate-Protocol" header

### ISSUE THREAD

**Issue by oschaaf** [apache/incubator-pagespeed-mod#1090]
Noticed at iispeed.com
When applying MapProxyDomain to `https://www.google-analytics.com/analytics.js`:
This response header will get forwarded: `Alternate-Protocol: 443:quic,p=1` in the optimized response.
That seems optimistic, I wish our server supported that :-)

Note that there's a hack in place to supress this right now, so it won't reproduce.

**Comment by jeffkaufman** [comment]
Do you think we should just strip out `Alternate-Protocol` in `MapProxyDomain` responses?

**Comment by oschaaf** [comment]
@jeffkaufman Yes, I think we should.
We might also want to check http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.5.1 to make sure other hop-by-hop headers are also not forwarded.
`Alternate-Protocol` is not on the list in the RFC, but it does classify as hop-by-hop as far as I can tell.

**Comment by jeffkaufman** [comment]
Fixed by https://github.com/pagespeed/mod_pagespeed/commit/d43f40b3c7b3b27dfce3350cea2d8b62f83cdc27
