### ISSUE TITLE
CSS parsing error

### ISSUE THREAD

**Issue by olimortimer** [apache/incubator-pagespeed-mod#1093]
Found a number of errors in my log file, advising that mod_pagespeed hit a "CSS parsing error" on a particular CSS file.

I found that `@charset utf-8;` at the top of the CSS file was causing the issue.  Once I changed this to `@charset "utf-8";` the file was able to be parsed correctly by mod_pagespeed.

Not sure if this was an error by the designer of the CSS file, and the quotes are required at all times, or an issue with mod_pagespeed not picking up the charset without quotes.

**Comment by jmarantz** [comment]
http://www.w3.org/International/questions/qa-css-charset gives the syntax with the quotes.  It does not state that the quotes are optional.

https://developer.mozilla.org/en-US/docs/Web/CSS/@charset specifically calls out the missing quotes as a syntax error.

**Comment by olimortimer** [comment]
Thanks @jmarantz

**Comment by mikkeschiren** [comment]
Also getting this error with some css files with bad characters in them - I had a third party css with a strange char in the end, removing that, and it works again.
