### ISSUE TITLE
AddOutputFilterByType MOD_PAGESPEED_OUTPUT_FILTER affects downloaded files

### ISSUE THREAD

**Issue by ghost** [apache/incubator-pagespeed-mod#1100]
If this configuration is active inside pagespeed.conf then all html files are affected. This is not desirable for downloaded files(when the user tries to download a html file from the website). Is this is a bug or a known issue, and is there a workaround? 

The file contains scripts like: pagespeed_no_defer="" type="text/javascript"

**Comment by jeffkaufman** [comment]
You need to tell PageSpeed what these files are so it knows not to mess with them.  We don't generally have a way to tell which html files are intended to be examples to be downloaded and saved vs which ones we're supposed to optimize.

The easiest way to tell PageSpeed to skip these is with a Location block:

```
<Location /html-that-people-download/>
ModPagespeed off
</Location>
```

See [Apache's `<Location>` docs](https://httpd.apache.org/docs/2.2/mod/core.html#location) for more on how to set these up, including `<LocationMatch>` to use a regex.
