### ISSUE TITLE
Build fails with gcc 5 due to compiler_version.py

### ISSUE THREAD

**Issue by rombert** [apache/incubator-pagespeed-mod#1101]
When building pagespeed from source with gcc 5 gyp_chromium  fails:

```
[   76s] + build/gyp_chromium -Duse_system_libs=1 -Duse_system_icu=1 -Dsystem_include_path_apr=/usr/include/apr-1 -Dsystem_include_path_httpd=/usr/include/apache2 -Dsystem_include_path_aprutil=/usr/include/apr-1
[   76s] Updating projects from gyp files...
[   76s] compiler_version.py failed to execute: g++ -dumpversion
[   76s] 'NoneType' object has no attribute 'group'
```

A patch which fixes this is at https://build.opensuse.org/package/view_file/Apache:Modules/apache2-mod_pagespeed/gcc5.patch?expand=1

**Comment by morlovich** [comment]
Does it just say 'version 5', rather than '5.0'?

**Comment by rombert** [comment]
Actually I'm not sure :-) gcc5 is not yet pushed to OpenSUSE Tumbleweed, this is a staging build.

**Comment by crowell** [comment]
related issue https://github.com/pagespeed/ngx_pagespeed/issues/942

**Comment by rombert** [comment]
For the record, `g++ -dumpversion` simply outputs `5`.

**Comment by crowell** [comment]
closed from https://github.com/pagespeed/mod_pagespeed/commit/ffd2adb960d437867b83ce52b3165fb4b561ce45 (master)

and 

https://github.com/pagespeed/mod_pagespeed/commit/8baf27dab7e4965ff75dbebbd29c60c18a902417 (branch 32)
