### ISSUE TITLE
Switch ubuntu buildbot to 12.04

### ISSUE THREAD

**Issue by crowell** [apache/incubator-pagespeed-mod#1103]
should we upgrade the builds for debs to be built with 12.04?

http://fridge.ubuntu.com/2015/03/18/ubuntu-10-04-lucid-lynx-reaches-end-of-life-on-april-30-2015/

**Comment by crowell** [comment]
another option is to use debian squeeze (6.x) as it is receiving LTS security updates until 2016

**Comment by jeffkaufman** [comment]
I'll move our ubuntu buildbot to 12.04 when I do the 1.10 release.

**Comment by crowell** [comment]
SGTM :+1:

**Comment by jeffkaufman** [comment]
did this a while ago
