### ISSUE TITLE
pagespeed problem

### ISSUE THREAD

**Issue by safetylab** [apache/incubator-pagespeed-mod#1113]
Hello,
my settings are : centos 6,apache 2.2.29,mod-pagespeed-stable-1.9.32.4-7251
ModPagespeedEnableFilters   recompress_images
ModPagespeedEnableFilters   convert_gif_to_png
ModPagespeedEnableFilters   convert_jpeg_to_progressive
ModPagespeedEnableFilters   recompress_jpeg
ModPagespeedEnableFilters   recompress_png
ModPagespeedEnableFilters   recompress_webp
ModPagespeedEnableFilters   strip_image_color_profile
ModPagespeedEnableFilters   strip_image_meta_data
ModPagespeedEnableFilters   jpeg_subsampling
ModPagespeedEnableFilters   insert_image_dimensions
ModPagespeedEnableFilters   resize_rendered_image_dimensions
ModPagespeedEnableFilters   add_head
ModPagespeedEnableFilters   combine_css
ModPagespeedEnableFilters   convert_meta_tags
ModPagespeedEnableFilters   extend_cache
ModPagespeedEnableFilters   flatten_css_imports
ModPagespeedEnableFilters   inline_css
ModPagespeedEnableFilters   inline_import_to_link
ModPagespeedEnableFilters   inline_javascript
ModPagespeedEnableFilters   rewrite_css
ModPagespeedEnableFilters   rewrite_images
ModPagespeedEnableFilters   rewrite_javascript
ModPagespeedEnableFilters   rewrite_style_attributes_with_url
AddOutputFilterByType MOD_PAGESPEED_OUTPUT_FILTER text/html
AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript

ModPagespeedDomain http://ivan.com
ModPagespeedDomain cd.ivan.com
# ModPagespeedMapOriginDomain cd.ivan.com  mir.ivan.com
# ModPagespeedMapRewriteDomain cd.ivan.com mir.ivan.com
# ModPagespeedMapOriginDomain localhost cd.ivan.com/mir mir.ivan.com
# ModPagespeedMapRewriteDomain cd.ivan.com/mir ivan.com/mir

working good with main domain ivan.com , but I can not set it up with sub domain mir.ivan.com and cdn cd.ivan.com
I tried settings 
ModPagespeedMapOriginDomain localhost cd.ivan.com/mir mir.ivan.com
ModPagespeedMapRewriteDomain cd.ivan.com/mir ivan.com/mir
or
ModPagespeedLoadFromFile "http://mir.ivan.com" "/home/is/public_html/mir/" 
but it did not work and breaks local css which looks like  /home/i/public_html/mir/css and should be loaded from cdn - cd.ivan.com 
appreciate your advice and help
thanks

**Comment by jeffkaufman** [comment]
It's not clear to me how your site is set up.  Is ivan.com your main site?  And then cd.ivan.com your cdn?  What is mir.ivan.com?

cd.ivan.com isn't resolving for me.

I'm not seeing any external resources on ivan.com, so I'm not sure what the cdn would be for?

**Comment by safetylab** [comment]
Is ivan.com your main site?   - Yes it is
 And then cd.ivan.com your cdn? - yes correct
 What is mir.ivan.com? - subdomain using same cdn

**Comment by jeffkaufman** [comment]
Is ivan.com running pagespeed?  I don't see the PageSpeed header:

```
$ headers ivan.com
HTTP/1.1 200 OK
Date: Mon, 27 Jul 2015 11:31:50 GMT
Server: Apache
Accept-Ranges: bytes
Content-Length: 11131
Content-Type: text/html
```

Anyway, the normal way to handle things if you have site (ivan.com) that uses a pull cdn (cd.ivan.com) is something like:

```
ModPagespeedMapRewriteDomain cd.ivan.com ivan.com
ModPagespeedEnableFilters rewrite_domains
```

Note that you don't need any `ModPagespeedDomain` lines.

This tells PageSpeed that when its rewriting html and sees a resource on ivan.com it should rewrite it onto cd.ivan.com, which it knows will then fetch through back to ivan.com on cache misses.

To add a second site (mir.ivan.com) to this we need to know how cd.ivan.com handles requests to separate ivan.com and mir.ivan.com.  Looking above I think you're using a subdirectory?  So cd.ivan.com/mir/foo fetches content that goes at mir.ivan.com/foo while cd.ivan.com/bar fetches content that goes at ivan.com/bar?  Is that right?  If so, you would add:

```
ModPagespeedMapRewriteDomain cd.ivan.com/mir mir.ivan.com
```

**Comment by jeffkaufman** [comment]
If this doesn't work, please reopen.
