### ISSUE TITLE
Pagespeed is not rewriting my website

### ISSUE THREAD

**Issue by prhomhyse** [apache/incubator-pagespeed-mod#1118]
I use the Nginx 1.8.0 and WP Super Cache.
I have rebuilt Nginx and the module is included when I type the command 

Nginx -V

but when i type 
 curl -D- http://mydomain.com | less

I don't see the X-Pagespeed there..

What is wrong and what do you suggest.
Thanks.

**Comment by crowell** [comment]
do you have pagespeed on in your configuration?

See this page for details: https://developers.google.com/speed/pagespeed/module/configuration

**Comment by prhomhyse** [comment]
I did. but never mind. got a new server. will work on it later. thanks
