### ISSUE TITLE
Don't accumulate waveforms if no one is looking at them

### ISSUE THREAD

**Issue by jmarantz** [apache/incubator-pagespeed-mod#1127]
Currently we collect a lot of waveform data in mod_pagespeed that has a non-trivial cost in memory & cpu.  However we don't even have a live admin-page tab to show them.  (at one point in the past we did, but it did not survive a refactor).

So we might as well not collect them until they are shown.

**Comment by jeffkaufman** [comment]
@jmarantz  Did https://github.com/pagespeed/mod_pagespeed/commit/53be049cf0f170ff4342d9dfb11974e65745d3ea fix this?

**Comment by jmarantz** [comment]
yes
