### ISSUE TITLE
pagespeed should have an option to add no-transform header

### ISSUE THREAD

**Issue by jmarantz** [apache/incubator-pagespeed-mod#1129]
PageSpeed honors no-transform headers on origin resources, but it should be possible for sites to add no-transform headers to PageSpeed's generated resources, to avoid re-optimization of images.

**Comment by jeffkaufman** [comment]
#1005 would let us do that.  Closing this as a special case of that issue.

**Comment by oschaaf** [comment]
@jeffkaufman I'm not sure I follow, how would https://github.com/pagespeed/mod_pagespeed/issues/1005 let sites add no-transform headers to PageSpeed's generated resources?

**Comment by oschaaf** [comment]
@jeffkaufman Wait, I think you meant ngx_pagespeed's issue 1005, https://github.com/pagespeed/ngx_pagespeed/issues/1005 - sorry!

**Comment by jeffkaufman** [comment]
Yes, sorry, https://github.com/pagespeed/ngx_pagespeed/issues/1005
