### ISSUE TITLE
On Firefox, CSS is not minified and inlined correctly

### ISSUE THREAD

**Issue by huibaolin** [apache/incubator-pagespeed-mod#1144]
To reproduce, try "http://www.seniorsfirst.com.au/?PageSpeed=on" on Firefox. The menu, which ought to be in one row at the top of page, is shown in a column. See screenshot "Bug.png".

This bug doesn't happen on Chrome or when 'rewrite_css' is turned off. See "Good.png".

The related CSS, in its original format, is
<link rel='stylesheet' id='boc-style-css'  href='http://www.seniorsfirst.com.au/wp-content/themes/Savia/style.css?ver=4.3.1' type='text/css' media='all' />

When it is correctly optimized, it's
<style id='boc-style-css' media='all'>@import url(wp-content/themes/Savia/stylesheets/skeleton.css) ;@import url(wp-content/themes/Savia/stylesheets/stylesheet.css) ;@import url(wp-content/themes/Savia/stylesheets/flexslider.css) ;@import url(wp-content/themes/Savia/stylesheets/prettyPhoto.css) ;@import url(wp-content/themes/Savia/stylesheets/carousel.css) ;</style>

When the bug happens, it's empty.
<style id='boc-style-css' media='all'></style>

![good](https://cloud.githubusercontent.com/assets/6412463/10048203/d6e441f8-61df-11e5-995f-d0b1d7e0db5e.png)
![bug](https://cloud.githubusercontent.com/assets/6412463/10048201/d6e26838-61df-11e5-9ec4-577a6448a9b1.png)

**Comment by jeffkaufman** [comment]
This looks like https://github.com/pagespeed/mod_pagespeed/issues/1068 to me.  That was fixed in 1.9.32.6 and they're running 1.9.32.4.  I suggested via email that they upgrade.
