### ISSUE TITLE
add this strings to .htaccess disable all mod_pagespeed functions

### ISSUE THREAD

**Issue by cheluskin** [apache/incubator-pagespeed-mod#1146]
<IfModule mod_headers.c>
       Header unset ETag
       Header unset Pragma
       Header unset Last-Modified
       Header append Cache-Control "public, no-transform, must-revalidate"
       Header set Last-modified "Tue, 1 Oct 2014 10:10:10 GMT"
</IfModule>

**Comment by jmarantz** [comment]
I don't understand the context for your post.  If you want to disable
mod_pagespeed, you can simply put this into the .htaccess
  ModPagespeed off
The suggestion you gave just disables external resource rewriting, and will
not affect HTML-minification, lazyload_images, defer_javascript,
minification of inline CSS and JavaScript, and numerous other filters.

-Josh

**Comment by cheluskin** [comment]
These lines disable all filters and it is wrong, I think. Just try it.

**Comment by jeffkaufman** [comment]
Setting "no-transform" on your resources does disable PageSpeed optimizations, but that's exactly how we should treat that cache-control directive.  The "no-transform" directive tells intermediate services (like PageSpeed) that your content is sensitive and that modifying it would cause problems.  So we don't modify it.

Why are you setting these directives in your .htaccess file?  What are you trying to accomplish?
