### ISSUE TITLE
webp transcoding does not work for MapProxyDomain resources written in-place.

### ISSUE THREAD

**Issue by jmarantz** [apache/incubator-pagespeed-mod#1149]
If you have 
  MapProxyDomain mps_host/origin origin_host/static
a request for:
  http://mps_host/origin/foo.jpg
will not be transcoded to webp.

This might seem like an odd case, because why would a browser request http://mps_host/origin/foo.jpg?  It works fine with MapProxyDomain when there is URL rewriting in HTML, in which case the webp request is encoded in the rewritten URL and it is not rewritten in-place.

However you can in theory construct an HTML page with MapProxyDomain and a bunch of references to external images via their manually rewritten proxied location, say, as a demo showing the benefits of passing those images through MPS.

**Comment by jeffkaufman** [comment]
Fixed by 52f0d46
