### ISSUE TITLE
pedantic filter should prevent inlining CSS into the body

### ISSUE THREAD

**Issue by ghost** [apache/incubator-pagespeed-mod#1153]
Automatic CSS inlining leaves `<style>` tag inside `<body>`, making the pages invalid.

**Comment by jeffkaufman** [comment]
I'm not sure what you're asking.  Can you give an example of a page with this problem, showing what it looked like originally and what it looked like after PageSpeed modified it?

**Comment by ghost** [comment]
Example:

``` html
<body>
  <p>blablabla</p>
  <link rel="stylesheet" property="stylesheet" href="https://something/whatever.css" />
</body>
```

will be modified to

``` html
<body>
  <p>blablabla</p>
  <style property="stylesheet">
    // Something
  </style>
</body>
```

I think you just don't know what "valid" means. "Valid" here means passing the W3C validator.
This is not a big problem, but if it doesn't inline styles in the `<body>` tag, it will be very useful for those who are requested to make the page "valid" like me.

**Comment by jmarantz** [comment]
Inlining CSS has substantial benefits to web-site latency which is the main goal of PageSpeed. In some cases, W3C validators flag constructs that are supported by all browsers, and PageSpeed has a choice as to whether to optimize for the validator or optimize for the end-user.  By default, PageSpeed has prefers optimizing for the end-user.

PageSpeed also has a 'pedantic' filter which, if specified, ought to avoid having PageSpeed introduce new validator violations in the page.  However, it probably doesn't cover this case, and that's a bug.

You probably want to turn the pedantic filter when running validators.  So when you type your URL into w3c validation tool, you can append:
   ?PageSpeedFilters=+pedantic
If you don't like that idea, and want your site valid all the time, then you can put
  ModPagespeedEnableFilters pedantic
into your pagespeed.conf, which will make your site slower.

And having said that, I believe this case is not covered by the 'pedantic' filter, and I'm wording this bug title to reflect that.

Old title: CSS embedment makes pages invalid

**Comment by jmaessen** [comment]
My understanding had been that <link> elements in <body> were also forbidden by validation – does the original page validate?

**Comment by jeffkaufman** [comment]
The pedantic filter inserts some things that are required by html4 but not html5.  So we might need a pedantic5 filter for this case.

**Comment by ghost** [comment]
Original page with that kind of `<link>` validates.
