### ISSUE TITLE
Add newlines between combined css files

### ISSUE THREAD

**Issue by jeffkaufman** [apache/incubator-pagespeed-mod#1165]
When a css file where the last line has an unclosed quote is combined with another css file this changes the behavior of css.  Normally the browser would stop looking for a matching quote at end of line, but here it will continue looking into the next file.

This caused this bug: https://groups.google.com/d/msgid/mod-pagespeed-discuss/CAHRWggQ0%2B%2Ba-%3DaiVGLVizO-2004TNS9Hr%2BG2y1Qy5MT7VhOdrQ%40mail.gmail.com

As a fix, we should add newlines between css files we combine.

**Comment by morlovich** [comment]
Trying to come up with a small testcase (and having some difficulties)

**Comment by morlovich** [comment]
Resolved with the above change.
