### ISSUE TITLE
Directing serf at alternate port #

### ISSUE THREAD

**Issue by allklier** [apache/incubator-pagespeed-mod#1172]
In our new configuration Apache w/ pagespeed runs on port 8080, while Varnish 4 listens on port 80. For the most part that runs pretty well, except the serf requests from pagespeed go back to port 80 and through Varnish, which is unnecessary and complicates monitoring of backend connections via mod_qos.

I've tried to configure pagespeed so that it would send serf requests directly to Apache on port 8080 but my attempts and plenty of searches online came up empty.

Here's what I've tried: 

  ModPagespeedMapOriginDomain xxx.com xxx.com:8080

Yet I still see this in the Varnish log (IP 192.254.214.183 is the IP of the host running both Varnish and Apache) so this is an internal call from pagespeed looping through Varnish.
-   BereqHeader    User-Agent: Serf/1.1.0 mod_pagespeed/1.9.32.4-7251
-   BereqHeader    PS-CapabilityList: fully general optimizations only
-   BereqHeader    X-Forwarded-For: 192.254.214.183
-   BereqHeader    Accept-Encoding: gzip
-   BereqHeader    X-Varnish: 393497
-   VCL_call       BACKEND_FETCH

Any ideas / suggestions on how to tell Serf to use port 8080 instead of 80?

I could try the static file loading, but then I don't get to attach expiration headers which improve our performance.

**Comment by jmarantz** [comment]
I think the problem is that you flipped the arguments to MapOriginDomain.  From the doc:

ModPagespeedMapOriginDomain origin_to_fetch_from origin_specified_in_html [host_header]

So you probably want:

ModPagespeedMapOriginDomain xxx.com:8080 xxx.com

**Comment by allklier** [comment]
Duh, that seemed to have been indeed the problem. Thanks for setting me straight.
