### ISSUE TITLE
How can I send domain to ModPagespeedDownstreamCachePurgeLocationPrefix?

### ISSUE THREAD

**Issue by sirshurf** [apache/incubator-pagespeed-mod#1175]
I am trying to implement mod_pagespeed with my website.

My current configuration is:

NGINX with srcache configured with memc to memcache. Behind it I have Apache on diferent port.

My problem is, since I have multiple subdomains I have a memc key as follows:

```
    set $key $http_host$request_uri;
```

This means that I need to pass subdomain to the system in order for it to catch the domain and fill the key correctly.

But the key in apache for it is:

```
    ModPagespeedDownstreamCachePurgeLocationPrefix http://CACHE-HOST:PORT/purge
```

How can I add my subdomain here?

**Comment by jeffkaufman** [comment]
We can't currently do this in Apache because we don't support Apache's environment variables.  I've opened a bug: https://github.com/pagespeed/mod_pagespeed/issues/1179
