### ISSUE TITLE
Add link rel=canonical on rewritten images and pdfs

### ISSUE THREAD

**Issue by jeffkaufman** [apache/incubator-pagespeed-mod#1184]
See https://support.google.com/webmasters/answer/139066?hl=en

**Comment by jeffkaufman** [comment]
fixed in 0ea2124fcdb0ae94e2

**Comment by ademarre** [comment]
I'm eager to deploy this feature, but it is 11 months old now and still unreleased. Is this planned for the next minor release, and if so when is that? Thanks.

**Comment by oschaaf** [comment]
@ademarre As far as I can tell this feature was released in `1.10.33.0`, however:

What seems a bit odd is that when I check the commit that adressed this (https://github.com/pagespeed/mod_pagespeed/commit/0ea2124fcdb0ae94e25383ac8f689b18edbedd26) to see on which branches it was included, for `1.11.3.x` it only shows up for `1.11.33.3`, which seems odd (what about `1.11.33.2` and `1.11.33.1`?).

What version of mod_pagespeed are you currently running?

**Comment by ademarre** [comment]
Thanks @oschaaf

I'm currently running 1.11.33.2. I must have been wrong about it not being released...

```
$ git branch -r --contains 0ea2124
  origin/1.10.33.4-scratch
  origin/1.10.33.6
  origin/1.10.33.7
  origin/1.11.33.0
  origin/1.11.33.1
  origin/1.11.33.2
  [...]
```

The commit is in the 1.11.33.2 branch. (I don't see a tag for that release, so I'm assuming that branch is correct.) But I'm not seeing the canonical link header on rewritten images. I'm an outsider on this codebase, but might it be related to the fix in 1ddc05c which has not been released?

My config is essentially this:

```
ModPagespeed on
ModPagespeedRespectVary on
ModPagespeedPreserveUrlRelativity on
ModPagespeedMapProxyDomain https://www.example.com/pagespeed/proxy/cdn https://cdn.example.com
ModPagespeedRewriteLevel CoreFilters
ModPagespeedEnableFilters prioritize_critical_css,insert_dns_prefetch
```

Is the rel=canonical link not added for proxied images?

**Comment by ademarre** [comment]
According to John Mueller, [Google doesn't use rel=canonical for images](https://www.seroundtable.com/google-rel-canonical-for-images-nope-22549.html):

> On the one hand, for images we don't use the rel=canonical. So if you have the rel=canonical header in the images themselves, we don't use that.

I still feel it's correct to set the header if possible though. In principle it seems like an accurate signal to broadcast, and one that might become more meaningful to Google in the future.

**Comment by jmarantz** [comment]
@ademarre please read the comments on that link you gave.  In particular:

"I wondered the same thing when configuring maxcdn a while ago. They add the canonical source to the http header sent from the CDN, which is not the same as adding a rel="canonical" to an html file. Google started supporting this method in 2011: https://webmasters.googleblog....

I think John must have meant canonical within an image file is not recognized. I have several sites using CDNs with canonical headers and the CDN versions of images don't show up in search while the originals do."

**Comment by oschaaf** [comment]
@ademarre Testing, I don't see the bleeding edge of mod_pagespeed adding a `Link` header for requests routed via `MapProxyDomain`. I think that would be a new feature - so you could consider opening a new issue with a feature request for that.

**Comment by ademarre** [comment]
@jmarantz, considering the context in that Google Hangout video, I doubt John Mueller was referring to setting canonical links _within_ image files. I've never heard of such a thing. Perhaps John is simply mistaken, but I'm more inclined to believe his explanation than that commenter's anecdotal account. The [cited blog](https://webmasters.googleblog.com/2011/06/supporting-relcanonical-http-headers.html) makes clear that the rel=canonical link header is supported for PDFs, but says nothing about images.

Nonetheless, this probably isn't the right forum for this discussion.

Thanks for your help, guys!

UPDATE: [Confirmation from John via Twitter](https://twitter.com/JohnMu/status/768024243544133633):

> We don't use rel=canonical for images in Image Search. We do use it for PDFs in web-search though.
