### ISSUE TITLE
Prioritize Critical CSS writes a mixture of optimized and unoptimized content

### ISSUE THREAD

**Issue by jeffkaufman** [apache/incubator-pagespeed-mod#1187]
Fixed in 98ffc6e1c4926765fb330a09ee35995416d7bbcc

**Comment by eldk** [comment]
Hello,
I have switch to 1.10.33.0-beta.
On first run, one css file (sometimes three, sometimes four are requested for one page) is missing, so some page styling are not applied.
After a few request on the page with the browser, styles are good (no more mixture)

I use ModPagespeedRewriteLevel OptimizeForBandwidth
with those optional filters : 
ModPagespeedEnableFilters lazyload_images,convert_to_webp_lossless,combine_css,trim_urls,remove_comments,collapse_whitespace,prioritize_critical_css,insert_dns_prefetch,combine_javascript,defer_javascript
- ipro (enable by default) and loadfromfiles (not for CSS) for images.

This was set prior to migration to MPS 1.10 and page was good on first run
ModPagespeedCssInlineMaxBytes        10240 
With same option now, one CSS file (that was the target of ModPagespeedCssInlineMaxBytes        10240) does not load on first page request.
`<link rel="stylesheet" href="thelongestfrom2048bytes.css">` disappeared from html source return by mod_pagespeed on the first run and stylesheet is not loaded.

Greatings,

Eric

**Comment by eldk** [comment]
Ok solved : remove combine_css from ModPagespeedEnableFilters  and all goes good.

**Comment by jeffkaufman** [comment]
That's a workaround, and I'm glad that fixed your problem, but this is still a bug and something we need to fix.  CSS files should never be dropped because that breaks pages.  Moved to a new bug: https://github.com/pagespeed/mod_pagespeed/issues/1215
