### ISSUE TITLE
Option to not rename cacheable assets

### ISSUE THREAD

**Issue by GuillaumeRossolini** [apache/incubator-pagespeed-mod#1201]
Hi,
Would it be possible to have a configuration option to tell mod_pagespeed that my CSS and JS assets are already cacheable as-is, and renaming their URL would break my pages?
I still want mod_pagespeed to parse these assets and to inline code into the HTML, I just want it to not rename their full URL while it doing this.
I guess this is mostly useful with the "prioritize_critical_css" rule.
Thanks,

**Comment by GuillaumeRossolini** [comment]
I guess I don't need the "extend_cache" filter at all in my case. I didn't enable it myself, is it included in any other option?

**Comment by oschaaf** [comment]
- For preventing url renaming, there is https://developers.google.com/speed/pagespeed/module/config_filters#preserveurls. Alternatively you could start out with `ModPagespeedRewriteLevel OptimizeForBandwidth` instead of the default `CoreFilters`: https://developers.google.com/speed/pagespeed/module/optimize-for-bandwidth
- extend_cache is in the set of core filters, and as such turned on by default: https://developers.google.com/speed/pagespeed/module/config_filters

If you want to optimize without url-renaming, but have critical css prioritization enabled, you could try if this works for you:

```
  ModPagespeedRewriteLevel OptimizeForBandwidth
  ModPagespeedEnableFilters prioritize_critical_css
```

Note that the `prioritize_critical_cs` filter may remove link tags for stylesheets from the html once it takes effect and replace those with inlined css, thereby altering the document object model (which might be an issue considering that renaming urls was indicated as undesirable for you).

**Comment by jmarantz** [comment]
It's possible you can come up with a way to get inlining without URL
renaming, but it's not a scenario we anticipated.  Our thinking was that
either you wanted to preserve all URLs or you didn't, and if you are
inlining external files you are not really preserving their URLs.

What's the motivation to allow inlining but forbid renaming URLs?  E.g. if
you are worried about breaking your pages, wouldn't inling a CSS or JS file
also break your JS that looks for URLs by scanning the DOM looking for
<script src=X> or <link rel=stylesheet href=Y>?

-Josh

**Comment by GuillaumeRossolini** [comment]
Hi,

The rationale is that we optimized our infrastructure resources for HTTP/1.1 with a few easy tricks:
- each versioned URL points to the same file on disk (ie. "www.1.css", "www.2.css" etc. point to "www.css"), with infinite browser caching so we don't need mod_pagespeed to rewrite our asset URLs;
- domain sharding for assets: they are in fact aliases of the same domain and we use "rel canonical" HTTP headers to avoid duplicate SEO for images;
- 1 host serves the content (HTML) with httpd on the www domain while the other host serves assets with nginx on sharded domains cdn, cdn1, cdn2, media, media1, media2;
- all domains are not on the same host, their contents are not perfectly in sync with each other;
- when installed on the www domain (httpd), mod_pagespeed has no write access to the folders served by our asset domains (nginx);
- cdn\* and media\* domains have different rewrite rules but they share the same docroot;

We will eventually migrate to some form of cloud/scalable infrastructure, but at the moment this is what we have.

For instance when httpd serves HTML with a CSS that points to our big https://cdn.domain.com/www.3.css, I'd like mod_pagespeed to help optimize browser rendering by inlining the CSS rules used for rendering of the first screen, then add some kind of prefetch rule so the whole CSS file gets loaded too.At the moment, mod_pagespeed does in fact import critical CSS rules into the HTML, but it also rewrites the URL of the "www.3034.css" asset to something like "A.www.3034.css.pagespeed.cf.BsVCwDmtQa.css", even though it is served from another host. We do not need this rewrite, because our asset URLs are already compatible with browser caching and they are versioned. Rewriting them causes more downloads, and makes filenames longer than our simple versioning scheme.
I guess another way would be to add rewrite rules for nginx so the URLs rewritten by mod_pagespeed still point to the same disk file, but in this case we would cause the browser to download several times the same file (not all pages are rewritten by mod_pagespeed). In fact we tested this approach and it works, but is not very effective.

We now use HTTP/2 as well and we will eventually remove domain sharding, but the server split (httpd VS nginx) will likely remain.

About your recommendations:
- we are using "ModPagespeedRewriteLevel PassThrough";
- we didn't specifically add "extend_cache";
- we have already tried "ModPagespeedCssPreserveURLs On" but it does not prevent mod_pagespeed from rewriting this the URL of the CSS;

Also, regarding: "Note that the prioritize_critical_cs filter may remove link tags for stylesheets from the html once it takes effect and replace those with inlined css, thereby altering the document object model (which might be an issue considering that renaming urls was indicated as undesirable for you)."
-> this is exactly what we need, we just don't wah mod_pagespeed to inject a rewritten URL: we want it to inject the provided URL as-is, because it is already suitable for optimal browser caching.

Any help would be appreciated.
If a demo would help, I can provide access to our testing platform, but I'd rather avoid public discussion for this.

Regards,

**Comment by GuillaumeRossolini** [comment]
Maybe a (simple?) solution would be to inspect the HTTP caching headers of said asset while you are fetching it. If it looks cacheable already, why bother renaming it and cacheing another copy?
What do you think?

**Comment by oschaaf** [comment]
Before my initial reply, I ran a quick test with this configuration on the mod_pagespeed_examples index:

```
ModPagespeedRewriteLevel OptimizeForBandwidth
ModPagespeedEnableFilters prioritize_critical_css,debug
```

For me, this resulted in no changes to urls for critical css prioritization:

``` html
<!doctype html>
<html>
  <head>
<!-- index_style.css inlined css follows: -->
    <style>body{font-family:arial;font-size:.9em}.filter_row{background-color:#eee;border:1px solid #000;padding:1em}.code{font-family:monospace;width:20%;padding:1em}.inline_code{font-family:monospace;width:20%}.menu{background-color:#ebeff9;width:100%;list-style:none;height:37px;padding-left:3px;padding-top:2px;margin:0}.menu li{display:inline-block;vertical-align:middle;padding-left:0}.menu a{display:block;padding-left:1em}td.before,td.after{padding-left:1em;width:10%}#pname{font-size:200%;margin:0;padding:0}</style>
  </head>
  <body>
....snip...
<!--Summary computation status for CriticalSelectorFilter
Resource 0 http://192.168.137.10:8090/mod_pagespeed_example/styles/index_style.css: Computed OK
--><noscript class="psa_add_styles"><link rel="stylesheet" href="styles/index_style.css"/></noscript>
... snip ....
```

Retesting `prioritize_critical_css` with `RewriteLevel PassThrough` and `CssPreserveUrls on`: that doesn't result in a changed css url  for me either.

Does the optimized html look like what you need?

**Comment by GuillaumeRossolini** [comment]
Hi,
As long as there is an additional "style" tag that includes inlined styles, and our original "stylesheet" link remains (although as a deferred download), we will be happy with the results.
We will be trying more settings this week.
By the way, in this context "inline" means "inside the HTML document" and not "as a 'style' attribute of the targetted tag", right?
Thanks,

**Comment by GuillaumeRossolini** [comment]
My bad, I didn't write the name of the filter correctly:
Wrong:

```
ModPagespeedCssPreserveUrls On
```

Right:

```
ModPagespeedCssPreserveURLs On
```
