### ISSUE TITLE
File cache entries are read in 10k chunks

### ISSUE THREAD

**Issue by jeffkaufman** [apache/incubator-pagespeed-mod#1203]
We could use a stat and read whole files at once, but currently we read files in fixed size chunks.  Since we need the whole file in memory, this is pretty wasteful.

**Comment by jeffkaufman** [comment]
Fixed in 56e4c8ddfa646d2265f1294decf12a24a23a8b8e

**Comment by keesspoelstra** [comment]
What about side effects/behavior with RewriteLevel PassThrough?

**Comment by jeffkaufman** [comment]
@keesspoelstra  Huh?  I wouldn't expect 56e4c8d to affect passthrough, because that shouldn't be using the file cache at all.

**Comment by keesspoelstra** [comment]
Wrong issue, should be a remark for 973, sorry
