### ISSUE TITLE
Don't emit type=text/javascript on script tags

### ISSUE THREAD

**Issue by GuillaumeRossolini** [apache/incubator-pagespeed-mod#1207]
Hi,
I noticed mod_pagespeed includes a new "script" tag inside "head". Which is normal, but in this case the head already had a "script" tag:

```
<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" xmlns:g="http://base.google.com/ns/1.0" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://ogp.me/ns/fb#" xml:lang=en lang=en>
<head>
<script type='text/javascript'>window.mod_pagespeed_start = Number(new Date());</script><script>var FileAPI={
```

Maybe there could be a way to merge these tags? Although their declaration is not strictly identical, I have heard that for certain doctypes, the "type" attribute of the "script" tag is unnecessary. Maybe stripping this attribute could be another "less bytes" optimization for pagespeed, and in this case merging two tags as well?
Thanks,

**Comment by oschaaf** [comment]
My 2p on merging script tags: when you merge script tags, you have to make sure that an exception that happens in code originating from one script block does not interfere with execution of merged code from another script block.
So I think you would have to add js code for that,  which I suspect might offset the benefit of saving the script-open and script-close tags in the first place.

As for eliminating `type` attributes for `script` tags: the Elide Attributes filter will do that for you if you serve html 5. You can maybe try it on your site with `?PageSpeedFilters=+elide_attributes`
See https://developers.google.com/speed/pagespeed/module/filter-attribute-elide

**Comment by GuillaumeRossolini** [comment]
Oh, you might be right about the exceptions.
As for the Elide filter, it does not seem to have much effect on pagespeed-issued tags: the output I gave you had Elide activated, as it is part of standard config in my case (see both lang="en" attributes from the <html> declaration: they were shortened as lang=en).

**Comment by oschaaf** [comment]
Perhaps the filters that inject those script tags run after the elide-attributes filter. I'm not sure if that is by design.. When I paste that html and run the elide_attributes filter on it, the type attribute does get elided. @jeffkaufman ?

**Comment by GuillaumeRossolini** [comment]
I tried enabling elide_attributes last to see what happens, but no luck.
Maybe you could make the order in which filters are added relevant?

**Comment by jeffkaufman** [comment]
merging tags: it doesn't save much in terms of bytes and it's pretty dangerous

removing the text/javascript tag on pagespeed scripts: why don't we just stop emitting this tag unless the pedantic filter is on?

**Comment by oschaaf** [comment]
Not emitting the `type` attribute unless pedantic is turned on (and we are serving a html 5 doc?) sounds good to me

**Comment by jeffkaufman** [comment]
Added to https://github.com/pagespeed/mod_pagespeed/wiki/Work-Prioritization

**Comment by jmarantz** [comment]
Can we make that have a 100% accurate view of whether browsers will
interpret a doc as HTML5. I think this has come into question in the past.

**Comment by jeffkaufman** [comment]
We don't need to know if it's html5; leaving off `type=text/javascript` doesn't cause problems in browsers even with html4. It's just not (pedantically) spec until html5.

**Comment by GuillaumeRossolini** [comment]
Hi,
While you are at it, maybe you could also do away with the //<![CDATA[ and its closing //]]> counterpart?

**Comment by jeffkaufman** [comment]
We need that (only in Apache) because we don't know if the page is xhtml.  If it is, then failing to include CDATA would break the page.

On the other hand, extremely few pages are xhtml these days, so it's possible that with an upcoming release we could require you to explicitly set something in your config if you wanted us to treat the page as xhtml.

**Comment by GuillaumeRossolini** [comment]
Yes, I meant with HTML5, and with the same exception rules you defined for `type=text/javascript` (nonpedantic). Or a config option would work too.
