### ISSUE TITLE
Problems when trying to update .css files

### ISSUE THREAD

**Issue by Ziiweb** [apache/incubator-pagespeed-mod#1210]
Hi,

I have installed 2 weeks ago the latest version of this module, the unstable one.

I have just updated the color of login inputs (kind of yellow)  at www.procomunicaciones.es to #f6ff9f as you can see here:

http://procomunicaciones.es/css/0e65e07.css

but now the color is not being updated, that is: it still shows the old #f6ffa4

Why? How should I install the stable one to try if it works ok?

**Comment by oschaaf** [comment]
See https://developers.google.com/speed/pagespeed/module/faq#ignores-changes for why mod_pagespeed behaves as you are seeing, and for tips on how to refresh optimized files more often (or even instantly via `ModPagespeedLoadFromFile`). 

I don't think this behavior is related to using the latest beta version, I expect you will experience the same behavior with the latest stable. Regardless, https://developers.google.com/speed/pagespeed/module/download contains instructions for installing both beta and stable versions.
