### ISSUE TITLE
3 failed tests

### ISSUE THREAD

**Issue by GuillaumeRossolini** [apache/incubator-pagespeed-mod#1211]
Hi,

I already had these errors last week but I didn't take the time to report them.
3 tests failed with today's release:

```
./out/Release/mod_pagespeed_test
[...]
[  FAILED  ] 1 test, listed below:
[  FAILED  ] AprFileSystemTest.TestRecursivelyMakeDir_NoPermission
```

```
./out/Release/pagespeed_automatic_test
[...]
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] StdioFileSystemTest.TestRecursivelyMakeDir_NoPermission
[  FAILED  ] InprocessShm/SharedMemStatisticsTestTemplate/0.TestHistogramRender, where TypeParam = net_instaweb::(anonymous namespace)::InProcessSharedMemEnv
```

I followed instructions at https://developers.google.com/speed/pagespeed/module/build_mod_pagespeed_from_source
Please tell me what details you might need.

Regards,

**Comment by oschaaf** [comment]
@Kirkis are you running these tests as root?

**Comment by jmarantz** [comment]
You were running the tests as root.  They are designed to be run as a
normal user.

**Comment by GuillaumeRossolini** [comment]
Yes I was. My bad if that's the whole problem.
