### ISSUE TITLE
Missing CSS files with OptimizeForBandwith + combine_css

### ISSUE THREAD

**Issue by jeffkaufman** [apache/incubator-pagespeed-mod#1215]
Moved from https://github.com/pagespeed/mod_pagespeed/issues/1187#issuecomment-164601069

I have switch to 1.10.33.0-beta.
On first run, one css file (sometimes three, sometimes four are requested for one page) is missing, so some page styling are not applied.
After a few request on the page with the browser, styles are good (no more mixture)

I use ModPagespeedRewriteLevel OptimizeForBandwidth
with those optional filters : 
ModPagespeedEnableFilters lazyload_images,convert_to_webp_lossless,combine_css,trim_urls,remove_comments,collapse_whitespace,prioritize_critical_css,insert_dns_prefetch,combine_javascript,defer_javascript

ipro (enable by default) and loadfromfiles (not for CSS) for images.
This was set prior to migration to MPS 1.10 and page was good on first run
ModPagespeedCssInlineMaxBytes 10240 
With same option now, one CSS file (that was the target of ModPagespeedCssInlineMaxBytes 10240) does not load on first page request.
<link rel="stylesheet" href="thelongestfrom2048bytes.css"> disappeared from html source return by mod_pagespeed on the first run and stylesheet is not loaded.

**Comment by oschaaf** [comment]
Hacked gtest that reproduces (and fails): https://gist.github.com/oschaaf/15a9a429867ee18ea622

**Comment by jeffkaufman** [comment]
Fixed with https://github.com/pagespeed/mod_pagespeed/commit/55e0962b1fa0eb8ff67028a0f1d616b164dc28f0

**Comment by jeffkaufman** [comment]
This applies to 1.9.x as well too, right?

**Comment by morlovich** [comment]
Probably best to just run the test to see?
