### ISSUE TITLE
Tracking bug: 1.10.33.0 issues

### ISSUE THREAD

**Issue by jeffkaufman** [apache/incubator-pagespeed-mod#1216]
- Issues fixed in 1.10.33.1:
  - webp served to uas that don't support it: https://github.com/pagespeed/mod_pagespeed/issues/1218
  - crash reported in gzip header setting: https://github.com/pagespeed/mod_pagespeed/issues/1219
- Issues planned for 1.10.33.2:
  - missing CSS files: https://github.com/pagespeed/mod_pagespeed/issues/1215 (https://github.com/pagespeed/mod_pagespeed/commit/55e0962b1fa0eb8ff67028a0f1d616b164dc28f0)
  - extra rel=canonical headers with ipro: https://github.com/pagespeed/mod_pagespeed/issues/1222 ( fixed in https://github.com/pagespeed/mod_pagespeed/commit/61f4e964aba4d4adfe0e73673e3012433fbde258 )
  - improve handling of nested rewrites #1226 https://github.com/pagespeed/mod_pagespeed/commit/024eb91ed45a95d3ff4718b226a4ee219d35f58b
  - nginx's noisy startup is back https://github.com/pagespeed/ngx_pagespeed/issues/808
    - main fix is in https://github.com/pagespeed/ngx_pagespeed/commit/37e1c36
    - also needs a change to not put newlines in logging messages ( b6a955a )
  - disallow newlines in content-type meta tag https://github.com/pagespeed/mod_pagespeed/issues/1083 ( @oschaaf has a fix in https://github.com/pagespeed/mod_pagespeed/pull/1196 ) 2cea12ce1157ff4e7ae0944578eeeef88110eacf
  - incompatibility with old apr versions https://github.com/pagespeed/mod_pagespeed/issues/1224 (fix is f3edc3b) 
- Issues planned for 1.10.33.3
  - DCHECK-fail in css summarizer https://github.com/pagespeed/ngx_pagespeed/issues/891
  - real fix for https://github.com/pagespeed/mod_pagespeed/issues/1215, that allows people to do optimizeforbandwidth+combinecss

**Comment by jeffkaufman** [comment]
We've reproduced the WebP issue and @morlovich is working on a fix now.

I sent out an announcement asking people to hold off on upgrading to 1.10 and giving commands to temporarily disable WebP conversion.

**Comment by eldk** [comment]
Hello,
- https://github.com/pagespeed/mod_pagespeed/commit/5a51f2500128a503ce8bf436536115fa9345961e
- crash reported in gzip header setting

I have switch to 1.10.0.0-7580 and re-enable convert_jpeg_to_webp and convert_to_webp_lossless.
Thanks,
Eric

**Comment by jeffkaufman** [comment]
@eldk Let me know if you still see those issues; I'm getting ready to push that out as 1.10.33.1

**Comment by eldk** [comment]
OK @jeffkaufman let's run a couple of hours and feedback

**Comment by jeffkaufman** [comment]
1.10.33.1 will be going out within the hour with fixes for #1218 and #1219.   #1215 is going to take more work, and is going to need to wait for a 1.10.33.2, which I'm hoping to get out later this week.

**Comment by eldk** [comment]
@jeffkaufman  https://github.com/pagespeed/mod_pagespeed/issues/1219

> Let me know if you still see those issues; I'm getting ready to push that out as 1.10.33.1

Hello,
No more off those errors in apache error.log since yesterday update.
Thanks

**Comment by jeffkaufman** [comment]
@eldk Thanks!

**Comment by jeffkaufman** [comment]
Planning to start building 1.10.33.2 tomorrow and release on monday.

**Comment by crowell** [comment]
1.10.33.2/3/4/5 have been release. closing

**Comment by ldkafka** [comment]
The issue happens in both the latest release of the .9 stable and .10 beta WITHOUT debug compile options.

[alert] 2209#2353: [ngx_pagespeed 1.9.32.14-0] [0427/153923:FATAL:css_summarizer_base.cc(327)] Check failed: canceled_summaries_.empty().

**Comment by oschaaf** [comment]
@auratravel Could you show us how you precisely installed / built ngx_pagespeed? That failure originates from a DCHECK which should only fire for debug builds.
Note that https://github.com/pagespeed/ngx_pagespeed/issues/891(which tracks this specific issue)  is still open, but I wouldn't expect this to show up in a release build.

**Comment by ldkafka** [comment]
@oschaaf

nginx version: nginx/1.9.10
built with OpenSSL 1.0.1k 8 Jan 2015
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt='-fPIE -pie -Wl,-z,relro -Wl,-z,now' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_mp4_module --with-http_perl_module --with-http_random_index_module --with-http_secure_link_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --with-mail --with-mail_ssl_module --with-stream --with-stream_ssl_module --with-threads --add-module=/home/leo/work/debian_package_build/nginx-1.9.10/debian/modules/headers-more-nginx-module --add-module=/home/leo/work/debian_package_build/nginx-1.9.10/debian/modules/nginx-auth-pam --add-module=/home/leo/work/debian_package_build/nginx-1.9.10/debian/modules/nginx-cache-purge --add-module=/home/leo/work/debian_package_build/nginx-1.9.10/debian/modules/nginx-dav-ext-module --add-module=/home/leo/work/debian_package_build/nginx-1.9.10/debian/modules/nginx-development-kit --add-module=/home/leo/work/debian_package_build/nginx-1.9.10/debian/modules/nginx-echo --add-module=/home/leo/work/debian_package_build/nginx-1.9.10/debian/modules/ngx-fancyindex --add-module=/home/leo/work/debian_package_build/nginx-1.9.10/debian/modules/nginx-http-push --add-module=/home/leo/work/debian_package_build/nginx-1.9.10/debian/modules/nginx-lua --add-module=/home/leo/work/debian_package_build/nginx-1.9.10/debian/modules/nginx-upload-progress --add-module=/home/leo/work/debian_package_build/nginx-1.9.10/debian/modules/nginx-upstream-fair --add-module=/home/leo/work/debian_package_build/nginx-1.9.10/debian/modules/ngx_http_substitutions_filter_module --add-module=/home/leo/work/debian_package_build/nginx-1.9.10/debian/modules/ngx_pagespeed

**Comment by oschaaf** [comment]
@auratravel I do see `--with-debug` in there.. When you would leave that out, the `DCHECK` should no longer occur.

**Comment by ldkafka** [comment]
@oschaaf 
You are right - it snucked in there... The server no longer shows the message once re-compiled ;)
