### ISSUE TITLE
Set s-maxage=10 on unoptimized IPRO resources

### ISSUE THREAD

**Issue by jeffkaufman** [apache/incubator-pagespeed-mod#1220]
When an IPRO resource hasn't been optimized yet we should serve it with a low TTL.

This is needed for integration with downstream caches.  If you have:

```
 user ---> cache ---> pagespeed
```

and if the original resource is indefinitely cacheable, then after the first request the cache will hold an indefinitely cacheable unoptimized resource.  If instead we lower the ttl, the cache will only hold the unoptimized resource for a short time, and then will check back with pagespeed to get the indefinitely cacheable optimized resource.

One thing we need to be very careful of here is that resources that PageSpeed tries and fails to optimize can't have their cache lifetimes cut short.  Nothing should be served with a low ttl for very long.

**Comment by litespeedtech** [comment]
Good.

**Comment by jeffkaufman** [comment]
When there's not an additional cache between PageSpeed and the browser this change would make things worse for users.  I still think we should do this, but after talking to @hillsp I think we should do this if at least one of:
- the site owner specifically sets a configuration directive saying they want this
- there's an X-Forwarded-For header, which indicates there was a cache
- they've set any of our downstream caching directives

**Comment by oschaaf** [comment]
Perhaps als consider `Via:` as an indication of having a cache in front?

**Comment by litespeedtech** [comment]
Those are not reliably ways. 
We want a better solution. Something in my mind:

Add a response header indicating the resource has been optimized or not, so cache server can decide whether to cache it, for how long base on that.

Send PURGE request to cache proxy to refresh cached copy when optimized version is ready (have this feature, but does not work for in-place as I heard)

Expose a cache API, let the server embedding mod_pagespeed module cache the result directly into server's cache storage and be able to serve it directly without going through mod_pagespeed. 

Just some ideas. 

Best regards,
George Wang

**Comment by jmarantz** [comment]
Another idea: keep the same TTL but send as cc:private when optimization is
in-progress.  Direct clients will cache the private resource for as long as
usual, but proxies will just skip caching it entirely.  As soon as the
optimized version is served, it would cached in the proxy.

-Josh

**Comment by oschaaf** [comment]
+1 on cc:private from me

**Comment by jeffkaufman** [comment]
Talking to @hillsp and @crowell , what we actually want here is `s-maxage`, which is a separate cache lifetime that applies only to shared (proxy) caches.  This is supported by default in varnish and most CDNs.  So we would append `s-maxage=10` to the cache control header for publicly cacheable resources that haven't been ipro-optimized yet, and the cache would check back in for optimized resources every 10s.  (And we would make this configurable, so sites could turn it off or use a longer limit if they preferred.)

**Comment by jeffkaufman** [comment]
#1287 is related: we currently don't interpret existing `Cache-Control: s-maxage=...` or `Age` headers.
