### ISSUE TITLE
Serf depends on APR 1.3

### ISSUE THREAD

**Issue by fidoboy** [apache/incubator-pagespeed-mod#1224]
Today i've updated to the latest beta (1.10.33.1-beta) and the pagespeed module fails to start, with this error message "undefined symbol: apr_sockaddr_ip_getbuf". I've rolled back to the previous stable version and it works fine again.

**Comment by morlovich** [comment]
Could you tell us what libapr version you have installed?

**Comment by fidoboy** [comment]
APR 1.2.7

**Comment by morlovich** [comment]
This seems to be used via Serf, and only in a debug method:
http://subversion.1072662.n5.nabble.com/Serf-1-2-0-has-been-released-td178523.html
Sounds like may be we should patch that out for .2 ?

**Comment by jeffkaufman** [comment]
I can do this.
