### ISSUE TITLE
beacon 204 responses with Content-Length: 0 makes Varnish log errors

### ISSUE THREAD

**Issue by oschaaf** [apache/incubator-pagespeed-mod#1225]
A report[1] from mod-pagespeed-discuss makes me suspect that Varnish doesn't like it and logs an error about our beacon responses. It looks like the Content-Length header is also violating the http specs.

https://groups.google.com/forum/#!msg/mod-pagespeed-discuss/62fOgzRtda4/u8xJnJfQDgAJ

**Comment by jeffkaufman** [comment]
Since varnish is rolling back this change [1] and the content-length is being added by apache code that's out of our (easy) control, it sounds like we can stay as we are.

[1] https://www.varnish-cache.org/trac/ticket/1826
