### ISSUE TITLE
pagespeed default config fails to load on 2.4 unless mod_access_compat is loaded

### ISSUE THREAD

**Issue by GuillaumeRossolini** [apache/incubator-pagespeed-mod#1229]
Hi,

The default config for the admin pages fails in pagespeed.conf with:

```
AH00526: Syntax error on line 345 of /usr/local/apache2/conf/pagespeed.conf
Invalid command 'Order', perhaps misspelled or defined by a module not included in the server configuration
```

This config is currently:

```
    <Location /pagespeed_admin>
        Order allow,deny
        Allow from localhost
        Allow from 127.0.0.1
        SetHandler pagespeed_admin
    </Location>
    <Location /pagespeed_global_admin>
        Order allow,deny
        Allow from localhost
        Allow from 127.0.0.1
        SetHandler pagespeed_global_admin
    </Location>
```

Which is ok for httpd-2.2.x.

For httpd-2.4.x however, it should be something along the lines of:

```
    <Location /pagespeed_admin>
        <RequireAny>
                Require ip 127.0.0.1
        </RequireAny>
        SetHandler pagespeed_admin
    </Location>
    <Location /pagespeed_global_admin>
        <RequireAny>
                Require ip 127.0.0.1
        </RequireAny>
        SetHandler pagespeed_global_admin
    </Location>
```

Regards,

**Comment by morlovich** [comment]
Hmm, this works for me, probably because I have mod_access_compat loaded. May be easier to load that rather than <IfVersion> the blocks...

**Comment by GuillaumeRossolini** [comment]
I'm not sure this would be the safest path. If the folks at httpd thought the config syntax needed changing, I'd rather follow their example than add compatibility modules which are bound to cause headaches at some point.
Maybe it would be even easier (to maintain) to have 2 separate config files or folders, one for the 2.2 branch and another for the 2.4 branch, and have the main config file "Include" the correct one? After all, there are a few if/elses in some parts of the config files already.

**Comment by jeffkaufman** [comment]
Closed by 02e8f7e866a1d8bd1ee28ee7d263770f6984d333

**Comment by GuillaumeRossolini** [comment]
I'm sorry, does it means that from now on, mod_access_compat is a required dependency?

**Comment by jeffkaufman** [comment]
People using apache 2.4 have two options:
- use mod_access_compat
- manually modify the two small blocks in PageSpeed's default config to use the new `Require` syntax instead of the old `allow/deny`.

Either one works.

**Comment by GuillaumeRossolini** [comment]
Excellent, that's just perfect. Many thanks!
