### ISSUE TITLE
Typo for "in_place_optimize_for_browser" filter in default config

### ISSUE THREAD

**Issue by GuillaumeRossolini** [apache/incubator-pagespeed-mod#1230]
Hi,

There is a small typo on this line of the default config (commented out by default):
`ModPagespeedFilters in_place_optimize_for_browser`

Apache complains:

```
2AH00526: Syntax error on line 192 of /usr/local/apache2/conf/pagespeed.conf:
Invalid command 'ModPagespeedFilters', perhaps misspelled or defined by a module not included in the server configuration
 failed!
```

The config should read instead:
`ModPagespeedEnableFilters in_place_optimize_for_browser`

Regards,

**Comment by jmaessen** [comment]
Thanks for the report!

**Comment by demlasjr** [comment]
1 year later and the bug is still there.
Ubuntu 16.04
Pagespeed version: 1.11.33.5-0
