### ISSUE TITLE
Add rel=noindex or rel=canonical on pagespeed=noscript pages

### ISSUE THREAD

**Issue by jeffkaufman** [apache/incubator-pagespeed-mod#1242]
PageSpeed automatically generates links to `?PageSpeed=noscript` versions of pages if you have any filters that require javascript.  We've had reports that this is giving duplicate content problems for people [1][2][3], so when we're serving a page with `?PageSpeed=noscript` we should add a rel=canonical pointer to the original page, or maybe a rel=noindex.

[1] https://productforums.google.com/forum/#!topic/webmasters/DcAiAmkMDqY
[2] https://groups.google.com/forum/#!topic/page-speed-service-discuss/hxxEdIIYgdQ
[3] https://groups.google.com/d/msgid/mod-pagespeed-discuss/b0f4bd00-a7e1-47c4-97ef-2d338be62326%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by jeffkaufman** [comment]
Testing this now, we do already add `rel=canonical`:

```
curl -Ss www.jefftk.com/index?PageSpeed=noscript | grep canonical
<link rel="canonical" href="http://www.jefftk.com/index"/>
```

So it looks like this is all set.

**Comment by morlovich** [comment]
I think the original reporter may have been implying that canonical may be
insufficient for some crawlers?

**Comment by jeffkaufman** [comment]
I'm not excited about adding a meta tag to the page for `rel=noindex` unless we have something stronger than someone's recollection that `rel=canonical` is insufficient.  For example, the bug could be fixed by now.

Does anyone have more details about a crawler that doesn't respect rel=canonical and does respect `rel=noindex`, ideally a time when this happened for the search results on a website they controlled?
