### ISSUE TITLE
Don't send webp to CriOS when there is no accept:image/webp

### ISSUE THREAD

**Issue by jmarantz** [apache/incubator-pagespeed-mod#1256]
The latest Chrome on iOS, based on WKWebView, cannot render webp images, but mod_pagespeed sends them.

See http://blog.chromium.org/2016/01/a-faster-more-stable-chrome-on-ios.html

I confirmed that this browser also does not send accept:image/webp.  If, in the future, webp is re-enabled in CriOS, it will likely send accept:image/webp again.

This is a workaround:

SetEnvIf User-Agent CriOS mps_disable_webp
RequestHeader set ModPagespeedFilters -convert_jpeg_to_webp env=mps_disable_webp

**Comment by jmarantz** [comment]
Note: a similar issue was found in https://github.com/pagespeed/mod_pagespeed/issues/969

**Comment by jeffkaufman** [comment]
At this point maybe we should switch to a simple "send webp if and only if we get accept:webp"?

**Comment by jmarantz** [comment]
I agree with that, but that's a larger change (assuming we still want to send webp to Android 4.0) and want to do that in a follow-up.

**Comment by huibaolin** [comment]
Android browser supports WebP since 4.0 but doesn't have WebP header. It
still has ~11% market share totally in mobile and tablet [1]. It's not
clear what is the portion of 4.0+ in this 11%, however most likely it's not
trivial.

[1]
https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=1

**Comment by jmarantz** [comment]
It turns out we need to separately disable webp-lossless and webp-animated, so the full workaround is:

SetEnvIf User-Agent CriOS mps_disable_webp
RequestHeader set ModPagespeedFilters -convert_jpeg_to_webp,-convert_to_webp_lossless,-convert_to_webp_animated env=mps_disable_webp

**Comment by jmarantz** [comment]
More detailed workaround information for nginx and apache.  None of this will be needed once we have https://github.com/pagespeed/mod_pagespeed/commit/23947d0006005c5e3aa7539d81b7819fdb454e4c in a release.

**Apache & mod_pagespeed 1.10:**
    # Temporary workaround for
    # https://github.com/pagespeed/mod_pagespeed/issues/1256
    SetEnvIf User-Agent CriOS mps_disable_webp
    RequestHeader set ModPagespeedFilters -convert_jpeg_to_webp,-convert_to_webp_lossless,-convert_to_webp_animated env=mps_disable_webp

**Nginx & ngx_pagespeed 1.10:**
  http {
    pagespeed ProcessScriptVariables on;
    server {
      set $disable_filters "";
       if ($http_user_agent ~ CriOS) {
         set $disable_filters "convert_jpeg_to_webp,convert_to_webp_lossless,convert_to_webp_animated";
       }
       pagespeed DisableFilters "$disable_filters";
    }
  }

In 1.9, there is no convert_to_webp_animated filter, and the nginx variable support is not present in PageSpeed so you have to completely disable webp until we get you a patch.

**Apache & mod_pagespeed 1.9:**
    # Temporary workaround for
    # https://github.com/pagespeed/mod_pagespeed/issues/1256
    SetEnvIf User-Agent CriOS mps_disable_webp
    RequestHeader set ModPagespeedFilters -convert_jpeg_to_webp,-convert_to_webp_lossless env=mps_disable_webp

**Nginx & ngx_pagespeed 1.9:**
  http {
    pagespeed DisableFilters "convert_jpeg_to_webp,convert_to_webp_lossless";
  }
