### ISSUE TITLE
Apache can't create /var/log/pagespeed directory

### ISSUE THREAD

**Issue by cdoublev** [apache/incubator-pagespeed-mod#1266]
Hi,

I've seen a [few](https://github.com/pagespeed/mod_pagespeed/issues/1015) [reports](https://groups.google.com/d/topic/mod-pagespeed-discuss/Wl1SLd77oLE/discussion) [on](https://groups.google.com/d/topic/mod-pagespeed-discuss/NNFElpUZO_Y/discussion) [this](https://github.com/pagespeed/mod_pagespeed/issues/345) [problem](https://github.com/pagespeed/mod_pagespeed/issues/945), and a suggested solution in [Pagespeed Module FAQ](https://developers.google.com/speed/pagespeed/module/faq#selinux_permissions), but I do not find any solution resolving it completely. 

I have Pagespeed module 1.9.32.13-0 for Apache installed on Centos 6.7, and Apache can't create /var/log/pagespeed directory. I switched ModPagespeedStatisticsLogging off momentarily.

Before that, it was the Pagespeed's cache directory that Apache couldn't create. I fixed this by creating it manually and setting type for SELinux context : 

`chcon -R system_u:object_r:httpd_sys_content_t:s0 /var/cache/mod_pagespeed/`

I tried the same solution with the log directory, both by creating it manually with SELinux permission...

`chcon -R system_u:object_r:httpd_sys_content_t:s0 /var/log/pagespeed/`

... and by leaving Apache creating it itself, but it's not working. My log entries show that Apache is unable to create it. Apache uid and gid are "apache". I also tried to set full permissions on the directory, owned by apache.

**Comment by EliezerB123** [comment]
@cdoublev Do you remember how you solved this?

**Comment by cdoublev** [comment]
Sorry, I closed this issue but didn't resolve it. I uninstalled the Pagespeed module and performed the optimizations manually. I'm sure it will always give better results than using this module. Many of its optimizations are done at runtime, that is, after the user has requested a page and before receiving the response. This increases the response time.

Anyway, I remember that this CentOS server was a "semi-self managed" VPS. By "semi-self managed", I mean a fork of the Plesk panel and scripts run via cron jobs and written by the host provider. Honestly, it was crap and there were recurring issues. I also remember using `httpd` to (re)start and stop the service, and that it was serving files in `/var/www`, which was owned by `www-data`. This means that `/var/log/pagespeed` may need to belong to one of these users/groups, depending on how the install script of this module checks which user Apache is running with.

Hope this helps a bit. Feel free to open a new issue, but you can see that it was open for 3 months without receiving any response.

**Comment by jmarantz** [comment]
For the record, PageSpeed caches optimized results server-side, to avoid
delaying responses to users. Initial requests for a website are served
unoptimized, while the optimization occurs in the background, server-side,
and saved in cache. Subsequent requests are served optimized quickly.

There is an increase in response time for HTML when running PageSpeed, due
to parsing overhead, but on modern processors with reasonable size HTML
pages, it is generally just a few milliseconds.

**Comment by cdoublev** [comment]
When it's able to write in `/var/cache/`, indeed. =)

**Comment by jmarantz** [comment]
Fair one :). The intricacies of which user mod_pagespeed is running under,
and who owns /var/cache/... are hard to keep track of, and differ based on
OS distro, as well as other modules loaded into Apache.

One option is to use ModPagespeedFileCachePath (
https://www.modpagespeed.com/doc/system) to put the files in a directory
you can control the ownership of to match the user mod_pagespeed is running
under.

**Comment by EliezerB123** [comment]
Thank you, cdoublev.

**chcon --reference /var/log/apache2 /var/log/pagespeed**

SHOULD have worked, but didn't work for me.

I used **chmod -R 777 /var/log/pagespeed** 
That allowed Pagespeed to create a file, and after learning what user Pagespeed created the file under, I **chowned** the directory to be the same user as the owner of the newly created log file, then put back **chmod 755**.

....To be fair, I did a LOT of things, but I'm pretty sure this is the sequence I did that finally solved the issue.
