### ISSUE TITLE
wrong path in log but in html ok (status=670002, resource_fetch.cc(197))

### ISSUE THREAD

**Issue by markierer** [apache/incubator-pagespeed-mod#1272]
Ubuntu 14.04 with included Apache, Pagespeed 1.9.32.13-0 (Debian package)

I use the original pagespeed.conf without any modifications.
The website is multi language so the base can be
www.domain.com/en
www.domain.com/de
www.domain.com/zh

The html output is perfect. The absolute path to the image is set correctly to www.domain.com/assets/images...
`<img src="/assets/images/icons/xlogo.gif.pagespeed.ic.7mXClZm_4Q.png" alt="xyz"/>`

But in the error.log I get warnings and errors about every 5-10 seconds.
The scheme is always one error with five warnings.

pagespeed searchs the logo.gif in domain.com/images (without assets between)
pagespeed adds assets but with two slashes after the domain // (Maybe because of en/de/zh)

```
[...] [pagespeed:error] [...] [mod_pagespeed 1.9.32.13-0 @30637] http://www.domain.com/images/icons/logo.gif (connecting to:assets):0: Error status=670002 (Name or service$
[...] [pagespeed:warn] [...] [mod_pagespeed 1.9.32.13-0 @30637] Fetch failed to start: http://www.domain.com/images/icons/logo.gif (connecting to:assets)
[...] [pagespeed:warn] [...] [mod_pagespeed 1.9.32.13-0 @30637] xlogo.gif:0: Resource based on http://www.domain.com//assets/images/icons/logo.gif but cannot access the $
[...] [pagespeed:warn] [...] [mod_pagespeed 1.9.32.13-0 @30637] [0219/194206:WARNING:resource_fetch.cc(197)] Fetch failed for resource url http://www.domain.com//assets/images$
[...] [pagespeed:warn] [...] [mod_pagespeed 1.9.32.13-0 @30637] Fetch failed for http://www.domain.com//assets/images/icons/xlogo.gif.pagespeed.ic.7mXClZm_4Q.png, status=404
[...] [pagespeed:warn] [...] [mod_pagespeed 1.9.32.13-0 @30637] http://www.domain.com//assets/images/icons/xlogo.gif.pagespeed.ic.7mXClZm_4Q.png resource_404_count: not fou$
```

But at the end the html code is ok. So pagespeed gets the correct path before or after. Why this error and warnings?
Thanks for help!

**Comment by oschaaf** [comment]
One thing I noticed is that you have all these `$` signs in the logs, which looks odd.
Is that a copy/paste error? 
The image tag you posted also does not close the src attribute with a double quote, is it really written like that in the html?

**Comment by markierer** [comment]
Those `$` are only the end of visible line signs from nano. The problem description is right after `@30637]`.

Following "solved" the problem for me:
I changed the site from http to https (redirect port 80 to 443). I added only   `ModPagespeedFetchHttps enable` to pagespeed.conf. Now all errors and warnings are gone.

**Comment by markierer** [comment]
The missing quote in the image tag above was a copy/paste error. I corrected it. (The html code is validated).

**Comment by oschaaf** [comment]
@markierer great to hear it's working. Closing this, please re-open if there still turns out to be a problem.
