### ISSUE TITLE
optimize images in srcset

### ISSUE THREAD

**Issue by jeffkaufman** [apache/incubator-pagespeed-mod#1274]
With 1.10 PageSpeed can create `srcset` attributes, but it still can't optimize existing ones.  We should identify the urls in a srcset and at least cache-extend them and do context-free optimization.  If we can additionally resize them then even better.

**Comment by Hamdani** [comment]
Great advice

**Comment by Hamdani** [comment]
Good help, good idea

**Comment by jmarantz** [comment]
this is fixed now, right?  and can also be removed from https://github.com/pagespeed/mod_pagespeed/wiki/Work-Prioritization ?

**Comment by jeffkaufman** [comment]
Is this fixed?  Did this go in while I was out?  I thought @morlovich  was still working on it?

**Comment by morlovich** [comment]
It's in
