### ISSUE TITLE
update varnish config for Varnish 4

### ISSUE THREAD

**Issue by jmarantz** [apache/incubator-pagespeed-mod#1284]
See the comments on mod-pagespeed-discuss:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mod-pagespeed-discuss/uKzbzWtQgZI/DglHAi_sAAAJ

Add double-quotes around <your-secret-key>

**Comment by jeffkaufman** [comment]
Fixed: https://developers.google.com/speed/pagespeed/module/downstream-caching
