### ISSUE TITLE
Conflicting docs for ImageMaxRewritesAtOnce=0

### ISSUE THREAD

**Issue by jeffkaufman** [apache/incubator-pagespeed-mod#1289]
Our docs [say](https://developers.google.com/speed/pagespeed/module/reference-image-optimize#ImageMaxRewritesAtOnce):

> Do not set this option to 0 to disable image optimization – that just adds computational overhead during page load. Disable recompress_images or the related filters instead.

While our default configuration (`pagespeed.conf.template`) says:

> Bound the number of images that can be rewritten at any one time; this  
> avoids overloading the CPU.  Set this to 0 to remove the bound. 

The relevant code has been rewritten recently as part of the controller work ( @hillsp ) and it looks to me like the new code follows what the default config says, not the docs:

```
CentralController* RewriteDriverFactory::CreateCentralController(
    NamedLockManager* lock_manager) {
  return new CompatibleCentralController(
      default_options()->image_max_rewrites_at_once(), statistics(),
      thread_system(), lock_manager);
}
...
WorkBoundExpensiveOperationController::WorkBoundExpensiveOperationController(
    int max_expensive_operations, Statistics* stats)
    : bound_(max_expensive_operations),
      counter_(bound_ > 0 ? stats->GetUpDownCounter(kCurrentExpensiveOperations)
                          : NULL) {}
...
bool WorkBoundExpensiveOperationController::TryToWork() {
  bool can_work = true;
  if (counter_ != NULL) {
    // We conservatively increment, then test, and decrement on failure.  This
    // guarantees that two incrementors don't both get through when we're within
    // 1 of the bound, at the cost of occasionally rejecting them both.
    // TODO(cheesy): If Statistics ever improves its atomicity gurantees, we
    // should just use the value returned by Add().
    counter_->Add(1);
    can_work = (counter_->Get() <= bound_);
    if (!can_work) {
      counter_->Add(-1);
    }
  }
  return can_work;
}
```

**Comment by jeffkaufman** [comment]
The online docs are incorrect; @huibaolin is going to fix them.

**Comment by huibaolin** [comment]
Doc has been updated. Now we're advertising "-1" for unlimited number of image rewrites. We also have added a note that "0" is equivalent to "-1".

**Comment by eldk** [comment]
Hello,

It seems that there is still something wrong : 
https://groups.google.com/forum/#!topic/mod-pagespeed-discuss/D93W3Zaycp0

Thanks,

Eric
