### ISSUE TITLE
Permissions denied

### ISSUE THREAD

**Issue by csummers4** [apache/incubator-pagespeed-mod#1295]
I have installed mod_pagespeed on a VPS with WHM using easyapache4...

wget https://github.com/pagespeed/cpanel/raw/master/EA4/ea-apache24-mod_pagespeed-latest-stable.src.rpm
rpmbuild --rebuild ea-apache24-mod_pagespeed-latest-stable.src.rpm
rpm -ivh /root/rpmbuild/RPMS/x86_64/ea-apache24-mod_pagespeed*.rpm
/etc/init.d/httpd restart

It is installed and I can view the admin panel successfully, however there are no hits...

I have PHP-FPM installed with opcache so my understanding is that the apache will use the users permissions under each homedirectory which seems to work ok as I have a fully working wordpress install.

In looking at the logs I see that there are lots and lots of permission denied errors...
e.g.

Failed to mkdir /var/mod_pagespeed/cache/!clean!lock!: Permission denied
Failed to make directory /var/mod_pagespeed/cache/rname: Permission denied

If I change the permissions to 777 then directories are created, however the user nobody is assigned to any files etc and once again mod_pagespeed cannot write/read.  This also occurs for log files etc

What should the permissions be set to?  Would really love to do some testing to see if I can improve pagespeed

**Comment by crowell** [comment]
Hi, I'm not familiar with php-fpm's permissions, so my assumptions may not be 100% correct here.

In general the cache directory should be owned by the user that apache runs as (in most cases `www-data`)

``` bash
$ ls -alh mod_pagespeed/
total 36K
drwxr-xr-x   5 www-data www-data 4.0K Apr 27 13:31 .
drwxr-xr-x  13 root     root     4.0K Jul 13  2015 ..
-rw-------   1 www-data www-data   14 Apr 26 17:13 cache.purge
-rw-------   1 www-data www-data   13 Apr 27 13:31 !clean!time!
drwxr-xr-x   4 www-data www-data 4.0K Apr 26 16:51 prop_page
drwxr-xr-x 198 www-data www-data  12K Apr 27 14:19 rname
drwxr-xr-x   9 www-data www-data 4.0K Apr 26 23:18 v3
```

When you say the user nobody is assigned to files, does that mean that apache is running as the user `nobody`? https://en.wikipedia.org/wiki/Nobody_(username)

You can check what apache is running as by doing 

``` bash
$ ps aux | grep -e "httpd\|apache"
```

the first column will have the user.
PHP-fpm shouldn't be writing to and from mod-pagespeed's cache as far as I know, so there shouldn't be a conflict there.

Also, opcache shouldn't be using the mod_pagespeed cache directory so there should also be no conflict there.

Do you have anything else "nonstandard" in your setup? mod_pagespeed should create the cache directory structure on it's own (except for the root directory, which you have to specify in the config). What is your current directory structure and httpd/pagespeed config if you can share those?

**Comment by csummers4** [comment]
Jeffrey,

I finally got it sorted...

When I looked at the apache user I got nobody

I had to change permissions for group to nobody (not owner)

PHP-FPM uses user pools so I checked the config for one of the sites and
although I had listen.owner set to <myclient> and listen.group set to
nobody there is also a user and group setting... I changed the group
setting to nobody

I created the log file and set permissions accordingly with group as nobody.

It all started working

I am not sure had the settings been set correctly whether or not the
install would have gone more seemlessly.  I plan on rebuilding my server
soon so will probably have the answer to that as well

Thanks
Chris

**Comment by ProgrammerNomad** [comment]
@csummers4 i am also facing same issues when i am uploading files from wordpress back end. so please help me.

Thanks

**Comment by csummers4** [comment]
Are you using php-fpm?  Generally wordpress is has 403 errors due to either
permissions or commonly a corrupt .htaccess file.
