### ISSUE TITLE
Memcache cache hit ratio

### ISSUE THREAD

**Issue by JoyceBabu** [apache/incubator-pagespeed-mod#1302]
While checking memcached logs, I found that the cache hit ratio is very low. I am using memcached only for pagespeed. `get_hits` / `cmd_get` is around 44%. Why is this so?

```
[root@new ~]# echo stats | nc localhost 11211
STAT pid 24611
STAT uptime 2619406
STAT time 1462777007
STAT version 1.4.25
STAT libevent 2.0.21-stable
STAT pointer_size 64
STAT rusage_user 199.047933
STAT rusage_system 496.005546
STAT curr_connections 70
STAT total_connections 17855
STAT connection_structures 94
STAT reserved_fds 20
STAT cmd_get 10529725
STAT cmd_set 5667650
STAT cmd_flush 0
STAT cmd_touch 0
STAT get_hits 4705614
STAT get_misses 5824111
STAT delete_misses 0
STAT delete_hits 0
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT touch_hits 0
STAT touch_misses 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 6744977032
STAT bytes_written 5892260375
STAT limit_maxbytes 6442450944
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT time_in_listen_disabled_us 0
STAT threads 4
STAT conn_yields 0
STAT hash_power_level 21
STAT hash_bytes 16777216
STAT hash_is_expanding 0
STAT malloc_fails 0
STAT bytes 2184994765
STAT curr_items 2484751
STAT total_items 5667650
STAT expired_unfetched 0
STAT evicted_unfetched 0
STAT evictions 0
STAT reclaimed 0
STAT crawler_reclaimed 0
STAT crawler_items_checked 0
STAT lrutail_reflocked 0
END
```

![image](https://cloud.githubusercontent.com/assets/502942/15105799/3e9d608e-15e2-11e6-8e94-d6e836af0152.png)

**Comment by oschaaf** [comment]
If you look at the "per application cache stats" under the "graphs" menu in the admin interface, you should see much better hit rates for "rewrite cached output" and "url input"

Someone else may know better then me, but I think that the overall low memcached hit percentage is just an attribute of the read/write access pattern of the property cache [1] and not something you have to worry about .

For more information about the various types of cache applications, see http://modpagespeed.jmarantz.com/2012/12/caching-in-modpagespeed.html

Closing this, but feel free to re-open if you still think there's an issue
