### ISSUE TITLE
ImageMaxRewritesAtOnce ignored (but displays correct configured value in admin interface)

### ISSUE THREAD

**Issue by oschaaf** [apache/incubator-pagespeed-mod#1305]
It looks like the configured ImageMaxRewritesAtOnce is ignored when limiting concurrent image rewrites (and expensive operations), as the default rewrite options value is used which always keeps the default value (8).
The global options from the server context do contain the configured value, but we probably can't use those as the option is process-scoped.

Reported via https://groups.google.com/forum/#!topic/mod-pagespeed-discuss/D93W3Zaycp0 (and https://github.com/pagespeed/mod_pagespeed/issues/1289#issuecomment-217722496
)

**Comment by jeffkaufman** [comment]
Fixed by https://github.com/pagespeed/mod_pagespeed/commit/4f657b92984c19ea562b2279cb2ff3a634a2a1ca
