### ISSUE TITLE
Azure CDN, by akami

### ISSUE THREAD

**Issue by aelsharawi** [apache/incubator-pagespeed-mod#1314]
Hi 

I need to set up azure CDN to work with MOD_PAGESPEED

my website admin statistics 
https:// .uk/ngx_pagespeed_statistics?config

my setting for AZURE to work:

```
######## ADD CDN

pagespeed MapRewriteDomain  .azureedge.net  .uk;

pagespeed EnableFilters rewrite_domains;

#pagespeed MapRewriteDomain https:// .uk https:// .azureedge.net;

#pagespeed ShardDomain https:// .uk https:// .azureedge.net;
#pagespeed MapProxyDomain https:// .uk/wp-content https:// .azureedge.net/wp-content;
#pagespeed Domain https:// .azureedge.net;

pagespeed DomainRewriteHyperlinks on;

#####

```

as u can see some filteres are disabled, as Im trying many configs but failed at the end to make it work

**Comment by oschaaf** [comment]
I think you should add this:

```
pagespeed MapRewriteDomain https://frcso.azureedge.net https://frcso.uk;
```

**Comment by jeffkaufman** [comment]
@oschaaf 's suggestion looks like it should have fixed this.

@aelsharawi , if you're still having problems feel free to re-open,
