### ISSUE TITLE
memcached and php 7

### ISSUE THREAD

**Issue by aelsharawi** [apache/incubator-pagespeed-mod#1315]
Hi

looks like mod_pagespeed can't work with Memcached installed into PHP 7

any idea?

also 

what about the Redis cache implementation?

**Comment by oschaaf** [comment]
On Sat, May 21, 2016 at 4:17 PM, aelsharawi notifications@github.com
wrote:

> looks like mod_pagespeed can't work with Memcached installed into PHP 7
> 
> any idea?
> 
> Could you post more details about what happens?
> 
> also
> 
> what about the Redis cache implementation?
> 
> Redis support is being tracked at
> https://github.com/pagespeed/ngx_pagespeed/issues/777

Otto

**Comment by jeffkaufman** [comment]
Closing this, since it's a month old.

@aelsharawi Feel free to reopen if you're still having problems with memcached and php7.
