### ISSUE TITLE
Forbidden on a specific CSS&JS

### ISSUE THREAD

**Issue by szepeviktor** [apache/incubator-pagespeed-mod#1317]
Please advise!

HTTP/403: http://www.vereskriszta.com/wordpress/wp-content/plugins/akismet/_inc/akismet.js,qver=3.1.5.pagespeed.jm.w_OH37C_JQ.js

original url: http://www.vereskriszta.com/wordpress/wp-content/plugins/akismet/_inc/akismet.js?ver=3.1.5

mod-pagespeed-stable     1.11.33.2-r0

apache2-mpm-itk 2.4.10-10+deb8u4

HTTP/403:  http://www.vereskriszta.com/wordpress/wp-content/plugins/akismet/_inc/A.akismet.css,qver=3.1.5.pagespeed.cf.oe-72ZrVAU.css

**Comment by szepeviktor** [comment]
All other files are OK.

```
ModPagespeed on
ModPagespeedFileCachePath /home/${SITE_USER}/website/pagespeed
ModPagespeedRewriteDeadlinePerFlushMs 100
#ModPagespeedMapRewriteDomain s.${SITE_DOMAIN} ${SITE_DOMAIN}

#ModPagespeedEnableFilters rewrite_javascript
ModPagespeedDisableFilters rewrite_images
#ModPagespeedCssInlineMaxBytes 10
```

**Comment by szepeviktor** [comment]
URL ends: `akismet.js,qver=3.1.5.pagespeed.jm.w_OH37C_JQ.js`
Existing cache file: `akismet.js,2Cqver=3.1.5.pagespeed.jm.w_OH37C_JQ.js,`

**Comment by morlovich** [comment]
That's pretty weird, especially since the version under original URL
clearly got in-place optimized. Anything relevant-looking in the log?

**Comment by szepeviktor** [comment]
nope

> AH01630: client denied by                                     server configuration: uri /wordpress/wp-content/plugins/akismet/_inc/akismet.js,qver=3.1.5.pagespeed.jm.w_OH37C_JQ.js

**Comment by morlovich** [comment]
That's actually somewhat helpful: that'a Apache's access control, not something at our level..

**Comment by szepeviktor** [comment]
`/wordpress/wp-content/plugins/akismet/_inc/akismet.js,qver=3.1.5.pagespeed.jm.w_OH37C_JQ.js` this URL was generated by Pagespeed. I actually do not understand it.

**Comment by morlovich** [comment]
Yes, we generated the URL, but some authorization settings in the Apache configuration is preventing it from being accessible.

**Comment by szepeviktor** [comment]
trace8 is the highest loglevel, all I've got is

```
[Mon May 23 17:37:45.378945 2016] [authz_core:debug] [pid 19066] mod_authz_core.c(809): [client 88.151.99.143:33119] AH01626: authorization result of Require all denied: denied

[Mon May 23 17:37:45.378992 2016] [authz_core:debug] [pid 19066] mod_authz_core.c(809): [client 88.151.99.143:33119] AH01626: authorization result of <RequireAny>: denied

[Mon May 23 17:37:45.378999 2016] [authz_core:error] [pid 19066] [client 88.151.99.143:33119] AH01630: client denied by server configuration: uri /wordpress/wp-content/plugins/akismet/_inc/akismet.js,qver=3.1.5.pagespeed.jm.w_OH37C_JQ.js
```

Then I've systematically commented out - On a live system! - all `Require all denied`-s and still it is http/403.

**Comment by szepeviktor** [comment]
The thing is, only for this file, all other pagespeed-ed files are OK.

**Comment by szepeviktor** [comment]
Oh! I am very sorry. Akismet plugin contains some Apache directives.

``` apache
# Only allow direct access to specific Web-available files.

# Apache 2.2
<IfModule !mod_authz_core.c>
    Order Deny,Allow
    Deny from all
</IfModule>

# Apache 2.4
<IfModule mod_authz_core.c>
    Require all denied
</IfModule>

# Akismet CSS and JS
<FilesMatch "^(form|akismet)\.(css|js)$">
    <IfModule !mod_authz_core.c>
        Allow from all
    </IfModule>

    <IfModule mod_authz_core.c>
        Require all granted
    </IfModule>
</FilesMatch>

# Akismet images
<FilesMatch "^(.+)\.(png|gif)$">
    <IfModule !mod_authz_core.c>
        Allow from all
    </IfModule>

    <IfModule mod_authz_core.c>
        Require all granted
    </IfModule>
</FilesMatch>
```

Workaround: `ModPagespeedDisallow "*/plugins/akismet/*"`
