### ISSUE TITLE
in combine_javascript doc, it says CSS where it should say JavaScript

### ISSUE THREAD

**Issue by jmarantz** [apache/incubator-pagespeed-mod#1318]
Bruno Negrão Guimarães Zica via googlegroups.com 
4:20 PM (20 minutes ago)
Reply
to mod-pagespeed-. 
I noticed a wrong paragraph in the "Combine Javascript", Limitations section. It says "CSS files" instead of Javascript files.

This filter generates URLs that are essentially the concatenation of the URLs of all the CSS files being combined. The maximum URL size is generally limited to about 2k characters due to IE: Seehttp://support.microsoft.com/kb/208427/EN-US. Apache servers by default impose a further limitation of about 250 characters per URL segment (text between slashes). PageSpeed circumvents this limitation when it runs under Apache, but if you employ proxy servers in your path you may need to re-impose it by overriding the setting here. The default setting is 1024.

This paragraph is a copy and paste from Combine Css, Limitations section.

**Comment by crowell** [comment]
doc fixed.
