### ISSUE TITLE
rewrite_style_attributes_with_url docs do not mention need for rewrite_css, rewrite_images

### ISSUE THREAD

**Issue by jmaessen** [apache/incubator-pagespeed-mod#1319]
Originally prompted by a user report of trouble with this filter, I ran http://www.modpagespeed.com/rewrite_style_attributes.html?ModPagespeed=on&ModPagespeedFilters=rewrite_style_attributes_with_url,debug

And I don't see the urls in the inline CSS being rewritten no matter how much I mash reload.

**Comment by jmarantz** [comment]
The example needs to add rewrite_css,rewrite_images into the filter-list in the query-param:

```
curl http://www.modpagespeed.com/rewrite_style_attributes.html?PageSpeedFilters=rewrite_css,rewrite_images,rewrite_style_attributes_with_url | grep background-image
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   501  100   501    0     0   2370      0 --:--:-- --:--:-- --:--:--  2363
    <div style="background-image:url(images/xBikeCrashIcn.png.pagespeed.ic.-f3rxqdUg6.jpg);height:100px"/>
```

**Comment by jmaessen** [comment]
Revising to indicate that the docs (https://developers.google.com/speed/pagespeed/module/filter-rewrite-style-attributes#configuration) and the example link don't mention the need for both of these filters.

**Comment by jmaessen** [comment]
Revised docs have been pushed.
