### ISSUE TITLE
cleaning large caches can take an extremely long time.

### ISSUE THREAD

**Issue by crowell** [apache/incubator-pagespeed-mod#1330]
if walking the filesystem takes ~1 hour, it's possible that the cache won't ever finish being cleaned.

cc: @hillsp

**Comment by jeffkaufman** [comment]
We don't stop cache cleaning runs after an hour, so the cache should continue being cleaned.

We do currently do bad things in this case, which https://github.com/pagespeed/mod_pagespeed/issues/1337 tracks and I have a CL for under review.
