### ISSUE TITLE
Cache cleaner locking is sub-optimal

### ISSUE THREAD

**Issue by hillsp** [apache/incubator-pagespeed-mod#1331]
If FileCache::CleanWithLocking takes longer than 1 hour, TryLockWithTimeout breaks the lock and starts a new thread regardless. In an IO starved system with a large cache, this would be pretty toxic, though in practice a cache clean is probably completed within an hour.

There is a case for some alternate method of determining if the cache cleaning is running. Moving to the central controller is one solution. Periodically touching the lock file while the cache is being cleaned is another.

(Even in the current code, it seems like maybe the lock timeout should be influenced by clean_interval_ms and/or the time that the last clean took.)

**Comment by jeffkaufman** [comment]
I accidentally re-filed this as #1337.

There's been more discussion there, so I'm closing this one.
