### ISSUE TITLE
Recognize dc.js as a synonym for ga.js

### ISSUE THREAD

**Issue by jeffkaufman** [apache/incubator-pagespeed-mod#1338]
`stats.g.doubleclick.net/dc.js` is a synonym for `google-analytics.com/ga.js`, for `insert_ga` purposes.  We should recognize scripts that use it, and be willing to make substitutions on them.  Doc: https://support.google.com/analytics/answer/2444872

(Reported on the mailing list: https://groups.google.com/forum/#!topic/ngx-pagespeed-discuss/GM8rYlv82cQ)

**Comment by jeffkaufman** [comment]
Patch is out for review.

**Comment by centminmod** [comment]
thanks @jeffkaufman didn't know dc.js was a synonym !

much appreciated :+1:

**Comment by jeffkaufman** [comment]
> didn't know dc.js was a synonym !

Well, it's not actually a synonym, but it is from ngx_pagespeed's
perspective?  My understanding from reading docs (this morning) is
that Double Click's `dc,js` is an extension of `ga.js` that adds a few
more features.

**Comment by centminmod** [comment]
Ah i see :)
