### ISSUE TITLE
Opera Mini user-agent filter looks incorrect

### ISSUE THREAD

**Issue by JoeUX** [apache/incubator-pagespeed-mod#1342]
In the user-agent matcher: https://github.com/pagespeed/mod_pagespeed/blob/master/pagespeed/kernel/http/user_agent_matcher.cc

I see various Opera Mini filters applied as `"*Opera Mini*"`

Problem: The Opera Mini user-agent does not include the string "Opera Mini" as far as I can tell. This is the Opera Mini UA string on my phone:

> Mozilla/5.0 (Linux; U; Android 6.0.1; SM-G930V Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.81 Mobile Safari/537.36 OPR/17.0.2211.105178

Highlights:
- The "Version/..." string is borrowed from iOS Safari norms, and does not appear on any other browser UA on my phone (Chrome, Firefox, Samsung, Opera standard)
- The solitary U in the parenthetical system info section appears to be unique to Opera Mini. It does not appear in the standard Opera browser for Android UA.

For comparison, here's the standard Opera for Android UA:

> Mozilla/5.0 (Linux; Android 6.0.1; SM-G930V Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Mobile Safari/537.36 OPR/37.0.2192.105088

If "Opera Mini" is generally not part of the Opera Mini UA string, then all the filters applied in the user agent matcher for Opera Mini are presumably broken.

**Comment by crowell** [comment]
looks like they've changed the UA since version 9 http://www.useragentstring.com/pages/Opera%20Mini/ Thanks for the update. Opera mini seems to be built on webkit now and may actually support the features that haven't been delivered to opera mini uas in the past. I'll check that out today.

**Comment by crowell** [comment]
Opera mini does seem to send the "Opera Mini" string in the UA when used in compression mode. And the other UA string is used when Opera isn't in compression mode, so this looks to work as intended.

![opera](http://i.imgur.com/dJsyWDI.png)

**Comment by JoeUX** [comment]
Interesting. It looks like it's called Extreme Mode. Some sort of compression mode is on by default, what they just call Data Savings, or sometimes Turbo. That's fascinating that it flips the user-agent so dramatically. It's also the first time I've seen a browser UA not start with Mozilla/5.0, which implies that maybe we don't need that string anymore...
