### ISSUE TITLE
allow people to turn off cache cleaning

### ISSUE THREAD

**Issue by jeffkaufman** [apache/incubator-pagespeed-mod#1343]
Right now you can turn off the "delete things" aspect of cache cleaning, but not the "check the whole cache to see what should be cleaned" aspect.

This should probably look like:

`ModPagespeedFileCacheCleanIntervalMs -1`

**Comment by morlovich** [comment]
Note that the interval is an int64, so it should be possible to just put in a sufficiently giant number as a workaround (3000000000000 would likely do --- it's around 95 years).

**Comment by jeffkaufman** [comment]
Yes, a giant number is what I suggested on the thread, but we should support -1 and doc it.

(I should also reread the code and make sure you can turn off all of our "uh oh, something's funny, better clean the cache" checks.)
