### ISSUE TITLE
Non-Chrome browsers aren't being optimized much

### ISSUE THREAD

**Issue by JoeUX** [apache/incubator-pagespeed-mod#1344]
Looking at the user_agent_matcher.cc code some more, I see lots of optimizations for Chrome, but the corresponding optimizations for other browsers are missing:
- There's a lot of webp logic, but apparently no JPEG-XR for IE 10, 11, and MS Edge, which are a significant chunk of users.
- There's logic for animated webp, but nothing for animated PNG, which is supported by both Firefox and Safari, including iOS, which is another big chunk of users. APNG is a nice win over GIF in size.
- Safari isn't getting DNS prefetch. The comment explaining why says "We haven't added Safari here since it supports dns prefetch only from 5.0.1 which causes the wildcard to be a bit messy."

Well, then I would just set the wildcard at version 6 and above, which is the vast majority of Safari users at this point. (Note that I'm not sure Safari on iOS supports DNS prefetch. CanIUse doesn't seem to know. Maybe it's only Mac Safari, which is still important.)

Is this happening by design? I don't know if there's a doc or charter kind of thing that explains that PageSpeed is focused on optimizing Chrome only. I was under the impression that it was meant for general website optimization, which would necessarily be neutral to users' browsers. What's the official word here?

**Comment by jeffkaufman** [comment]
Overall, our goal is to make pages as fast as possible for all users, not just Chrome users.  Nearly all our development work has gone into optimizations that are fully cross browser, which is what we need to do to make pages fast everywhere.  So "non-Chrome browsers aren't being optimized much" seems pretty unfair to me.

As you point out, though, we do have some places where we include optimizations for Blink-derived browsers (Chrome/Opera) but not others:
- WebP support is ~50%, while JPEG-XR support is ~5%.  I do still think adding support for JPEG-XR would be valuable, though.  Opened a bug: https://github.com/pagespeed/mod_pagespeed/issues/1346
- I had thought that APNG wasn't typically any smaller than GIF, just more full-featured, but it does look like it's actually smaller.  This is more broadly supported than JPEG-XR, but applies to fewer images.  Opened a bug: https://github.com/pagespeed/mod_pagespeed/issues/1347
- For Safari and `dns-prefetch` the code you're referring to looks like [user_agent_matcher.cc:218](https://github.com/pagespeed/mod_pagespeed/blob/master/pagespeed/kernel/http/user_agent_matcher.cc#L218).  Filed a bug, and I'll fix that now. https://github.com/pagespeed/mod_pagespeed/issues/1348

**Comment by jeffkaufman** [comment]
#1348 is fixed; #1346 and #1347 are on the [work prioritization sheet](https://github.com/pagespeed/mod_pagespeed/wiki/Work-Prioritization).  Feel free to reopen if you have followups or you see anything else we should be doing for other browsers.

**Comment by JoeUX** [comment]
Hi Jeff – Thanks for the thorough and quick responses. A couple of things:
- In your point about 50% and 5% support, I assume you mean browser share? IE10+ and Edge comprise a lot more than 5% of browser share, so are referring to a specific scenario or subset? The upper bound is probably going to be [Net Market Share](https://www.netmarketshare.com/browser-market-share.aspx), which yields 26.25% for desktop. [StatCounter for April-June](http://gs.statcounter.com/#browser-na-monthly-201604-201606-bar) gives around 20%, but that probably includes IE8.
  
  Note that JPEG-XR support may increase even as IE share decreases, since the latter will plausibly be driven by IE<10 attrition more than by IE≥10 and Edge losses (I doubt Edge will lose share at all).
- Yes, APNG is much more efficient than GIF. It's easy to beat GIF, but APNG has gotten little attention because for the longest time it was Firefox-only, like MathML. Then Safari quietly added support, and so I think it's worth doing now.
- Speaking of which, there is also JPEG-2000 on Safari Mac and iOS. This might be a bigger share than JPEG-XR. However, something is sketchy about it. Try Googling `JPEG-2000 site:apple.com` and you'll come up dry (the two non-discussion hits are trivial). Apple doesn't talk about supporting J2K at all. Undocumented features can be taken away at any time, so I don't know... it doesn't seem worth the hassle. And generating J2K images will be tough given the tooling landscape.

For JPEG-XR encoding, you might want to talk to Cloudinary to see if they'd be willing to share their [batch encoding solution](http://cloudinary.com/blog/jpeg_xr_conversion_with_auto_browser_detection_optimize_images_for_ie_users). Or imgix. These guys might have built something pretty sweet. Or Microsoft Research.

**Comment by jeffkaufman** [comment]
> In your point about 50% and 5% support, I assume you mean browser share? IE10+ and Edge comprise a lot more than 5% of browser share, so are referring to a specific scenario or subset? The upper bound is probably going to be Net Market Share, which yields 26.25% for desktop. StatCounter for April-June gives around 20%, but that probably includes IE8.

I mean browser share, across all devices.  It looks like your two links include IE<10 and exclude mobile users.

(I still think it's worth doing regardless, but if it's 20% of users I think it's higher priority than if it's 5%.)
