### ISSUE TITLE
Installed and enabled mod_pagespeed but I am not getting 'Pagespeed' on my website header 

### ISSUE THREAD

**Issue by shabnambanu1983** [apache/incubator-pagespeed-mod#1345]
Hi,

I am a software developer and an Entrepreneur . I am using a linux centos6.8 VPS from  godaddy . I installed and enabled mod_pagespeed for the apache server I am using but Its not yet enabled . I tried curl -I http://www.femiza.com | less to check the header output but it didn't return anything related to 'PageSpeed' . Please help me resolve this issue . Its really really important for me and is holding back my product release .

Thanks,
Shabnam
![pagespeed](https://cloud.githubusercontent.com/assets/20386780/16716043/954a5cae-470e-11e6-93b7-a99c6dc05530.png)

**Comment by yeputons** [comment]
@shabnambanu1234 just in case: have you restarted your Apache server after making changes to configuration?
If yes, do logs say anything about pagespeed being enabled/disabled/ignored? What version of Pagespeed do you use?

**Comment by shabnambanu1983** [comment]
@yeputons : Thanks for the prompt response . Yes I have restarted my Apache server after installing and making changes in configuration . In fact /etc/httpd/conf.d/pagespeed.conf has pagespeed on by default . No logs don't say anything . I am not sure how can I tell you the pagespeed version as the header of the site doesn't say anything . I installed from this link https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_x86_64.rpm  .

**Comment by yeputons** [comment]
@shabnambanu1234  would you mind trying `curl -D- http://localhost | less` on your VPS locally and checking for pagespeed headers so that we know noone is stripping headers away? Say, some DDoS protection systems may do that.

If it's still not here, please run `httpd -M | less` and check if mod_pagespeed is loaded by the server at all.

**Comment by shabnambanu1983** [comment]
@yeputons  : I tried both the commands . Details are given below . Yes mod_pagespeed is not getting loaded by the server . I am not sure what I am missing :( .

## curl -D- http://localhost | less  result

HTTP/1.1 200 OK
Date: Sun, 10 Jul 2016 21:27:57 GMT
Server: Apache
Last-Modified: Tue, 28 Jun 2016 08:08:34 GMT
Accept-Ranges: bytes
Content-Length: 111
Content-Type: text/html

<html><head><META HTTP-EQUIV="refresh" CONTENT="0;URL=/cgi-sys/defaultwebpage.cgi"></head><body></body></html>

## httpd -M | less output

Loaded Modules:
 core_module (static)
 authn_file_module (static)
 authn_core_module (static)
 authz_host_module (static)
 authz_groupfile_module (static)
 authz_user_module (static)
 authz_core_module (static)
 access_compat_module (static)
 auth_basic_module (static)
 socache_shmcb_module (static)
 socache_dbm_module (static)
 so_module (static)
 include_module (static)
 filter_module (static)
 deflate_module (static)
 http_module (static)
 mime_module (static)
 log_config_module (static)
 logio_module (static)
 env_module (static)
 expires_module (static)
 headers_module (static)
 unique_id_module (static)
 setenvif_module (static)
 version_module (static)
 proxy_module (static)
 proxy_connect_module (static)
 proxy_http_module (static)
 slotmem_shm_module (static)
 ssl_module (static)
 mpm_prefork_module (static)
 unixd_module (static)
 status_module (static)
 autoindex_module (static)
 asis_module (static)
 suexec_module (static)
 cgi_module (static)
 negotiation_module (static)
 dir_module (static)
 actions_module (static)
 userdir_module (static)
 alias_module (static)
 rewrite_module (static)
 bwlimited_module (shared)
 suphp_module (shared)
 security2_module (shared)

Thanks,
Shabnam

**Comment by shabnambanu1983** [comment]
@yeputons I am using redis cache and also mod_deflate module . Is there any chance that these can interfere with mod_pagespeed . If yes how ? What do I need to do .

**Comment by yeputons** [comment]
@shabnambanu1234 mod_deflate is automatically enabled by mod_pagespeed anyway, so I doubt it's a problem. If you use Redis as a cache on framework-level (e.g. it's configured somewhere in Magento), then it also should not be a problem.

What version of Apache do you use? What commands have you used for pagespeed installation?
Is there anything pagespeed-related in directories `/etc/apache2/mods-available` and `/etc/apache2/mods-enabled`?

**Comment by shabnambanu1983** [comment]
@yeputons  : 

Yes I am using redis as a cache on framework-level .I am using apache version: Apache/2.4.18 (Unix) . I used the steps mentioned here http://sharadchhetri.com/2014/07/30/install-pagespeed-module-mod_pagespeed-on-apache-web-server-centos-rhel/ to install pagespeed. I don't have the directory /etc/apache2 on my machine . But I have checked and I have the following files and directories as mentioned in the link .
Two conf file is also created inside /etc/httpd/conf.d
1. /etc/httpd/conf.d/pagespeed.conf (Main configuration file)
2. /etc/httpd/conf.d/pagespeed_libraries.conf

Two pagespeed modules liberary are installed
1./etc/httpd/modules/mod_pagespeed_ap24.so
2. /etc/httpd/modules/mod_pagespeed.so

One file created in /etc/cron.daily/
1. /etc/cron.daily/mod-pagespeed

Thanks,
Shabnam

**Comment by aaniya** [comment]
i think if you are using apache2, u must hv /etc/apache2
do u hv /usr/local/apache2 ? 
in case u hv mispleaced those folders.. u can download them or reinstall apache 2 depending on ur centos version rightly.
be sure to purge mod_pagespeed & all other dependencies before uninstalling.

**Comment by shabnambanu1983** [comment]
I have solved this issue . I am writing here the way I solved it on godaddy centos VPS . Instead of directly installing it I installed it through the WHM of the VPS . Initially 'mod_pagespeed'  was not available in the install list but after following the commands listed here http://stackoverflow.com/questions/24366649/install-mod-page-speed-module-on-whm-centos I could install and enable it successfully. I hope it helps someone facing similar issue .

**Comment by yeputons** [comment]
@shabnambanu1234 Thank you for sharing the solution!
