### ISSUE TITLE
rewrite_domains doesn't apply to static assets

### ISSUE THREAD

**Issue by oschaaf** [apache/incubator-pagespeed-mod#1350]
Scripts written into the html by PSOL for (for example) defer_javascript and lazyload_images cannot be rewritten to be served via a CDN.

From https://groups.google.com/d/msgid/mod-pagespeed-discuss/fd26cdb8-f4bc-4629-96cd-dd604b5b1649%40googlegroups.com:
- There's the StaticAssetPrefix [1] option, which takes an absolute path. 
  I did attempt to specify a full domain in this option instead of just that. The option allows doing so and it will be used in the html output correctly, but it looks like mapping the resulting incoming requests fails.
- The MapRewriteDomain option does not apply to pagespeed's static assets.

**Comment by jeffkaufman** [comment]
I think `MapRewriteDomain` should be applying to the static assets.  I'll figure out why not.

**Comment by jeffkaufman** [comment]
Reproduced:

```
<VirtualHost localhost:@@APACHE_SECONDARY_PORT@@>
  ServerName map-static-domain.example.com
  DocumentRoot "@@APACHE_DOC_ROOT@@"
  ModPagespeedFileCachePath "@@MOD_PAGESPEED_CACHE@@"

  ModPagespeedMapRewriteDomain http://static-cdn.example.com \
                               http://map-static-domain.example.com

  ModPagespeedRewriteLevel PassThrough
  ModPagespeedEnableFilters defer_javascript
</VirtualHost>

http_proxy=localhost:8083 curl -sS -D- -H 'User-Agent: Chrome/100' \
  map-static-domain.example.com/mod_pagespeed_example/rewrite_javascript.html \
  | grep /mod_pagespeed_static/
...<script type="text/javascript" src="/mod_pagespeed_static/js_defer.tRzI7EHUpg.js"></script></body>
```

That should have read `http://static-cdn.example.com/mod_pagespeed_static/js_defer.tRzI7EHUpg.js`

**Comment by jeffkaufman** [comment]
I'm not sure whether you should need to have to turn on `rewrite_domains` for this to work.

**Comment by jeffkaufman** [comment]
I see two ways for this to work:
- `StaticAssetManager::GetAssetUrl` could call `DomainRewriteFilter::Rewrite` like the css tag scanner does.  This is awkward because currently `GetAssetUrl` doesn't know what the base is.
- `DomainRewriteFilter::Rewrite` could allow rewriting `.pagespeed.` resources that are static assets.  I think this would be a pretty tidy change, but it would require people to turn on `rewrite_domains` if they want this behavior, which is a little strange.

**Comment by morlovich** [comment]
There is also PageSpeedStaticAssetCDN, but that might require one to
actually distribute the files, which is probably impractical for
normal users.
(It was added for mobilizer experiments...)

See TEST_F(SystemRewriteOptionsTest, StaticAssetCdn)  for the closest
it has to documentation

**Comment by jeffkaufman** [comment]
Actually, I think all we need to do is move rewrite domains to run after everything that inserts static assets

**Comment by jeffkaufman** [comment]
change is out for review
