### ISSUE TITLE
<link rel="preload"> resources are not optimized

### ISSUE THREAD

**Issue by JoyceBabu** [apache/incubator-pagespeed-mod#1353]
MPS is not optimizing files mentioned in `<link rel="preload">`. I am trying to use the `<link rel="preload" as="style">` for preloading my main CSS file asynchronously, but the CSS file is not optimized/rewritten.

**Comment by jeffkaufman** [comment]
This isn't currently possible, and with the way PageSpeed is designed it's not practical.  Instead, what we're planning to do is to strip out existing `rel=preload` tags and insert new ones for the resources we determine it's worth telling the preload scanner about.
