### ISSUE TITLE
Attempt to destroy unknown SHM segment

### ISSUE THREAD

**Issue by JanGalek** [apache/incubator-pagespeed-mod#1365]
Clear install module,

OS: Ubuntu 14.04
Apache: 2.4.7
PHP: 7.0

I still get (/var/log/apache2/error.log)

```
[Tue Jul 26 14:33:10.099304 2016] [pagespeed:error] [pid 26576] [mod_pagespeed 1.11.33.2-0 @26576] Attempt to destroy unknown SHM segment [1]/var/cache/mod_pagespeed/ flush /named_locks.
[Tue Jul 26 14:33:10.102425 2016] [pagespeed:error] [pid 26576] [mod_pagespeed 1.11.33.2-0 @26576] Attempt to destroy unknown SHM segment [1]pagespeed_default_shm/metadata_cache.
[Tue Jul 26 14:33:10.103217 2016] [pagespeed:error] [pid 26576] [mod_pagespeed 1.11.33.2-0 @26576] Attempt to destroy unknown SHM segment [1]globalstatistics.
[Tue Jul 26 14:33:10.103567 2016] [pagespeed:error] [pid 26576] [mod_pagespeed  @26576] [0726/143310:ERROR:google_message_handler.cc(59)] Attempt to destroy unknown SHM segment [1]SharedCircularBuffer.:0.

```

**Comment by jmarantz** [comment]
I agree this is annoying, but it's also benign.  We should figure out
what's going on and remove the warning.

**Comment by jmarantz** [comment]
I think it's clear that this warning happens enough in practice that we are just learning to ignore it, so we might as well just not print it.  Maks?

**Comment by morlovich** [comment]
I think I might have fixed this last week or two weeks ago, actually.

**Comment by JanGalek** [comment]
Warrning ? I see error [pagespeed:**error**]

**Comment by jeffkaufman** [comment]
> I think I might have fixed this last week or two weeks ago, actually.

6ff9ecd394d26ed253dcd738f25d0641249aa1e7

**Comment by JanGalek** [comment]
but not merged - https://github.com/pagespeed/mod_pagespeed/blob/master/pagespeed/apache/mod_instaweb.cc#L307
