### ISSUE TITLE
dedup_inline_images filter is broken

### ISSUE THREAD

**Issue by jmarantz** [apache/incubator-pagespeed-mod#1369]
A user reports that it's broken on his site here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mod-pagespeed-discuss/ZlpKH_1O3A4/A57MfpGrAAAJ

And I _think_ it's also broken in the same way on modpagespeed.com here: http://modpagespeed.com/dedup_inlined_images.html?ModPagespeed=on&ModPagespeedFilters=inline_images,dedup_inlined_images

**Comment by jeffkaufman** [comment]
From a scan of the email I thought at first this might be https://github.com/pagespeed/mod_pagespeed/issues/1002, but this actually looks like the filter is seriously broken now?

**Comment by morlovich** [comment]
Seems easier to reproduce with local debug install than mps.com due to lack
of critical image stuff getting involved. Taking a look.

**Comment by morlovich** [comment]
Well, this is obviously broken (irrelevant stuff removed) --- why are we getting all the duplicated (including the one that has the data) the same ID?:
<img id="pagespeed_img_98KheFixjv"/><script id="pagespeed_script_1" data-pagespeed-no-defer>
pagespeed.dedupInlinedImages.inlineImg('pagespeed_img_98KheFixjv','pagespeed_img_98KheFixjv','pagespeed_script_1');
</script><br/>
    <img id="pagespeed_img_98KheFixjv"/><script type="text/javascript" id="pagespeed_script_2" data-pagespeed-no-defer>
pagespeed.dedupInlinedImages.inlineImg('pagespeed_img_98KheFixjv','pagespeed_img_98KheFixjv','pagespeed_script_2');

**Comment by morlovich** [comment]
This might be enough (but I haven't run any actual tests):
--- net/instaweb/rewriter/dedup_inlined_images_filter.cc      2015-08-28 14:25:48.000000000 -0400
+++ net/instaweb/rewriter/dedup_inlined_images_filter.cc       2016-08-04 11:29:01.000000000 -0400
@@ -117,7 +117,8 @@
     GoogleString element_id;
     const char\* id = element->AttributeValue(HtmlName::kId);
     if (id == NULL || id[0] == '\0') {
-      element_id = StrCat("pagespeed_img_", hash);
-      element_id = StrCat("pagespeed_img_", hash,
-                          IntegerToString(++snippet_id_));
     driver()->AddAttribute(element, HtmlName::kId, element_id);
   } else {
     element_id = id;

**Comment by morlovich** [comment]
Let's try this again:

```
--- net/instaweb/rewriter/dedup_inlined_images_filter.cc      2015-08-28 14:25:48.000000000 -0400
+++ net/instaweb/rewriter/dedup_inlined_images_filter.cc       2016-08-04 11:29:01.000000000 -0400
@@ -117,7 +117,8 @@
     GoogleString element_id;
     const char* id = element->AttributeValue(HtmlName::kId);
     if (id == NULL || id[0] == '\0') {
-      element_id = StrCat("pagespeed_img_", hash);
+      element_id = StrCat("pagespeed_img_", hash,
+                          IntegerToString(++snippet_id_));
       driver()->AddAttribute(element, HtmlName::kId, element_id);
     } else {
       element_id = id;
```

**Comment by jeffkaufman** [comment]
Any idea how this could have gotten broken?  Did it just never work?

**Comment by jmarantz** [comment]
I haven't dug in deeply enough to be sure but I assume it worked at one
point.  One possible explanation is that maybe browsers were sloppier then
about allowing multiple elements with the same ID.

**Comment by morlovich** [comment]
That would be very weird, since it wass basically doing
document.getElementById(to_id).src = document.getElementById(from_id).src, where to_id was equal to from_id.

**Comment by jeffkaufman** [comment]
This went out in 1.11.33.3

**Comment by jeffkaufman** [comment]
confirmed fixed
