### ISSUE TITLE
Option to support CloudFront-Forwarded-Proto

### ISSUE THREAD

**Issue by marstonstudio** [apache/incubator-pagespeed-mod#1370]
Add a new option or extend the exsiting configuration option ModPagespeedRespectXForwardedProto to also cover the header 'CloudFront-Forwarded-Proto'. This header serves the same function as the X-Forwarded-Proto header.

Documentation on this option
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html

**Comment by oschaaf** [comment]
If you have the `headers-more` module [1] available you could transform `CloudFront-Forwarded-Proto` to `X-Forwarded-Proto`:

```
        more_set_input_headers 'X-Forwarded-Proto: $http_cloudfront_forwarded_proto';
        pagespeed RespectXForwardedProto on;   
```

Would that work for you?

[1] https://github.com/openresty/headers-more-nginx-module#name

**Comment by oschaaf** [comment]
Oh, wait, I see I made a mistake. The configuration I posted was for nginx and is not going to work for Apache. Sorry! 

Perhaps `mod_headers` is able to perform the required request-header manipulation, but I'm not sure.

**Comment by marstonstudio** [comment]
I'll take a look, thanks for the suggestion.

**Comment by marstonstudio** [comment]
mod_header worked, thank you for the suggestion @oschaaf. 

My settings:

```
SetEnvIf CloudFront-Forwarded-Proto https HTTPS_PROTO
RequestHeader set X-Forwarded-Proto "https" env=HTTPS_PROTO
```
