### ISSUE TITLE
[ngx_pagespeed 1.11.33.2-0] AprMemCache::Get error: Connection refused (111)

### ISSUE THREAD

**Issue by cerriex** [apache/incubator-pagespeed-mod#1372]
Hello,

Using a 3 server setup of Nginx/PHP-FPM and PageSpeed I am unable to get PHP to save sessions to memcached (distributed) on any of the cluster servers with the following error in (/var/log/nginx/error_log):

[ngx_pagespeed 1.11.33.2-0] AprMemCache::Get error: Connection refused (111)
[ngx_pagespeed 1.11.33.2-0] AprMemCache::MultiGet error: Internal error
[ngx_pagespeed 1.11.33.2-0] AprMemCache::Put error: Could not find specified socket in poll list. 

These versions that are installed: 

rpm -qa | grep memcache
memcached-1.4.15-9.el7.x86_64
libmemcached-1.0.16-5.el7.x86_64
php56-php-pecl-memcache-3.0.8-5.el7.remi.x86_64

I am able to connect to memcached on any server from any server via telnet. Just not PHP.

Here is the memcached PID where x.x.x.x is the public IP of any of the 3 cluster servers.

/usr/bin/memcached -u memcached -p 11211 -m 64 -c 1024 -l x.x.x.x

here is the /etc/nginx/conf.d/pagespeed.conf
# enable Memcached storage for cache

pagespeed MemcachedThreads 1;
pagespeed MemcachedServers "x.x.x.x:11211,x.x.x.x:11211,x.x.x.x:11211";

Here is the /etc/sysconfig/memcached

PORT="11211"
USER="memcached"
MAXCONN="1024"
CACHESIZE="64"
OPTIONS="-l x.x.x.x"

Here is loaded /opt/remi/php56/root/etc/php.d/40-memcache.ini

extension=memcache.so
memcache.allow_failover=1
memcache.hash_strategy=consistent
memcache.redundancy=1
memcache.session_redundancy=3 << have tried "4" so servers+1 but same issue.
session.save_handler=memcache
session.save_path="tcp://x.x.x.x:11211?persistent=1&weight=1&timeout=1&retry_interval=30,tcp://x.x.x.x:11211?persistent=1&weight=1&timeout=1&retry_interval=30,tcp://x.x.x.x:11211?persistent=1&weight=1&timeout=1&retry_interval=30"

Here is memcached running and stats

telnet x.x.x.x 11211
Trying x.x.x.x...
Connected to x.x.x.x.
Escape character is '^]'.
stats
STAT pid 31174
STAT uptime 2808
STAT time 1470565471
STAT version 1.4.15
STAT libevent 2.0.21-stable
STAT pointer_size 64
STAT rusage_user 0.095252
STAT rusage_system 0.122210
STAT curr_connections 6
STAT total_connections 13
STAT connection_structures 8
STAT reserved_fds 20
STAT cmd_get 200
STAT cmd_set 151
STAT cmd_flush 0
STAT cmd_touch 0
STAT get_hits 86
STAT get_misses 114
STAT delete_misses 0
STAT delete_hits 0
STAT incr_misses 3
STAT incr_hits 20
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT touch_hits 0
STAT touch_misses 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 36221
STAT bytes_written 25835
STAT limit_maxbytes 67108864
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT threads 4
STAT conn_yields 0
STAT hash_power_level 16
STAT hash_bytes 524288
STAT hash_is_expanding 0
STAT bytes 26297
STAT curr_items 88
STAT total_items 151
STAT expired_unfetched 1
STAT evicted_unfetched 0
STAT evictions 0
STAT reclaimed 2
END

Can you please offer any assistance at all as to why I am seeing "ngx_pagespeed AprMemCache" errors in the Nginx log on all of the 3 servers in the cluster? I assume this is related to PageSpeed from the "ngx_pagespeed" section of the error.

The main discussion was started here: https://support.sysally.net/boards/1/topics/6011

Thanks for any help! 

C.

**Comment by oschaaf** [comment]
At what frequency are the "ngx_pagespeed AprMemCache" entries logged?

Also, do you have the admin pages set up?
See https://developers.google.com/speed/pagespeed/module/admin

The admin pages are able to lists the status of the memcached servers as perceived by the module, and I'm curious what that looks like (/pagespeed_global_admin/cache#physical_cache)

**Comment by cerriex** [comment]
Hi, Can see it happening on every page load of page. Hit F5 and will see it happen. 

I've not had the admin pages enabled before, and have had no luck in doing so just now. Will keep trying.

**Comment by cerriex** [comment]
Ah got it now.. Yes you are right looks like it cannot talk to memcached at all.

Error getting memcached server status for localhost:11211

Any idea why this may be? I set the IP of memcached and added that to /etc/nginx/conf.d/pagespeed.conf yet it still says "localhost:11211"

Thanks.

**Comment by cerriex** [comment]
Add the IPs to /etc/nginx/conf.d/pagespeed_default.conf as well as /etc/nginx/conf.d/pagespeed.conf  and I see data now:

memcached server SERVER-1-IP:11211 version 1.4.15 pid 405 up 7278 seconds 
bytes:                 0
bytes_read:            54
bytes_written:         3076
cmd_get:               1
cmd_set:               0
connection_structures: 7
curr_connections:      6
curr_items:            0
evictions:             0
get_hits:              0
get_misses:            1
limit_maxbytes:        67108864
pointer_size:          64
rusage_system:         175864
rusage_user:           64
threads:               4
total_connections:     7
total_items:           0

memcached server SERVER-2-IP:11211 version 1.4.15 pid 390 up 14416 seconds 
bytes:                 11760
bytes_read:            14778
bytes_written:         11140
cmd_get:               93
cmd_set:               54
connection_structures: 8
curr_connections:      6
curr_items:            40
evictions:             0
get_hits:              25
get_misses:            68
limit_maxbytes:        67108864
pointer_size:          64
rusage_system:         371033
rusage_user:           64
threads:               4
total_connections:     15
total_items:           54


Error getting memcached server status for SERVER-1-IP:11211,SERVER-3-IP:11211,SERVER-2-IP:11211

**Comment by cerriex** [comment]
EDIT Added the memcached server IPs to the /etc/nginx/conf.d/pagespeed_default.conf as well as /etc/nginx/conf.d/pagespeed.conf and I see data now for all servers:

memcached server SERVER-1-IP:11211 version 1.4.15 pid 405 up 7989 seconds 
bytes:                 102580
bytes_read:            120974
bytes_written:         49930
cmd_get:               441
cmd_set:               170
connection_structures: 12
curr_connections:      11
curr_items:            127
evictions:             0
get_hits:              116
get_misses:            325
limit_maxbytes:        67108864
pointer_size:          64
rusage_system:         280824
rusage_user:           64
threads:               4
total_connections:     15
total_items:           170

memcached server SERVER-2-IP:11211 version 1.4.15 pid 11568 up 457 seconds 
bytes:                 511146
bytes_read:            517309
bytes_written:         57866
cmd_get:               402
cmd_set:               132
connection_structures: 13
curr_connections:      12
curr_items:            124
evictions:             0
get_hits:              157
get_misses:            245
limit_maxbytes:        67108864
pointer_size:          64
rusage_system:         42839
rusage_user:           64
threads:               4
total_connections:     14
total_items:           132

memcached server SERVER-3-IP:11211 version 1.4.15 pid 390 up 15126 seconds 
bytes:                 730553
bytes_read:            751018
bytes_written:         71466
cmd_get:               565
cmd_set:               298
connection_structures: 13
curr_connections:      12
curr_items:            232
evictions:             0
get_hits:              186
get_misses:            379
limit_maxbytes:        67108864
pointer_size:          64
rusage_system:         496978
rusage_user:           64
threads:               4
total_connections:     24
total_items:           298

I now only see the error in SERVER-2 : /var/log/nginx/error_log

[error] 8381#8554: [ngx_pagespeed 1.11.33.2-0] AprMemCache::Put error: Could not find specified socket in poll list.

Seems we are getting somewhere ;)

**Comment by oschaaf** [comment]
@cerriex Did you get Server 2 working? Closing this issue -- as you have Servers 1 & 3 working, I'm assuming there's no bug in ngx_pagespeed. If you have further questions, feel free toask them at the discussion list. https://groups.google.com/forum/#!forum/ngx-pagespeed-discuss

**Comment by cerriex** [comment]
Hi, yes thank you all sorted. was issue this end. thanks for help!
