### ISSUE TITLE
.deb package: pagespeed_libraries.conf installed in wrong path for Apache httpd 2.4.x

### ISSUE THREAD

**Issue by wolfgangkarall** [apache/incubator-pagespeed-mod#1389]
Hi,

mod-pagespeed-stable installed from the APT repository installs

```
# dpkg -L mod-pagespeed-stable | grep pagespeed_libraries.conf
/etc/apache2/conf.d/pagespeed_libraries.conf
```

But the 2.4 layout for Debian/Ubuntu doesn't include that directory in the server config anymore, but uses

`IncludeOptional conf-enabled/*.conf`

(i.e. `/etc/apache2/conf-enabled/*.conf`) instead.

Cheers
Wolfgang

**Comment by hillsp** [comment]
Ugh, that's not good news. Can you tell us what version of apache 2.4 and ubuntu/debian you have?

**Comment by wolfgangkarall** [comment]
I only use mod-pagespeed-stable on this system where the problem showed when upgrading to Debian 8.0, but the configuration was switched to using `conf-enabled/*.conf` also in all Ubuntu versions starting with at least 14.04:

Debian 8.0:

```
Server version: Apache/2.4.10 (Debian)
IncludeOptional conf-enabled/*.conf
```

Ubuntu 14.04 LTS (trusty):

```
Server version: Apache/2.4.7 (Ubuntu)
IncludeOptional conf-enabled/*.conf
```

Ubuntu 16.04 LTS (xenial):

```
Server version: Apache/2.4.18 (Ubuntu)
IncludeOptional conf-enabled/*.conf
```

**Comment by jeffkaufman** [comment]
If you're building one module for each version of Ubuntu, as a distro packager would, this is easy: your script for Ubuntu 12 puts it in `/etc/apache2/conf.d/` while for Ubuntu 14+ you put it in `/etc/apache2/conf-enabled/`.  We just build one package for both, and I'd really rather not start building two packages!

Looking at the install scripts, something like "put it in `conf-enabled/` if that exists, otherwise `conf.d/`" doesn't look like it will work, since we first install into a staging area, creating the directories we need, and then that gets installed from there.

Given that Ubuntu 12 EOLs in April and shouldn't be getting many new installs, and this feature hasn't been installing correctly on Ubuntu 14+ for the past several years, I'm inclined to do the easy thing and switch from unconditionally installing to `conf.d/` to unconditionally installing to `conf-enabled/`.

Objections?

**Comment by morlovich** [comment]
Sort of: Pretty sure it's supposed to be installed into conf-available and
then symlinked into conf-enabled, by running a2enconf
I think we do something similar with pagespeed.conf

**Comment by jeffkaufman** [comment]
Hmm.  `a2enconf` isn't available on Ubuntu 12, since that's pre symlinking for conf.

Maybe we should install it into conf-available regardless of Ubuntu version, and then if `a2enconf` is available have `postinst` run that, otherwise `postinst` should manually symlink it into /etc/apache2/conf.d

**Comment by jeffkaufman** [comment]
(This has the advantage of working on both Ubuntu 12 and on later versions.)

**Comment by wolfgangkarall** [comment]
@jeffkaufman a2enconf works with /etc/apache2/conf-available/ so it's no wonder it's not available in 12.04/precise.

And I guess you'll have to make postinst aware of the version of apache2 and then act depending on that.

**Comment by wolfgangkarall** [comment]
Basically, install in both locations (maybe symlinking one to the other), and use a2enconf if it's available in postinst.

**Comment by jeffkaufman** [comment]
Ok, planning on this:
1) Install the config to `/etc/apache2/conf-available/` regardless, creating it if it doesn't exist.
2) In `postinst:configure()`, run:

```
        # Enable pagespeed-libraries.conf.  On recent systems you install config
        # files into /etc/apache2/conf-available and then use a2enconf to        
        # symlink it into /etc/apache2/conf-enabled.  On older systems there's   
        # just /etc/apache2/conf.d/, so we manually symlink it there instead.    
        # See https://github.com/pagespeed/mod_pagespeed/issues/1389             
        if hash a2enconf; then
          # a2enconf is available; use it.                                       
          a2enconf pagespeed_libraries
        else
          # this ubuntu is too old for that; manually symlink it                 
          ln -s ../conf-available/pagespeed_libraries.conf /etc/apache2/conf.d/
        fi
```

**Comment by wolfgangkarall** [comment]
I guess since `/etc/apache2/conf.d/pagespeed_libraries.conf` is an official 'Debian conffile' in the current package, you'll have to handle the removal of that before creating that symlink.

**Comment by morlovich** [comment]
Hmm, are we supposed to be doing a2disconf or something in an uninstall
config scriptlet, too?

**Comment by jeffkaufman** [comment]
We doc that you shouldn't make local changes to `pagespeed_libraries.conf`, so I think it's ok to remove /etc/apache2/conf.d/pagespeed_libraries.conf unconditionally?  If so then we can do:

```
        # If the old-style configuration file exists, remove it.                 
        if [ -e /etc/apache2/conf.d/pagespeed_libraries.conf ]; then
          rm /etc/apache2/conf.d/pagespeed_libraries.conf
        fi

        # Enable pagespeed-libraries.conf.  On recent systems you install config
        # files into /etc/apache2/conf-available and then use a2enconf to        
        # symlink it into /etc/apache2/conf-enabled.  On older systems there's   
        # just /etc/apache2/conf.d/, so we manually symlink it there instead.    
        # See https://github.com/pagespeed/mod_pagespeed/issues/1389             
        if hash a2enconf; then
          # a2enconf is available; use it.                                       
          a2enconf pagespeed_libraries
        else
          # this ubuntu is too old for that; manually symlink it                 
          ln -s ../conf-available/pagespeed_libraries.conf /etc/apache2/conf.d/
        fi
```

**Comment by jeffkaufman** [comment]
(I'm fumbling around a bit here, since I don't know much about debian packaging)
