### ISSUE TITLE
Don't strip rel=preload hints for resource types we don't optimize

### ISSUE THREAD

**Issue by jeffkaufman** [apache/incubator-pagespeed-mod#1392]
Right now if we see:

```
<link rel=preload as=font href=...>
```

or:

```
<link rel=preload as=document href=...>
```

we will strip the preload hint.  We should instead only be stripping hints for resources we optimize:

```
<link rel=preload as=script href=...>
<link rel=preload as=style href=...>
<link rel=preload as=image href=...>
```

Specifically, if `as` is something other than `script`, `style`, or `image` we should leave the hint alone.

**Comment by jmarantz** [comment]
And we should only strip preload hints for images when image-rewriting is on, and options()->image_preserve_urls() is off.

Similar for css_preserve_urls() and the variety of css-rewriting options (mostly combine_css and rewrite_css and  cache_extend_styles).

Similar for js_preserve_urls() and js-rewriting options including combine_javascript and rewrite_external_javascript and cache_extend_javascript but not rewrite_inline_javascript.

We'll have to be a little careful about curating the exact list of filters that trigger the stripping.

**Comment by jeffkaufman** [comment]
Right now `strip_subresource_hints_filter.cc` enables hint removal if:

```
driver_->can_modify_urls() &&
(!(options->css_preserve_urls() &&
   options->image_preserve_urls() &&
   options->js_preserve_urls()));
```

Each `HtmlFilter` has `bool CanModifyUrls()`, and `driver_->can_modify_urls()` just returns whether any enabled filter has `CanModifyUrls()` returning `true``(See`HtmlParse::CheckFilterBehavior`.)

This was written this way because at the time hints didn't specify types.

We can extend this to add `CanModifyImageUrls()`, `CanModifySyleUrls()`, `CanModifyScriptUrls()` but that's a much bigger chunk of work.

**Comment by jmarantz** [comment]
I might be kind of frustrated if I was using MPS just for aggressive image optimization, and it stripped all my CSS/JS hints.  How much work is this really?

**Comment by jeffkaufman** [comment]
> How much work is this really?

Kind of a pain.  Right now `RewriteFilter::CanModifyUrls` just returns `true`, so we'd need to go through all our filter classes and specify what kinds of urls they modify.

Alternatively, if `X_preserve_urls()` is set we could not strip X hints, and so your example person could set  preserve for css+js but not images.  That one is much easier to code, since `strip_subresource_hints_filter` can see (and already uses) the `preserve` settings.

**Comment by jeffkaufman** [comment]
Planning to go the preserve route.

We can come back and do the full thing later if we want to.
