### ISSUE TITLE
ERROR: inlined_image_type in cached_result , CSS parsing error

### ISSUE THREAD

**Issue by jominhyun** [apache/incubator-pagespeed-mod#1406]
[Wed Sep 28 17:42:22.288760 2016] [pagespeed:error] [pid 29189] [mod_pagespeed 1.11.33.4-0 @29189] [0928/174222:ERROR:image_rewrite_filter.cc(1950)] Invalid inlined_image_type in cached_result
[Wed Sep 28 17:42:22.309961 2016] [pagespeed:error] [pid 29189] [mod_pagespeed 1.11.33.4-0 @29189] [0928/174222:ERROR:image_rewrite_filter.cc(1950)] Invalid inlined_image_type in cached_result

[Wed Sep 28 17:39:44.161965 2016] [pagespeed:warn] [pid 22513] [mod_pagespeed 1.11.33.4-0 @22513] CSS parsing error in http://www.domain.com
[Wed Sep 28 17:40:35.495714 2016] [pagespeed:warn] [pid 16907] [mod_pagespeed 1.11.33.4-0 @16907] CSS parsing error in  http://www.domain.com

**Comment by jominhyun** [comment]
@

**Comment by oschaaf** [comment]
@jominhyun did you close this by accident? I have never seen messages like "Invalid inlined_image_type in cached_result" before. Did you, by chance, recently upgrade mod_pagespeed?
