### ISSUE TITLE
mod_pagespeed installed but not working in Apache/2.2.17 (CentOS)

### ISSUE THREAD

**Issue by rajamuthur** [apache/incubator-pagespeed-mod#1407]
I have installed mod_pagespeed in my server using following steps

　　　　Step 1: wget https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_i386.rpm
　　　　Step 2:   rpm -ivh mod-pagespeed-*.rpm 
　　　　Step 3:     yum install  mod-pagespeed-stable
　　　　Step 4: Add the following into pagespeed.conf     [Path : /etc/httpd/conf.d/pagespeed.conf]
　　　　    ModPagespeedEnableFilters rewrite_javascript,rewrite_css
　　　　    ModPagespeedEnableFilters recompress_png,recompress_jpeg
　　　　    ModPagespeedEnableFilters combine_css,combine_javascript
　　　　    ModPagespeedEnableFilters extend_cache
　　　　    ModPagespeedEnableFilters insert_dns_prefetch
　　　　    ModPagespeedEnableFilters remove_comments
　　　　    ModPagespeedEnableFilters inline_google_font_css
　　　　    ModPagespeedEnableFilters convert_meta_tags
　　　　    ModPagespeedEnableFilters flatten_css_imports
　　　　Step5: Enable ModPagespeed  in pagespeed.conf  
　　　　ModPagespeed  on
　　　　Step6: Restart the apache 

I can see mod_pagespeed is installed correctly. Its  not combine any css and js.

CMD:  yum list | grep page
## output:

man-pages.noarch                           2.39-12.el5                 installed
mod-pagespeed-stable.i386                  1.11.33.2-0                 installed

Also x-mod-pagespeed is not avalible in the header.

CMD: curl -D- http://localhost | less or CMD: curl -D- http://**.**.**1.38 | less
## output:

HTTP/1.1 403 Forbidden
Date: Thu, 29 Sep 2016 09:02:53 GMT
Server: Apache/2.2.17 (EL)
Accept-Ranges: bytes
Vary: Accept-Encoding
Content-Length: 3968
Content-Type: text/html; charset=UTF-8

Note: i tried samething in my local server. it was working fine.

i dont know what i am missing. Please help me out.
Thanks in advance.

**Comment by oschaaf** [comment]
It looks like you are receiving a 403/Forbidden response... I think mod_pagespeed will not process those, which explains the `X-Mod-PageSpeed` header missing.

However, when I query the server, I do get that header, but I noticed it is mentions a different mod_pagespeed version when I compare it to the one I would expect based on what I would expect based on the output of `yum list` that you posted (1.11.33.2):

```
curl -I -X GET http://anonimized/
```

I get:

```
HTTP/1.1 200 OK
Date: Thu, 29 Sep 2016 09:46:15 GMT
Server: Apache/2.2.15 (CentOS)
...
X-Mod-Pagespeed: 1.9.32.10-7443
...
```

I wonder how `1.9.32.10` was installed? Was that also via yum?

**Comment by rajamuthur** [comment]
Thanks for quick reply,

sorry i mistakenly enter another server ip. 

 1.9.32.10 is installed in  http://**.**.**1.38/  server.

 1.11.33.2 is installed in http://**.**.**1.75/ server.

yes i have installed through yum.

How to avoid '403/Forbidden response'

**Comment by rajamuthur** [comment]
[pagespeed_easter_75.txt](https://github.com/pagespeed/mod_pagespeed/files/500492/pagespeed_easter_75.txt)

**Comment by oschaaf** [comment]
http://anonimized/ times out for me, so I can't take a look myself. But if you could take a look at the html sources of a page with `?PageSpeedFilters=+debug` on the querystring, then the module should write debug comments in the html source right after the javascript and css files that you would have liked to see combined. You may find a clue in there.

**Comment by rajamuthur** [comment]
thanks.
Got an error as ''Cache-control: no-transform, preventing rewriting of http:\......" 

please take look at:
view-source:http://**.**.**1.75/*****/?PageSpeedFilters=+debug

<!--
mod_pagespeed on
Filters:
ah  Add Head
cc  Combine Css
jc  Combine Javascript
gp  Convert Gif to Png
jp  Convert Jpeg to Progressive
jw  Convert Jpeg To Webp
mc  Convert Meta Tags
pj  Convert Png to Jpeg
ws  When converting images to WebP, prefer lossless conversions
db  Debug
ec  Cache Extend Css
ei  Cache Extend Images
es  Cache Extend Scripts
fc  Fallback Rewrite Css 
if  Flatten CSS Imports
hw  Flushes html
ci  Inline Css
gf  Inline Google Font CSS
ii  Inline Images
il  Inline @import to Link
ji  Inline Javascript
idp Insert DNS Prefetch
js  Jpeg Subsampling
rj  Recompress Jpeg
rp  Recompress Png
rw  Recompress Webp
rc  Remove Comments
ri  Resize Images
cf  Rewrite Css
jm  Rewrite External Javascript
jj  Rewrite Inline Javascript
cu  Rewrite Style Attributes With Url
cp  Strip Image Color Profiles
md  Strip Image Meta Data

Options:
EnableRewriting (e) 1
FileCacheInodeLimit (afcl) 500000
RunExperiment (fur) False
StatisticsLogging (asle) True

#NumFlushes            0
#EndDocument after     10427us
#Total Parse duration  2129us
#Total Render duration 18546us
#Total Idle duration   8298us

```
SupportNoscript
```

**Comment by oschaaf** [comment]
It looks like some of the resources served with `cache-control:no-transform`, which the module respects by default.  To turn off mod_pagespeed's behavior of respecting this header, you can configure:

```
ModPagespeedDisableRewriteOnNoTransform off
```

But it may be wise to first double check why this header is written in the first place.
Also see https://developers.google.com/speed/pagespeed/module/configuration#notransform

**Comment by rajamuthur** [comment]
Its started working once i have added "ModPagespeedDisableRewriteOnNoTransform off" in pagespeed.conf.

Thank you very much.

Please remove ip(**.**.**_.75, *_.**.***.38) address  from your comment.

Thanks.

**Comment by oschaaf** [comment]
@rajamuthur great to hear it is working! I anonimized the ip addresses from my comments as requested.

**Comment by rajamuthur** [comment]
Thanks

**Comment by AlphabetTechnologies** [comment]
Hi...
step by step config for apache centos 6.9 -- text file for /etc/httpd/conf.d/pagespeed.conf
