### ISSUE TITLE
unit test DownstreamCacheWithPossiblePurgeTest.DownstreamCacheEnabled passes but leaks drivers

### ISSUE THREAD

**Issue by jmarantz** [apache/incubator-pagespeed-mod#1421]
I don't know if this a test artifact or evidence of some real problem, but running:

src/out/Debug/pagespeed_automatic_test \
 --gtest_filters=DownstreamCacheWithPossiblePurgeTest.DownstreamCacheEnabled 

we get:
[ RUN      ] DownstreamCacheWithPossiblePurgeTest.DownstreamCacheEnabled
[1020/102025:ERROR:google_message_handler.cc(41)] ServerContext: 1 leaked_rewrite_drivers on destruction
[1020/102025:ERROR:google_message_handler.cc(41)] URL: 
decoded_base: 
base_was_set: false
containing_charset: 
filters_added: true
externally_managed: false
waiting: kNoWait
waiting_deadline_reached: false
detached_rewrites_.size(): 0
RewritesComplete(): true
fully_rewrite_on_flush: false
fast_blocking_rewrite: true
flush_requested: false
flush_occurred: false
is_lazyload_script_flushed: false
release_driver: false
write_property_cache_dom_cohort: false
owns_property_page: false
xhtml_mimetype_computed: false
can_rewrite_resources: true
is_nested: false
ref counts:
    User references: 1  Parsing: 0  Pending rewrites: 0 Detached rewrites: 0    Deleting rewrites: 0    User-facing fetch rewrite: 0    Background fetch rewrite: 0 Misc async event: 0 Misc async event that's render-blocking: 0
[       OK ] DownstreamCacheWithPossiblePurgeTest.DownstreamCacheEnabled (26 ms)

**Comment by morlovich** [comment]
Other tests in the same family have the same problem, too.

**Comment by morlovich** [comment]
Huh, it's the other_rewrite_driver_ that's an issue. Strange, since I don't think that's even in use

**Comment by morlovich** [comment]
These tests seem to be the only ones to use RewriteTestBase::SetUseManagedRewriteDrivers(true).
It's possible way may have trouble in that case with the unused other_rewrite_driver somehow
