### ISSUE TITLE
Defer JS delaying javascript on Safari Desktop and Mobile

### ISSUE THREAD

**Issue by Slind14** [apache/incubator-pagespeed-mod#1431]
Hi there,

I got reports from iOS users that the time until the page's javascript is loaded did increase with the use of defer js.

So I looked at the loading order and found this:

**Chrome, Firefox, Opera, Vivaldi:**
- document
- stylesheet
- logo
- jquery
- main js
- images & further js & google font

**Safari:**
- document
- stylesheet
- svg images
- logo
- images
- google font
- non required js
- jquery
- main js
- further images and js

This is delaying the main javascript - which is required for many features of the site - by multiple seconds with safari (depending on the internet connection). 
Is this a known issue? (I couldn't find anything similar)

Any help would be great. Live example: `//hayday-forum.de` Main js: `WCF.Combined.min.js` pagespeed_version: `apache stable latest` (installed 2 days ago from official website, unfortunately it doesn't tell the version in the filename)

**Comment by jmarantz** [comment]
defer_javascript is probably not a good choice for sites where the main
content is loaded from JS.  It makes sense when the content is rendered as
HTML, and additional functionality (e..g menu actions, ads, analytics) is
loaded via JS.

The main surprise for me is that this isn't a problem for you on the other
browsers besides Safari.

What was your motivation for using defer_javascript on this site?

**Comment by Slind14** [comment]
The motivation is bad third party javascript which needs to run sync in the middle of the page. With defer it is being moved to the end of the page load without issues while trying to invoke it with document.write my self caused the script to overwrite the entire page.

The `WCF.Combined.min.js` is not a requirement. It's mainly in the navigational aspects. But if the page is loaded visually 4 seconds before the js it causes issues for the user wanting to navigate.
I'm really wondering why the script is loaded right after css and its dependencies on most browsers, that's like the perfect loading order, but on safari it fails.

It does reduce DOMContentLoaded from 2-3 Sec. down to 900ms on browsers with working loading order.

**Comment by jmarantz** [comment]
I don't see how this is a bug in defer_javascript.   However, if you are looking for a way to selectively delay the loading of third party JS, you should probably consider the 'async' attribute on the script tag.  See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script for details.

**Comment by Slind14** [comment]
Thank you. Unfortunately "async" and "defer" cause issues with the script. I resolved it now by excluding the specific script manually.
