### ISSUE TITLE
Debian Jessie error and warning from mod-pagespeed-stable 1.11.33.5-r0

### ISSUE THREAD

**Issue by danjde** [apache/incubator-pagespeed-mod#1446]
Hi friends,
I've installed and enabled mod-pagespeed on Debian Jessie and Apache2 2.4.10-10+deb8u7;
from now on I get a series of errors:

```
tail -f /var/log/apache2/error.log
[Sat Dec 10 16:16:42.543673 2016] [pagespeed:warn] [pid 20626] [mod_pagespeed 1.11.33.5-0 @20626] [1210/161642:WARNING:resource_fetch.cc(191)] Fetch failed for resource url https://www.vini-bulgarini.com/wp-content/uploads/2016/12/xNATALE_brut.jpg.pagespeed.ic.86_kTG7XlE.jpg
[Sat Dec 10 16:16:42.543752 2016] [pagespeed:warn] [pid 20626] [mod_pagespeed 1.11.33.5-0 @20626] Fetch failed for https://www.vini-bulgarini.com/wp-content/uploads/2016/12/xNATALE_brut.jpg.pagespeed.ic.86_kTG7XlE.jpg, status=404
[Sat Dec 10 16:16:42.544024 2016] [pagespeed:warn] [pid 20626] [mod_pagespeed 1.11.33.5-0 @20626] https://www.vini-bulgarini.com/wp-content/uploads/2016/12/xNATALE_brut.jpg.pagespeed.ic.86_kTG7XlE.jpg resource_404_count: not found (404)
[Sat Dec 10 16:22:40.690434 2016] [pagespeed:warn] [pid 20621] [mod_pagespeed 1.11.33.5-0 @20621] xevento4XWEB-632x416.jpg:0: Resource based on https://www.vini-bulgarini.com/wp-content/uploads/2016/11/evento4XWEB-632x416.jpg but cannot access the original
[Sat Dec 10 16:22:40.690497 2016] [pagespeed:warn] [pid 20621] [mod_pagespeed 1.11.33.5-0 @20621] [1210/162240:WARNING:resource_fetch.cc(191)] Fetch failed for resource url https://www.vini-bulgarini.com/wp-content/uploads/2016/11/xevento4XWEB-632x416.jpg.pagespeed.ic.UDO_lVS9Yx.jpg
[Sat Dec 10 16:22:40.690552 2016] [pagespeed:warn] [pid 20621] [mod_pagespeed 1.11.33.5-0 @20621] Fetch failed for https://www.vini-bulgarini.com/wp-content/uploads/2016/11/xevento4XWEB-632x416.jpg.pagespeed.ic.UDO_lVS9Yx.jpg, status=404
[Sat Dec 10 16:22:40.690749 2016] [pagespeed:warn] [pid 20621] [mod_pagespeed 1.11.33.5-0 @20621] https://www.vini-bulgarini.com/wp-content/uploads/2016/11/xevento4XWEB-632x416.jpg.pagespeed.ic.UDO_lVS9Yx.jpg resource_404_count: not found (404)
[Sat Dec 10 16:40:33.658291 2016] [pagespeed:error] [pid 20217] [mod_pagespeed 1.11.33.5-0 @20217] Slow ReadFile operation on file /var/cache/mod_pagespeed/rname/ic_jJ7wrIF7DG1ZpoWFzHtJ/https,3A/,2Fwww.pergraziaricevuta.it/wp/wp-content/plugins/final-tiles-gallery/lightbox/fancybox/fancybox-y.png,40x,40._,: 77.874ms; configure SlowFileLatencyUs to change threshold\n
[Sat Dec 10 17:13:49.619398 2016] [authz_core:error] [pid 20454] [client 2.33.224.117:27242] AH01630: client denied by server configuration: uri /wp-content/plugins/akismet/_inc/A.akismet.css,qver=3.2.pagespeed.cf.6x_ZXisMN8.css, referer: https://www.vini-bulgarini.com/wp-admin/
[Sat Dec 10 17:38:41.292760 2016] [pagespeed:error] [pid 20972] [mod_pagespeed 1.11.33.5-0 @20972] Slow ReadFile operation on file /var/cache/mod_pagespeed/v3/vini-bulgarini.com/https,3A/,2Fwww.vini-bulgarini.com/wp-content/uploads/2016/10/05-DECANTER-World-Wine-Award-2016-632x879,402x.jpg,: 101.955ms; configure SlowFileLatencyUs to change threshold\n
```

This is the enabled list modules:

```
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 cache_module (shared)
 cache_disk_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 expires_module (shared)
 ext_filter_module (shared)
 file_cache_module (shared)
 filter_module (shared)
 headers_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 pagespeed_module (shared)
 php5_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
```
also this morning, on a website Wordpress based I discovered that a graphic file had been deleted from the directory wp-content/uploads/...
could this depend on the module?

Many many thanks!

**Comment by oschaaf** [comment]
I see three types of warnings:
- A message about denying a client access into /wp-admin: this is not related to mod_pagespeed, and probably is what you want to happen.
- Warnings for image urls that respond with 404. The original image urls alse respond with 404, so I would say it's not a mod_pagespeed specific problem.
- Warnings about slow disk reads emitted by mod_pagespeed. You can hide them by configuring the logging threshold for this somewhat higher [1], but if they are only occasionally logged I wouldn't worry about them.

[1]
```
ModPagespeedSlowFileLatencyUs 200000
```

**Comment by danjde** [comment]
Everything you say is correct.
But you don't know why the log shown 404 error for:

> xNATALE_brut.jpg.pagespeed.ic.86_kTG7XlE.jpg
> xevento4XWEB-632x416.jpg.pagespeed.ic.UDO_lVS9Yx.jpg

The original (uncompressed) files above were loaded and then deleted shortly after by the wordpress user.
From that moment mod-pagespeed print the above warning.

Even now, all is ok for you? :-)

**Comment by oschaaf** [comment]
The warning for these images are logged when someone or something is still requesting these them. 
So it looks like the the images you mention still are linked somewhere, which is odd. Can you figure out the referrer for these requests from the access logs and check where and how they are linked?

**Comment by danjde** [comment]
> [10/Dec/2016:16:16:37 +0100] "GET /wp-content/uploads/2016/12/xNATALE_brut.jpg.pagespeed.ic.86_kTG7XlE.jpg HTTP/1.1" 301 700 "http://image.baidu.com/i?ct=503316480&z=0&tn=baiduimagedetail" "Baiduspider-image+(+http://www.baidu.com/search/spider.htm)"
> 
> [10/Dec/2016:16:22:38 +0100] "GET /wp-content/uploads/2016/11/xevento4XWEB-632x416.jpg.pagespeed.ic.UDO_lVS9Yx.jpg HTTP/1.1" 301 716 "http://image.baidu.com/i?ct=503316480&z=0&tn=baiduimagedetail" "Baiduspider-image+(+http://www.baidu.com/search/spider.htm)"

Perfect! Mystery solved: Baiduspider!

And about the slow disk warnings (,the third point) do you think that mod_pagespeed should be used only (or preferably) on hight performance i/o computers?

Thank you so much for making me understand how it works! :-)

**Comment by oschaaf** [comment]
I don't think you need a high performance i/o system, but you may have to tune its caches to reduce disk i/o:
https://developers.google.com/speed/pagespeed/module/system

If disk i/o really is a problem you could consider using memcached to work around that.

**Comment by oschaaf** [comment]
Also, an occasional warning about slow disk reads does not indicate a problem. But if you see lots of them, it would be good to address that.
