### ISSUE TITLE
Too long combined filenames are still being created 

### ISSUE THREAD

**Issue by ivnnv** [apache/incubator-pagespeed-mod#1461]
Hi,

An old issue previously reported on:
https://github.com/pagespeed/mod_pagespeed/issues/149
https://github.com/pagespeed/mod_pagespeed/issues/181
https://github.com/pagespeed/mod_pagespeed/issues/140
and
http://stackoverflow.com/questions/41170207/mod-pagespeed-error-without-the-module-enabled-or-ever-been-installed

Is still happening to us from time to time on our production server which is a:
Ubuntu 14.04.4 LTS 64 Bit
Apache version: 2.4.7
X-Mod-Pagespeed: 1.11.33.2-0
(+PHP 5.5.38 just for reference)
Despite we dont have the latest version of the pagespeed module, theres no mention to any fixes on regards this topic on the newer versions, hence we are opening this issue.

Below some of this kind of errors logged by apache:

[Mon Dec 19 16:26:45.648118 2016] [core:error] [pid 15278] (36)File name too long: [client xxx.xxx.xxx.xxx:xxxx] AH00036: access to /A.modules,,_revsliderprestashop,,_rs-plugin,,_css,,_static-captions.css+modules,,_revsliderprestashop,,_rs-plugin,,_css,,_dynamic-captions.css+modules,,_revsliderprestashop,,_css,,_front.css+themes,,_oteros,,_css,,_modules,,_newsletterpro,,_views,,_css,,_1.6,,_newsletterpro_front.css+themes,,_oteros,,_css,,_modules,,_tommatobrands,,_css,,_tommatobrands.css+themes,,_oteros,,_css,,_modules,,_linoscrosssellings,,_css,,_linoscrosssellings.css,Mcc.T9ye505ORO.css.pagespeed.cf.SkkzRRwvqY.css failed (filesystem path '/var/www/html/A.modules,,_revsliderprestashop,,_rs-plugin,,_css,,_static-captions.css+modules,,_revsliderprestashop,,_rs-plugin,,_css,,_dynamic-captions.css+modules,,_revsliderprestashop,,_css,,_front.css+themes,,_oteros,,_css,,_modules,,_newsletterpro,,_views,,_css,,_1.6,,_newsletterpro_front.css+themes,,_oteros,,_css,,_modules,,_tommatobrands,,_css,,_tommatobrands.css+themes,,_oteros,,_css,,_modules,,_linoscrosssellings,,_css,,_linoscrosssellings.css,Mcc.T9ye505ORO.css.pagespeed.cf.SkkzRRwvqY.css')

[Wed Dec 21 16:03:54.887088 2016] [core:error] [pid 19369] (36)File name too long: [client xxx.xxx.xxx.xxx:xxxx] AH00036: access to /modules,_csthemescript,_js,_jquery.touchSwipe.min.js+modules,_csthemescript,_js,_jquery.ui.totop.js+modules,_csthemescript,_js,_cs.script.js+modules,_csthemescript,_js,_jquery.appear.js+themes,_oteros,_js,_modules,_blockwishlist,_js,_ajax-wishlist.js+modules,_linos_menu,_js,_csmegamenu_addmore.js+themes,_oteros,_js,_modules,_linos_menu,_js,_csmegamenu_front.js+themes,_oteros,_js,_modules,_blocklayered,_blocklayered.js+js,_jquery,_ui,_jquery.ui.core.min.js+js,_jquery,_ui,_jquery.ui.widget.min.js+js,_jquery,_ui,_jquery.ui.mouseH$.min.js+js,_jquery,_ui,_jquery.ui.slider.min.js.pagespeed.jc.AB3esG3kyQ.js failed (filesystem path '/var/www/html/modules,_csthemescript,_js,_jquery.touchSwipe.min.js+modules,_csthemescript,_js,_jquery.ui.totop.js+modules,_csthemescript,_js,_cs.script.js+modules,_csthemescript,_js,_jquery.appear.js+themes,_oteros,_js,_modules,_blockwishlist,_js,_ajax-wishlist.js+modules,_linos_menu,_js,_csmegamenu_addmore.js+themes,_oteros,_js,_modules,_linos_menu,_js,_csmegamenu_front.js+themes,_oteros,_js,_modules,_blocklayered,_blocklayered.js+js,_jquery,_ui,_jquery.ui.core.min.js+js,_jquery,_ui,_jquery.ui.widget.min.js+js,_jquery,_ui,_jquery.ui.mouseH$.min.js+js,_jquery,_ui,_jquery.ui.slider.min.js.pagespeed.jc.AB3esG3kyQ.js')

**Comment by Lofesa** [comment]
Have you tried the "ModPagespeedMaxSegmentLength 250" parameter in pagespeed config?
You can read it [here](https://developers.google.com/speed/pagespeed/module/restricting_urls) Limiting the maximum generated URL segment length and [here](https://developers.google.com/speed/pagespeed/module/filter-css-combine) Limitations

Hope this help

**Comment by ivnnv** [comment]
Hi,
We have tested the parameter on our stating server and indeed it seems to shorter the combined urls.

We are going to make the change on our production server and track the logs for errors a couple of days and close the issue if issue is solved.

Many thanks.

**Comment by Lofesa** [comment]
@IvanLinos de nada y que funcione ;-)

**Comment by ivnnv** [comment]
@Lofesa muchas gracias!

Solution by @Lofesa seems to be working, no more long name errors since we applied ModPagespeedMaxSegmentLength parameter. Issue solved.
