### ISSUE TITLE
prioritize_critical_css - not working for chrome incognito and not confirmed by pagespeed test

### ISSUE THREAD

**Issue by ecommy** [apache/incubator-pagespeed-mod#1486]
When I activate prioritize_critical_css filter - this is not confirmed by pagespeed test. 

Further mode:
I see the inline above-the-fold CSS if I manually test using chrome, but for instance if I test using the incognito mod =>, the filter seems that is not triggered (in view source I only see the original code)

**Comment by oschaaf** [comment]
When I view the source [1] of the prioritize critical css example at modpagespeed.com with Chrome in incognito mode, I do get the critical css inlined.

The filter depends on browsers beaconing back data to mod_pagespeed and therefore needs a couple of pageloads to determine which elements are critical.  It needs to do so for different classes of browsers, so Insights may need to run a couple of times before it gets the fully optimized response with critical css inlined.

[1] http://www.modpagespeed.com/prioritize_critical_css.html?PageSpeed=on&PageSpeedFilters=rewrite_css,flatten_css_imports,inline_import_to_link,prioritize_critical_css

Closing this issue, but please re-open it if the issue persists.

**Comment by devgeektech** [comment]
Hello Guys 

I am using the page speed module in my website. 
https://fallsriversoap.com/

I am using this filter...Please check attach snapshot..
![screenshot from 2018-07-20 16-20-32](https://user-images.githubusercontent.com/21241618/42998782-ffdb0cf0-8c38-11e8-8705-ad5a0dc4aefc.png)

ModPagespeedEnableFilters prioritize_critical_css


But i am still getting the issue of  "Your page has 1 blocking CSS resources. This causes a delay in rendering your page."

https://prnt.sc/k8tk5g

Please let me know how could it resolve.

**Comment by devgeektech** [comment]
Hello Guys 

Also, I implement the page speed module here:

https://fallsriversoap.com/pagespeed_admin/

But I have no idea how i link with pages as like to click on :  "Configuration" then how i will open the config page.
As same like other pages how we connect that..Basically i want to know that how we set handlers in pagesped.conf to link pages.

Also i don't get the handler of GRAPHS to link.
I tried to found here but it have not graph handlers  https://www.modpagespeed.com/doc/admin 

Please let me know that if you help me on this
