### ISSUE TITLE
Mixed Content on Resources (Wordpress, nginx proxy)

### ISSUE THREAD

**Issue by discostur** [apache/incubator-pagespeed-mod#1500]
Hi,

i'm running a wordpress installation behind a nginx proxy with mod_pagespeed. The wordpress runs on plain HTTP and the nginx does terminate the SSL connections:

https (nginx, mod_pagespeed) -> proxy_pass -> http (apache, wordpress)

The problem is i'm getting mixed content errors, because wordpress (and other CMS, too) can't recognize the x_forwared_for header correctly and they still think they are running on http (no ssl).

mod_pagespeed rewrites the css / javascript files correctly, but the browser still tries to load the content via http:

```
http://proxy.xxx.de/wp-content/themes/twentyfourteen/genericons/A.genericons.css,qver=3.0.3.pagespeed.cf.mweVyKKY-g.css
```

Is there any possibility to tell mod_pagespeed to rewrite the URLs from http -> https? Then the resources would be loaded correctly (no mixed content errors).

I already tried some "MapOriginDomain" or "MapRewriteDomain" settings, but none of them worked.

Thanks, 
Greets
Kilian

**Comment by oschaaf** [comment]
Do you have `RespectXForwardedProto` set up and turned on?:
https://modpagespeed.com/doc/https_support#RespectXForwardedProto

`MapRewriteDomain` is what you need to rewrite http to https, plus probably the `rewrite_domains` filter to also point non-pagespeed urls to https: https://modpagespeed.com/doc/filter-domain-rewrite.

**Comment by discostur** [comment]
@oschaaf 

Thanks for your help, it looks like **rewrite_domains** solved the problem:

```
 pagespeed MapRewriteDomain https://proxy.xxx.de http://proxy.xxx.de;
 pagespeed EnableFilters rewrite_domains; 
```

That works for me! ;)
