### ISSUE TITLE
Not working, nothing in the headers

### ISSUE THREAD

**Issue by mcpacific** [apache/incubator-pagespeed-mod#1521]
I've installed mod_pagespeed as per instructions but when I go to view the response headers, I do not see "X-Mod-Pagespeed" in the response header at all. The website is an https-only website; does this matter? My server is a Centos 6.8 server with WHM/cPanel.

**Comment by mcpacific** [comment]
I should add, httpd -M shows "pagespeed_module (shared)" so I believe it's installed properly...

**Comment by jmarantz** [comment]
Can you paste your config?

What content-type is on your HTML?

**Comment by mcpacific** [comment]
Here is my pagespeed.conf file contents:
```
`<IfModule !mod_version.c>
  LoadModule version_module modules/mod_version.so
</IfModule>

<IfVersion < 2.4>
  LoadModule pagespeed_module modules/mod_pagespeed.so
</IfVersion>
<IfVersion >= 2.4.2>
  LoadModule pagespeed_module modules/mod_pagespeed_ap24.so
</IfVersion>

<IfModule pagespeed_module>
  ModPagespeed off

  AddOutputFilterByType MOD_PAGESPEED_OUTPUT_FILTER text/html

  ModPagespeedFileCachePath            "/var/mod_pagespeed/cache/"

  
  <Location /mod_pagespeed_beacon>
        SetHandler mod_pagespeed_beacon
  </Location>

  <Location /mod_pagespeed_statistics>
      Order allow,deny
      Allow from localhost
      SetHandler mod_pagespeed_statistics
  </Location>

  ModPagespeedEnableFilters prioritize_critical_css
  ModPagespeedEnableFilters defer_javascript
  ModPagespeedEnableFilters sprite_images
  ModPagespeedEnableFilters rewrite_images
  ModPagespeedEnableFilters recompress_png
  ModPagespeedEnableFilters convert_png_to_jpeg,convert_jpeg_to_webp
  ModPagespeedEnableFilters collapse_whitespace,remove_comments

</IfModule>`
```

I enabled pagespeed for a specific domain in it's .htaccess file. I was able to get the response header but now I get 404 errors:

```
<IfModule pagespeed_module>
    ModPagespeed on
</IfModule>
```

Content-Type: text/html; charset=UTF-8

**Comment by jmarantz** [comment]
So IIUC the problem with no responsive headers is now solved, and you have
a new problem with 404s?

404s on what URLs?   On HTML files?  On resources whose URLs are rewritten
by PageSpeed?

**Comment by mcpacific** [comment]
Not really. Although when I use curl to view the headers I see "X-Mod-Pagespeed: 1.11.33.4-0
", it doesn't appear in the Response Header section in Google Development tools:

```
Accept-Ranges:bytes
Cache-Control:max-age=2419200, public
Connection:Keep-Alive
Content-Length:3707
Content-Type:image/png
Date:Tue, 28 Mar 2017 21:26:56 GMT
Etag:W/"PSA-XARIYRKaRM"
Expires:Thu, 27 Apr 2017 05:02:32 GMT
Keep-Alive:timeout=5, max=995
Last-Modified:Fri, 28 Oct 2016 19:51:08 GMT
Server:Apache
X-Content-Type-Options:nosniff
```

The 404 errors seem to be limited to .jpg files that are being rewritten to .webp files:

xfile.jpg.pagespeed.ic.wz-T2Kcb51.webp

**Comment by jmarantz** [comment]
mod_pagespeed doesn't put x-mod-pagespeed headers on rewritten resources,
only on HTML.

The header Etag:W/"PSA-XARIYRKaRM" tells me this png was rewritten by
PageSpeed.

Now let's figure out what's going on with the webp files. Do you have a
multi-server setup?

**Comment by mcpacific** [comment]
If you're asking if I have multiple vhosts on this server, the answer is yes. Most are old sites, however.

**Comment by jmarantz** [comment]
Actually I was asking if you had multiple machines behind a load balancer.
That's one potential source of 404s, if you don't have mod_pagespeed
configured on all machines that might service a request for resources
rewritten by PageSpeed.

Another source of trouble, sometimes, is mod_rewrite.

**Comment by mcpacific** [comment]
Ah ok, no, just this one server.

Should I disable mod_rewrite? We do have several rewrites in our .htaccess file...

**Comment by jmarantz** [comment]
I assume you have rewrite rules you need or you wouldn't have them :)

But we may need to tweak them to avoid them corrupting PageSpeed's
rewritten URLs.  You can paste them in hear though I have to admit I'm not
a mod_rewrite expert.  I just know it has caused issues in the past.

I've also seen configs that block unexpected file types (e.g. webp) in some
way.

**Comment by mcpacific** [comment]
There are so many, but here are a few (I've replaced our actual domain with ourdomain.net):

```
RewriteCond %{SERVER_PORT} 80
RewriteCond %{HTTP_HOST} ^ourdomain\.net$ [OR]
RewriteCond %{HTTP_HOST} ^www\.ourdomain\.net$
RewriteRule ^(.*)$ "https://www.ourdomain.net/$1" [R=301,L]

RewriteCond %{SERVER_PORT} 443
RewriteCond %{HTTP_HOST} ^ourdomain\.net$
RewriteRule ^(.*)$ "https://www.ourdomain.net/$1" [R=301,L]
```

The rest are just basic rewrites like:

```
RewriteCond %{HTTP_HOST} ^www\.ourdomain\.net$
RewriteRule ^old\-url/$ "https://www\.ourdomain\.net/new\-url/" [R=301,L]
```

**Comment by jmarantz** [comment]
It's hard for me to tell what will break in your setup, but I think can
keep it simple:
You should not have mod_rewrite touch any URLs with ".pagespeed." in them.
If you touch them, then mod_pagespeed will probably not be able to decode
them, and you'll get a 404.

**Comment by mcpacific** [comment]
I read in another post to add an exception for mod_pagespeed URLs by adding:

`RewriteCond %{REQUEST_URI} !pagespeed`

but I wasn't clear to me if it's necessary to add it to every rewrite or not.

**Comment by mcpacific** [comment]
I added it to all of them and it doesn't appear to make any difference.

**Comment by mcpacific** [comment]
Just to see what would happen if I disabled mod_rewrite altogether... I tried that but still I go the 404 errors. is it possible the cache folder doesn't have the correct permissions?

**Comment by jmarantz** [comment]
It's worth checking your error.log to see what happens when you request the
webp.  If there was a cache permissions problem you'd probably see it.

However, I don't think that could cause a 404.  That could cause a failure
to rewrite the resource, which is not happening.

**Comment by mcpacific** [comment]
There are these warnings. Also, I can't see any evidence that css or javascript is being combined:

```
[Wed Mar 29 07:58:26.489270 2017] [pagespeed:warn] [pid 21033] [mod_pagespeed 1.11.33.4-0 @21033] x1.jpg:0: Resource based on https://www.mydomain.net/_assets/images/parallax/1.jpg but cannot access the original
[Wed Mar 29 07:58:26.489326 2017] [pagespeed:warn] [pid 21033] [mod_pagespeed 1.11.33.4-0 @21033] [0329/075826:WARNING:resource_fetch.cc(191)] Fetch failed for resource url https://www.mydomain.net/_assets/images/parallax/x1.jpg.pagespeed.ic.PQf7K73gat.webp
[Wed Mar 29 07:58:26.489370 2017] [pagespeed:warn] [pid 21033] [mod_pagespeed 1.11.33.4-0 @21033] Fetch failed for https://www.mydomain.net/_assets/images/parallax/x1.jpg.pagespeed.ic.PQf7K73gat.webp, status=404
[Wed Mar 29 07:58:26.489478 2017] [pagespeed:warn] [pid 21033] [mod_pagespeed 1.11.33.4-0 @21033] https://www.mydomain.net/_assets/images/parallax/x1.jpg.pagespeed.ic.PQf7K73gat.webp resource_404_count: not found (404)
[Wed Mar 29 07:59:50.846631 2017] [pagespeed:warn] [pid 21059] [mod_pagespeed 1.11.33.4-0 @21059] x1.jpg:0: Resource based on https://www.mydomain.net/_assets/images/parallax/1.jpg but cannot access the original
[Wed Mar 29 07:59:50.846685 2017] [pagespeed:warn] [pid 21059] [mod_pagespeed 1.11.33.4-0 @21059] [0329/075950:WARNING:resource_fetch.cc(191)] Fetch failed for resource url https://www.mydomain.net/_assets/images/parallax/x1.jpg.pagespeed.ic.PQf7K73gat.webp
[Wed Mar 29 07:59:50.846704 2017] [pagespeed:warn] [pid 21059] [mod_pagespeed 1.11.33.4-0 @21059] Fetch failed for https://www.mydomain.net/_assets/images/parallax/x1.jpg.pagespeed.ic.PQf7K73gat.webp, status=404
[Wed Mar 29 07:59:50.846776 2017] [pagespeed:warn] [pid 21059] [mod_pagespeed 1.11.33.4-0 @21059] https://www.mydomain.net/_assets/images/parallax/x1.jpg.pagespeed.ic.PQf7K73gat.webp resource_404_count: not found (404)
```

**Comment by jmarantz** [comment]
Thanks for the log fragments. I think I have an idea what's going on now.  As an experiment can you turn on OptimizeForBandwidth (https://modpagespeed.com/doc/optimize-for-bandwidth), and let me know what you see?  Does that resolve the 404s?

**Comment by mcpacific** [comment]
Ok, the 404 errors have disappeared but there is some breakage in the display (perhaps some javascript is being deferred that shouldn't be deferred?). Using Google's Pagespeed Insights tool yields no change in score.

**Comment by mcpacific** [comment]
Actually in reloading Pagespeed insights, it did go up slightly (+3 on mobile and +6 on desktop), with scores of 63/81.

**Comment by jmarantz** [comment]
Hi -- sorry if I wasn't clear, I just wanted to use OptimizeForBandwidth as an experiment to see if it eliminated the errors.  I want to suggest a second experiment now.

I think this might be an other instance of this bug: https://github.com/pagespeed/mod_pagespeed/issues/1145

In a nutshell, if PageSpeed's fetching path doesn't work (usually due to network configuration) then we can run into functional problems in some cases described in detail in that bug.

The next experiment is to turn *off* OptimizeForBandwidth, and also turn off in-place resource optimization:

 ModPagespeedRewriteLevel CoreFilters
 ModPagespeedInPlaceResourceOptimization off

If you set these options up, and my theory is correct, you will get *no* optimized resources, and also never get 404s.  If that's the case then we just have to debug why fetching is failing.

**Comment by mcpacific** [comment]
No change. My Pagespeed scores are 60/74. Just to be clear, here are my filer settings (I rem'd out a couple):

```
  ModPagespeedEnableFilters prioritize_critical_css
  #ModPagespeedEnableFilters defer_javascript
  ModPagespeedEnableFilters combine_javascript
  ModPagespeedEnableFilters sprite_images
  ModPagespeedEnableFilters rewrite_images
  ModPagespeedEnableFilters recompress_png
  ModPagespeedEnableFilters convert_png_to_jpeg,convert_jpeg_to_webp
  ModPagespeedEnableFilters collapse_whitespace,remove_comments
  #ModPagespeedRewriteLevel OptimizeForBandwidth
  ModPagespeedRewriteLevel CoreFilters
  ModPagespeedInPlaceResourceOptimization off
```

**Comment by jmarantz** [comment]
Sorry -- forgot one thing.  Can you flush your cache?

My theory is that your fetching path is completely broken, and the configuration you just pasted will result in nothing being rewritten.  When you had OptimizeForBandwidth enabled, I would expect to see your images served with 
  Etag:W/"PSA-...."
but no URLs renamed, and a slightly better PSI score, because there is some image compression.

With the current configuration, if your setup is broken in the way I suspect it is, I expect to see no URLs changed, and no compressed assets, no Etag with that W/"PSA..." pattern.  The only thing in your config that will work is the HTML minfication.

I do expect to see lots of error messages in your error.log about failed fetches, and that's what I'd like to debug :)

**Comment by mcpacific** [comment]
After making these changes there have been no further entries in the error log (there were only warnings before, not errors).

**Comment by mcpacific** [comment]
Oh I forgot to tell you, I cleared the cache.

**Comment by jmarantz** [comment]
So...I'm not sure what the "no change" is relative to. Are you getting any URL rewriting happening with InPlaceResourceOptimization off, and CoreFilters on?  If so, then you are able to fetch, and this is not what I thought it was.

One more sanity check: how did you clear the PageSpeed server cache...did you have PageSpeed's cache purging enabled and use the admin site?  Or do you have it disabled and used "touch cache.flush"?

**Comment by mcpacific** [comment]
By "no change" I mean, the PSI scores are relatively unchanged. There are no 404 errors anymore (haven't had those for a while now). I don't see any evidence of URL rewriting.

I read online to delete and recreate the cache folder. I wasn't sure of the best way to do it.

**Comment by jmarantz** [comment]
That is not a good way to do it :)  In particular, it leaves behind any
in-memory cache entries.

To flush cache, please see: https://modpagespeed.com/doc/system#flush_cache

**Comment by jmarantz** [comment]
Also, for debugging purposes, it would be easier for me if we left PSI out
of it.  I'd rather work in terms of whether assets get optimized as we
predict, and URLs rewritten, and 404s served.  PSI is kind of a second
order effect after that, and has its own caching, which makes things harder
to debug.

**Comment by jmarantz** [comment]
Yes.

**Comment by mcpacific** [comment]
Ok, I did that but still nothing new to report

**Comment by jmarantz** [comment]
Just to clarify: with InPlaceResourceOptimization off, CoreFilters on, and a freshly cleared cache, refreshing the page in your browser does not result in any error messages about fetching written to the log?

Before you refresh the page in a browser, can you also open up the statistics page, click on "auto refresh", and the checkbox next to "number of pages"?  Then we can see which statistics are increasing while the system is trying to refresh your page.

**Comment by mcpacific** [comment]
Correct. Here is the last relevant log entry. It shows the cached being flushed but nothing after that.

`[Wed Mar 29 16:07:12.618855 2017] [pagespeed:warn] [pid 31504] [mod_pagespeed 1.11.33.4-0 @31504] Cache Flush 1`

**Comment by mcpacific** [comment]
When you say the "statistics" page, do you mean Chrome Developer tools > Network? Sorry I'm a little lost.

**Comment by jmarantz** [comment]
No, your mod_pagespeed server stats page.  E.g. http://modpagespeed.com/
pagespeed_admin/statistics

From your config, it would be http://localhost//mod_pagespeed_statistics


One other thing to try: visit YOURSITE?PageSpeedFilters=+debug, then look
at the HTML source. mod_pagespeed will inject debug comments showing why
optimizations failed.

**Comment by mcpacific** [comment]
It's a remote server, but when I subsitute the IP address i get 

```
Forbidden
You don't have permission to access /mod_pagespeed_statistics on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
```
As far as the debug output goes:
```
<!--Summary computation status for CriticalCssBeacon
Resource 0 https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css: Cannot create resource: either its domain is unauthorized and InlineUnauthorizedResources is not enabled, or it cannot be fetched (check the server logs)
Resource 1 https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic: Cannot create resource: either its domain is unauthorized and InlineUnauthorizedResources is not enabled, or it cannot be fetched (check the server logs)
Resource 2 https://fonts.googleapis.com/css?family=Roboto:100,200,300,400,500,600,700,800,900: Cannot create resource: either its domain is unauthorized and InlineUnauthorizedResources is not enabled, or it cannot be fetched (check the server logs)
Resource 3 https://fonts.googleapis.com/css?family=Roboto+Mono:400,700: Cannot create resource: either its domain is unauthorized and InlineUnauthorizedResources is not enabled, or it cannot be fetched (check the server logs)
Resource 4 https://www.mydomain.net/_assets/css/combined.min.css: Fetch failed or resource not publicly cacheable
Resource 5 https://www.mydomain.net/_assets/css/customize.min.css: Fetch failed or resource not publicly cacheable
--></body>
</html><!--
mod_pagespeed on
Filters:
ah	Add Head
cw	Collapse Whitespace
cc	Combine Css
jc	Combine Javascript
gp	Convert Gif to Png
jp	Convert Jpeg to Progressive
jw	Convert Jpeg To Webp
mc	Convert Meta Tags
pj	Convert Png to Jpeg
ws	When converting images to WebP, prefer lossless conversions
db	Debug
ec	Cache Extend Css
ei	Cache Extend Images
es	Cache Extend Scripts
fc	Fallback Rewrite Css 
if	Flatten CSS Imports
hw	Flushes html
ci	Inline Css
ii	Inline Images
il	Inline @import to Link
ji	Inline Javascript
js	Jpeg Subsampling
pr	Prioritize Critical Css
rj	Recompress Jpeg
rp	Recompress Png
rw	Recompress Webp
rc	Remove Comments
ri	Resize Images
cf	Rewrite Css
jm	Rewrite External Javascript
jj	Rewrite Inline Javascript
cu	Rewrite Style Attributes With Url
is	Sprite Images
cp	Strip Image Color Profiles
md	Strip Image Meta Data

Options:
EnableRewriting (e) 1
InPlaceResourceOptimization (ipro) False
RewriteLevel (l) Core Filters
RunExperiment (fur) False

#NumFlushes            0
#EndDocument after     284499us
#Total Parse duration  1732us
#Total Render duration 5519us
#Total Idle duration   282767us
Critical Images:
	https://www.mydomain.net/_assets/images/logo/logo.png
	https://www.mydomain.net/_assets/images/sliders/bg1.jpg
	https://www.mydomain.net/_assets/images/sliders/fg2.png
	https://www.mydomain.net/_assets/images/sliders/readout.png
	https://www.mydomain.net/_assets/js/masterslider/style/blank.gif
The following filters were disabled for this request:
	CriticalSelectorFilter: No critical selector info in cache
	SupportNoscript
-->
```

**Comment by jmarantz** [comment]
If it's a remote server, are you ssh-ing in to see the server error.log
file, and to flush the pagespeed cache?

This page isn't the whole story, right?  Can you look at the debug output
near your <img> tags?

**Comment by mcpacific** [comment]
Yes, that's right. Oh yes, I didn't see the ones near the image tags. Here's one:

`<!--4xx status code, preventing rewriting of https://www.mydomain.net/_assets/images/logo/logo.png--><!--4xx status code, preventing rewriting of https://www.mydomain.net/_assets/images/logo/logo.png-->`

For some reason it's there twice on each one.

**Comment by mcpacific** [comment]
The javascript files have something similar:

`<!--4xx status code, preventing rewriting of https://www.mydomain.net/_assets/js/less/less.min.js--><!--4xx status code, preventing rewriting of https://www.mydomain.net/_assets/js/less/less.min.js--><!--4xx status code, preventing rewriting of https://www.mydomain.net/_assets/js/less/less.min.js-->`

and 

`<!--The preceding resource was not rewritten because its domain (maxcdn.bootstrapcdn.com) is not authorized-->`

**Comment by jmarantz** [comment]
4xx failures mean fetch failures (consistent with my original theory).  What happened to the logs?  Can you try flushing cache, setting "loglevel info" in your apache config, and refreshing the browser again?  You might get more detail on what's going wrong in the logs.

But most likely, this is a case of the networking setup on your machine preventing a loopback fetch by hostname somehow.  You might be able to bypass fetching altogether with LoadFromFile (https://modpagespeed.com/doc/domains#ModPagespeedLoadFromFile), or to fetch directly from localhost via MapOriginDomain.  Please see https://modpagespeed.com/doc/domains#mapping_origin for details.

This message:

indicates that you are loading an asset from maxcdn.bootstrapcdn.com.  That domain is probably not running mod_pagespeed, so rewriting assets on it might fail.  If that's really a pull CDN with www.mydomain.net as an origin, then you can authorize it with:
  ModPagespeedDomain  maxcdn.bootstrapcdn.com

Hope this helps!

**Comment by mcpacific** [comment]
Indeed, it looks like my Apache loglevel was turned down to warning only.

```
[Thu Mar 30 07:09:24.179394 2017] [pagespeed:info] [pid 19774] [mod_pagespeed 1.11.33.4-0 @19774] HTTPCache key=https://www.mydomain.net/_assets/css/customize.min.css fragment=mydomain.net: remembering recent failure for 284 seconds.
[Thu Mar 30 07:13:12.221425 2017] [pagespeed:info] [pid 19743] [mod_pagespeed 1.11.33.4-0 @19743] HTTPCache key=https://www.mydomain.net/_assets/css/combined.min.css fragment=mydomain.net: remembering recent failure for 56 seconds.
[Thu Mar 30 07:13:12.221564 2017] [pagespeed:info] [pid 19743] [mod_pagespeed 1.11.33.4-0 @19743] HTTPCache key=https://www.mydomain.net/_assets/images/sliders/bg1.jpg fragment=mydomain.net: remembering recent failure for 56 seconds.
[Thu Mar 30 07:13:12.221616 2017] [pagespeed:info] [pid 19743] [mod_pagespeed 1.11.33.4-0 @19743] HTTPCache key=https://www.mydomain.net/_assets/js/masterslider/style/blank.gif fragment=mydomain.net: remembering recent failure for 56 seconds.
[Thu Mar 30 07:13:12.221665 2017] [pagespeed:info] [pid 19743] [mod_pagespeed 1.11.33.4-0 @19743] HTTPCache key=https://www.mydomain.net/_assets/images/sliders/readout.png fragment=mydomain.net: remembering recent failure for 56 seconds.
[Thu Mar 30 07:13:12.221709 2017] [pagespeed:info] [pid 19743] [mod_pagespeed 1.11.33.4-0 @19743] HTTPCache key=https://www.mydomain.net/_assets/images/sliders/fg2.png fragment=mydomain.net: remembering recent failure for 56 seconds.
```

I was configured ModPagespeedLoadFromFile for my static assets, but now I get
`<!--deadline_exceeded for filter CacheExtender--><!--deadline_exceeded for filter ImageRewrite-->`
for images and 
`<!--deadline_exceeded--><!--deadline_exceeded for filter Javascript--><!--deadline_exceeded for filter CacheExtender--><!--deadline_exceeded for filter JsCombine-->`
for javascript.

**Comment by mcpacific** [comment]
Ok I mapped my static resources to fetch from file, and I extended the deadline with ModPagespeedEnableFilters extend_cache. I noticed my existing sprites weren't appearing normally so I disabled ModPagespeedEnableFilters sprite_images. However, after going through all that my PSI scores remain unchanged :(

**Comment by jmarantz** [comment]
RE sprites: Could you break that out as specific bug with an example of what's broken?

RE: extend_cache -- does it look like  that's working now?  No 404s?  Did you also enable image optimization or combining or anything else?

RE PSI score: again this is a very indirect way to measure whether MPS is doing what it's supposed to be doing.   Even if MPS is working perfectly it can't guarantee a perfect score in PSI -- or even an improved one -- that depends on what state your site was in before.  And there are some things PSI wants that MPS just doesn't do automatically.  Let's make sure your system is working properly first.

**Comment by mcpacific** [comment]
I have a few image sprites I used in combination with CSS for backgrounds of different elements. When ModPagespeedEnableFilters sprite_images was enabled in my pagespeed.conf file, each element showed the first part of the sprite (only). For example, I have a sprite with 5 "awards", and each award displays in the background of 5 different li's. When it was enabled, all 5 li's showed the first award.

Yes, I believe the extend_cache has worked and there are no more 404's. Image optimization seems to be working.

Before I included ModPagespeedEnableFilters combine_css in my pagespeed.conf file, I noticed some of my CSS files were being inlined,  After including ModPagespeedEnableFilters combine_css I noticed:
`<!--deadline_exceeded for filter CacheExtender--><!--deadline_exceeded--><!--deadline_exceeded--><!--deadline_exceeded for filter CssFilter-->`

I removed it, cleared cache, restart Apache but the deadline_exceeded notice remained. So I've never seem them combined yet.

Also, on the bottom of each web page I have thumbnails for recent blog posts from our WordPress blog. I noticed that these images show:
`<!--Resource headers are preventing rewriting of https://www.mydomain.net/blog/wp-content/uploads/2016/10/imagename.jpg--><!--Resource headers are preventing rewriting of https://www.mydomain.net/blog/wp-content/uploads/2016/10/imagename.jpg-->`

**Comment by jmarantz** [comment]
Can you report a separate issue for the sprites including the actual images
and CSS needed to repro?

The deadline exceeded messages should go away when you refresh your browser
and the optimized assets are in your PageSpeed cache.  Flushing your cache
of course will make that process restart.

**Comment by mcpacific** [comment]
Yes I'll be happy to do that, regarding the sprites.

After flushing the cache and restarting my browser, I still couldn't get any of the css to combine. The smaller css files are inlined, but the larger ones are still loading as separate files. Some of them appear to be compressed more (with .pagespeed.cf.*.css added to their respective filenames). Several are untouched with "deadline_exceeded" showing.

**Comment by jmarantz** [comment]
You don't have to restart your browser.  Also you don't need to flush your cache at this point; I suggested that earlier to repro error logs.

Just refresh your browser a few times, so pagespeed has enough time to load & optimize all your resources and store them in its cache.  Then the deadline exceeded messages will disappear and the optimizations will either work, or will leave behind debug comments indicating why they didn't.

**Comment by jmarantz** [comment]
RE "too busy to rewrite" -- that should also be transient.  After refreshing the browser a few times, PageSpeed should catch up with all your image processing backlog (assuming you don't flush its cache).

RE combining in debug output -- not sure; can you check the HTML output following each 'link' tag, after refreshing a few times?

I don't know anything about WP thumbnails

**Comment by mcpacific** [comment]
I've refreshed many times but the css never combines. The only notes next to each link tag say "CSS not inlined since it&#39;s bigger than 2048 bytes".

Upon further inspection I don't believe javascript is combining either. Its seems that some of it is inlining, but none are being combined (sorry I didn't catch this sooner). Also in reference to javascript, it looks like any scripts that are being loaded, deferred, via jquery ( via $(document).reeady(function(){.getScript()} ) are being left untouched (perhaps this is by design?).

Does the order of the ModPagespeedEnableFilters "combine_css" and "combine_javascript" matter in the pagespeed.conf file? Here is the whole section as it stands now:
```

  ModPagespeedLoadFromFile "https://www.mydomain.net/_assets/" \
                           "/home/account/public_html/_assets/"
  ModPagespeedLoadFromFile "https://www.mydomain.net/blog/wp-content/uploads/" \
                           "/home/account/public_html/_assets/blog/wp-content/uploads/"
  ModPagespeedEnableFilters prioritize_critical_css
  #ModPagespeedEnableFilters defer_javascript
  ModPagespeedEnableFilters combine_css
  ModPagespeedEnableFilters combine_javascript
  #ModPagespeedEnableFilters sprite_images
  ModPagespeedEnableFilters rewrite_images
  ModPagespeedEnableFilters recompress_png
  ModPagespeedEnableFilters convert_png_to_jpeg,convert_jpeg_to_webp
  ModPagespeedEnableFilters collapse_whitespace,remove_comments
  ModPagespeedEnableFilters extend_cache
  #ModPagespeedRewriteLevel OptimizeForBandwidth
  ModPagespeedRewriteLevel CoreFilters
  ModPagespeedInPlaceResourceOptimization off
```

**Comment by mcpacific** [comment]
I guess I should add the fact that it doesn't combine css or javascript to the bug reports.

**Comment by jmarantz** [comment]
RE javascript: mod_pagespeed doesn't really parse or analyze JavaScript, so any script-loading via libraries like jquery cannot be optimized (except simple minification).

RE css: I think I have to see the testcase to understand why they are not combining.

I was kind of hoping that we'd figure out why your fetching is not working.  Even though you've bypassed fetching in your config with LoadFromFile, I really want to learn more about why fetching fails for some installations.

**Comment by mcpacific** [comment]
No worries. I the meantime I wrote my own script to automatically combine css and I'll go ahead and implement that for now. I was hoping we could get this to work but for now I need to move on to other matters. I'll be happy to revisit this anytime, should you come up with any ideas.

Thank you so much for your help.

**Comment by mcpacific** [comment]
I'm getting max-age=300 on all my pagespeed images, even though it is set for max-age=2419200 on the origin. I guess I have to leave "ModPagespeedInPlaceResourceOptimization off".

**Comment by Lofesa** [comment]
Some idea about this:
Use  ModPagespeedMaxCombinedCssBytes MaxBytes and ModPagespeedMaxCombinedJsBytes MaxBytes whit MaxBytes set to a value bigger that the sum of some of the css/js files.
Reference [here](https://modpagespeed.com/doc/filter-css-combine) and [here](https://modpagespeed.com/doc/filter-js-combine)


For the max-age issue, try to use ModPagespeedLoadFromFileCacheTtlMs implicit_cache_ttl_in_milliseconds because if you use LoadFromFile they don´t have cache headers
Reference [here](https://modpagespeed.com/doc/system)

**Comment by jmarantz** [comment]
Thanks Lofesa!  In addition to what Lofesa said, I am wondering if you are getting max-age=300 on your images whose URLs were rewritten (e.g. ximg.jpg.pagespeed.ic.HASH.webp.  Those should be cached for a year.

If you have images referenced from JavaScript (as opposed to HTML), then their URLs cannot be rewrritten, and ModPagespeedLoadFromFileCacheTtlMs is what you need, as Lofesa said, because we can't add the content-hash to those URLs.

**Comment by bitclaw** [comment]
I'm also getting an error like the one posted above about critical css (Using version mod-pagespeed: 1.11.33.2-0):

```shell
<!--Summary computation status for CriticalCssBeacon
--
  | Resource 0 http://www.vetformsdomaintwo.com/combine/ebc1b4b2684df9b1dc754d05da9572d3-1500410688.css: Computed OK
  | --></body></html><!--
  | mod_pagespeed on
  | Filters:
  | db	Debug
  | hw	Flushes html
  | pr	Prioritize Critical Css
  |  
  | Options:
  | CssInlineMaxBytes (ci) 600000
  | DownstreamCacheRewrittenPercentageThreshold (dcrpt) 99
  | EnableRewriting (e) 1
  | FileCacheInodeLimit (afcl) 500000
  | ImageResolutionLimitBytes (irlb) 128000000
  | MaxSegmentLength (uss) 1400
  | RewriteLevel (l) Pass Through
  | RunExperiment (fur) False
  | StatisticsLogging (asle) True
  |  
  | #NumFlushes            0
  | #EndDocument after     3810us
  | #Total Parse duration  1325us
  | #Total Render duration 3910us
  | #Total Idle duration   2485us
  | The following filters were disabled for this request:
  | CriticalSelectorFilter: No critical selector info in cache
  | SupportNoscript
  | -->
```

**Comment by oschaaf** [comment]
@bitclaw the debug comment you posted doesn't seem to mention an error? 
Could you open a new issue that includes the error?

Also I'm closing this issue (I think the initial report and follow up questions have been adressed by @jmarantz and @Lofesa, and a separate issue has been filed for a perceived problem during the discussion).
