### ISSUE TITLE
Pagespeed breaks headers_more 

### ISSUE THREAD

**Issue by dasJ** [apache/incubator-pagespeed-mod#1527]
When using both PageSpeed and [headers_more ](https://github.com/openresty/headers-more-nginx-module), `more_clear_headers` does not work with the first request.
The headers are removed in all other requests, but not in the first.

My configuration:
```
more_clear_headers Server X-Page-Speed X-Powered-By X-CF-Powered-By;
```

**Comment by oschaaf** [comment]
What version of ngx_pagespeed are you running?

**Comment by dasJ** [comment]
I'm sorry, I forgot to add the versions

nginx 1.11.10 (OpenSSL 1.0.2k)
ngx_pagespeed 1.11.33.4
headers_more 0.32

**Comment by oschaaf** [comment]
@dasJ I think this has to do with module ordering. See https://github.com/pagespeed/ngx_pagespeed/issues/612 (I will mark this issue as a duplicate and close it). 

There is a flag in ngx_pagespeed which allows you to re-order the module position, but I have not tested it in a while, and it is not covered in the CI tests. But maybe it is worth giving a shot, see the PR description here:
https://github.com/pagespeed/ngx_pagespeed/pull/906

**Comment by mtx-z** [comment]
Hello.

So in the end, we HAVE to build nginx with header_more AFTER ngx_pagespeed to make both work ? 
As before, I was building with header_more then pagespeed and it was working great. ty !

Now, when pagespeed is enabled : 
- default PNG image have correct headers
- rewrited WEBP images (from PNG sources) have no header but pagespeed ones, so no browser caching. 

When pagespeed is disable:
- all assets have correct header using header_more (including used PNG)

Strangely, all rewrited/optimised CSS have the correct caching headers. It fail only for images. 

Version : 
- pagespeed 1.12.34.3-stable
- nginx 1.13.6
- open SSL 1.1.0g
