### ISSUE TITLE
Wrong recompiled images cache-control max-age headers after a scan with PageSpeed Insight

### ISSUE THREAD

**Issue by teolaz** [apache/incubator-pagespeed-mod#1570]
Hi guys.
Strange situation here... 
If i open my page using Firefox, images have a correct cache-control: max-age rewritten by mod_pagespeed... but, the same images appear to have a different max-age when interrogated by PageSpeed Insight, and it tells my images have a 5 minutes max-age!

Let's take an example.

If you try to interrogate this page: https://www.lacantinapizzolato.com with Firefox, you can see the file 
`https://www.lacantinapizzolato.com/wp-content/uploads/2016/06/xDSC_0015-1-300x200.jpg.pagespeed.ic.LKkIrVBdUF.jpg`
which is a recompiled version of
`https://www.lacantinapizzolato.com/wp-content/uploads/2016/06/DSC_0015-1-300x200.jpg`
The image below show the response headers from Firefox for this file.

![image](https://user-images.githubusercontent.com/19909323/27436437-9736851c-575f-11e7-8d99-e60e1b8a3624.png)

But the same image, when interrogated using PageSpeed Insight show a different url and a max-age of 5 minutes:

![image](https://user-images.githubusercontent.com/19909323/27436488-bb7f6a2e-575f-11e7-8015-201e50cc95a1.png)

Why is this happening?

**Comment by oschaaf** [comment]
What happens if you run Insights a couple of times (with a 30 second delay between tests to make sure you do not get a cached report)? 

Insights may use a user-agent that is different compared to the one your browser users to query your website. That may imply that mod_pagespeed will plan for different optimizations. 

Perhaps you are getting a partially optimized response while mod_pagespeed finishes up these computations, and those are served with a 5 minute cache TTL.

**Comment by teolaz** [comment]
@oschaaf it continues to show the wrong file...
but why you're giving more than one version of the recompiled image in base on the user agent?
i agree with .webp extension, which is enabled only for Chrome's requests, but this seems a bit strange...

**Comment by oschaaf** [comment]
I can see the 5 minute TTL persists. It only seems to happen with the mobile tests. 

It may be a bug, what mod_pagespeed version is the site running? 
When I turn off `PageSpeedFilters=-resize_images` the behaviour goes away, that could be a clue where to look.

**Comment by teolaz** [comment]
It seems the version is 1.11.33.5-0 ...

**Comment by teolaz** [comment]
Now, after having `apache2 reload`, the problem seems to be gone, but happens the same yesterday... what happens during time? Do you change files after a short time?

I cannot understand if this is a Insight bug or not....

**Comment by junaid-A-khan** [comment]
just installed and configured pagespeed module but having same issue.

**Comment by Zwilla** [comment]
I have a solution - just watch an old thread and a very very old problem. It is an Apache Bug since years.
Google is not able too and Apache s.. on Google. Thats all! 

The magic word is: max-age

**Comment by oschaaf** [comment]
Closing this. If someone is still able to produce a clear reproduction case based on the latest stable , feel free to re-open.
