### ISSUE TITLE
mod_pagespeed issue

### ISSUE THREAD

**Issue by sankarkodali** [apache/incubator-pagespeed-mod#1574]
Hi,

mod_pagespeed is not working properly
when trying to install Preserve URL Relativity, giving module is deprecated
can you please explain how to activate Preserve URL Relativity

**Comment by sankarkodali** [comment]
My server configuration is CENTOS 6.9 x86_64 vmware – server, php7

**Comment by oschaaf** [comment]
The docs [1] state "Note: This option will be enabled by default in future versions of PageSpeed and eventually the option will be removed entirely."
The deprecation warning is probably related to that. Could you be running into this?
If so, you can probably just remove `ModPagespeedPreserveUrlRelativity on` from your configuration to eliminate the warning.
[1] https://modpagespeed.com/doc/configuration#preserve-url-relativity

**Comment by sankarkodali** [comment]
Thank you, My doubt has been clarified
