### ISSUE TITLE
<!--4xx status code, preventing rewriting of https:// mod_pagespeed 1.12.34.2-0

### ISSUE THREAD

**Issue by ghost** [apache/incubator-pagespeed-mod#1579]
There is the following website: https://www.easymodeloans.co.nz/?PageSpeedFilters=%20debug

The debug is littered with 4xx status code, preventing rewriting of https:// and isn't optimising anything.

The output of a header pull shows the following: curl -I https://www.easymodeloans.co.nz

HTTP/1.1 200 OK
Date: Tue, 04 Jul 2017 09:20:13 GMT
Server: Apache
Link: <https://www.easymodeloans.co.nz/wp-json/>; rel="https://api.w.org/", <https://www.easymodeloans.co.nz/>; rel=shortlink
X-Mod-Pagespeed: 1.12.34.2-0
Cache-Control: max-age=0, no-cache
Content-Type: text/html; charset=UTF-8

I had Xvarnish installed But I have now disabled it for testing as I was getting the same error. But disabling it seems to be having the same issues.

I have a completely default pagespeed.conf file currently. I have also tried adding X-Proto-Header parameter to on and it didn't make a difference.

It is a wordpress website - there is no caching plugins installed, and no https redirect plugins installed currently.

Any thoughts?

**Comment by oschaaf** [comment]
Can you try if explicitly mapping the origin helps?
https://modpagespeed.com/doc/https_support#map_the_origin

Another thing on that page that is worth double checking is "Configuring SSL Certificates"

**Comment by oschaaf** [comment]
Closing: moved to https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mod-pagespeed-discuss/HDs9AJZh7Ro/o7YWUhIWAgAJ
