### ISSUE TITLE
Css changed to bootstrap.min.css.pagespeed.cc.1nPuP5w9CU.css

### ISSUE THREAD

**Issue by kjareena** [apache/incubator-pagespeed-mod#1583]
Hi,

I am using mod_pagespeed for codeigniter website. First its working fine.

Suddenly site was down means bootstrap css changed to like below and it not calling
<link href="https://www.siteurl.com/styles/css/custom.css+bootstrap.min.css.pagespeed.cc.1nPuP5w9CU.css">

![image](https://user-images.githubusercontent.com/15811342/27851616-3881ef7e-6179-11e7-89e9-1e0fb485c7f6.png)

this is my .htaccess file code for  pagespeed_module

<IfModule pagespeed_module>
   
    ModPagespeed on
    ModPagespeedRewriteLevel CoreFilters
   #ModPagespeedEnableFilters combine_css
   #ModPagespeedEnableFilters combine_javascript
    AddOutputFilterByType MOD_PAGESPEED_OUTPUT_FILTER text/html

    ModPagespeedEnableFilters insert_dns_prefetch
    ModPagespeedDisableRewriteOnNoTransform off

# Text / HTML
 
    ModPagespeedEnableFilters collapse_whitespace
    ModPagespeedEnableFilters convert_meta_tags
    ModPagespeedEnableFilters remove_comments    
    ModPagespeedEnableFilters elide_attributes 

# JavaScript
 
    ModPagespeedEnableFilters rewrite_javascript   
    ModPagespeedEnableFilters inline_javascript

# CSS

    ModPagespeedEnableFilters rewrite_css    
    ModPagespeedEnableFilters move_css_to_head
    ModPagespeedEnableFilters inline_css
    ModPagespeedEnableFilters inline_import_to_link

# Images
    
    ModPagespeedEnableFilters insert_image_dimensions
    ModPagespeedEnableFilters resize_images
    ModPagespeedEnableFilters rewrite_images
    ModPagespeedEnableFilters recompress_images
    ModPagespeedEnableFilters resize_mobile_images

    ModPagespeedCriticalImagesBeaconEnabled false
    ModPagespeedLazyloadImagesAfterOnload off

# Google Analytics

    ModPagespeedEnableFilters insert_ga

</IfModule>

Please help me any one......

**Comment by oschaaf** [comment]
Looking at the site with `?PageSpeedFilters=+debug` I see lots of these comments like this in the html:
```
<!--4xx status code, preventing rewriting of https://www.pharmafocusasia.com/styles/js/jquery-ui-datepicker.js-->
```

It looks like the module has trouble fetching its inputs (the original css / js / images).
Could you take a look at https://modpagespeed.com/doc/https_support and verify the steps for https?
Alternatively, you could consider setting up `LoadFromFile` to allow the module to directly load static assets from disk.

**Comment by kjareena** [comment]
Hi Oschaaf,

Thank you so much for your quick response. 

I tried like you said 
https://www.automotive-technology.com/?PageSpeedFilters=+debug 

but it does not showing any comments. I am doing any this wrong ???

Actually i am new to Mod_Pagespeed i don't know exact steps to follow.
Please guide me where i am lagging.

**Comment by oschaaf** [comment]
I had to add `?PageSpeed=on` as well, it looks like the module was disabled.
With that, I do see debug comments.

**Comment by kjareena** [comment]
Hi,

**This is my server config file:**

[Mod page config.txt](https://github.com/pagespeed/mod_pagespeed/files/1127877/Mod.page.config.txt)


**And my .htaccess file**

<IfModule pagespeed_module>
    ModPagespeed on
    ModPagespeedRewriteLevel CoreFilters
	
    AddOutputFilterByType MOD_PAGESPEED_OUTPUT_FILTER text/html

    ModPagespeedEnableFilters insert_image_dimensions
    ModPagespeedEnableFilters resize_images
    ModPagespeedEnableFilters rewrite_images
    ModPagespeedEnableFilters recompress_images
    ModPagespeedEnableFilters resize_mobile_images

    ModPagespeedCriticalImagesBeaconEnabled false
    ModPagespeedLazyloadImagesAfterOnload off
    ModPagespeedCombineAcrossPaths off

    ModPagespeedDomain https://www.automotive-technology.com
    ModPagespeedDomain https://industry.automotive-technology.com
    ModPagespeedDomain https://www.automotive-technology.com/stylesheet/css
    ModPagespeedDomain *.automotive-technology.com

</IfModule>


-------------------------------------------

Website is working fine for few hours and after that unable to load the css, javascript, images.
combine css, js path is missing and images are converted to webp format.

Please help me to solve this issue

**Comment by oschaaf** [comment]
The debug filter shows a lot of comments like:
`<!--4xx status code, preventing rewriting of https://www.automotive-technology.com/stylesheet/css/font-awesome.min.css-->`

Do you see any user-agents mentioning 'mod_pagespeed' querying that file in the access logs?
If you do, what response codes are logged?
If there's not trace of the module requesting that file, I recommend taking a good look at https://modpagespeed.com/doc/https_support#https_fetch, because probably something at the https level isn't right.

**Comment by kjareena** [comment]
Hi,

Images issue has been solved.
But in css and js file getting  " <!--4xx status code, preventing rewriting of "  error.
Mod_pagespeed SSL have been enabled in server level. 

If i enable **SslCertFile**,**SslCertDirectory** my site will get 500 server error. 

#ModPagespeedSslCertDirectory /var/cpanel/ssl/installed/certs/www_ochre_media_com_d29e3_2409f_1516386605_949fe6da63214617ddf260bab24f07ad.crt
    #ModPagespeedSslCertFile /var/cpanel/ssl/installed/keys/d29e3_2409f_1263ad02419ee89c02312345992f7173.key

--------------------------------------------------------------
My **.htaccess**: file

<IfModule pagespeed_module>
    ModPagespeed on
    ModPagespeedRewriteLevel CoreFilters
    
    #ModPagespeedFetchHttps enable,allow_self_signed
    **#ModPagespeedSslCertDirectory /var/cpanel/ssl/installed/certs/www_ochre_media_com_d29e3_2409f_1516386605_949fe6da63214617ddf260bab24f07ad.crt
    #ModPagespeedSslCertFile /var/cpanel/ssl/installed/keys/d29e3_2409f_1263ad02419ee89c02312345992f7173.key**


    AddOutputFilterByType MOD_PAGESPEED_OUTPUT_FILTER text/html

    #ModPagespeedEnableFilters debug

    ModPagespeedEnableFilters extend_cache
	ModPagespeedEnableFilters rewrite_css

    ModPagespeedEnableFilters insert_image_dimensions
    ModPagespeedEnableFilters resize_images
    ModPagespeedEnableFilters rewrite_images
    ModPagespeedEnableFilters recompress_images
    ModPagespeedEnableFilters resize_mobile_images   

    ModPagespeedRespectXForwardedProto on
	ModPagespeedDomain https://www.automotive-technology.com
	ModPagespeedDomain industry.automotive-technology.com
	ModPagespeedDomain https://www.automotive-technology.com/stylesheet/css
	ModPagespeedDomain *.automotive-technology.com

	ModPagespeedMapRewriteDomain industry.automotive-technology.com *automotive-technology.com
	ModPagespeedMapRewriteDomain https://industry.automotive-technology.com http://industry.automotive-technology.com
   ModPagespeedCriticalImagesBeaconEnabled false
    ModPagespeedLazyloadImagesAfterOnload off
    ModPagespeedCombineAcrossPaths off
</IfModule>

Am doing any this wrong????? Kindly help me to solve css and js issue.

**Comment by oschaaf** [comment]
It would be helpful to get some more detail on the 500 error, probably
Apache's error logs can shed some light on that.
A guess: the docs state "These directive cannot be used in .htaccess files
or <Directory> scopes.".
Did you put the SslCertFile and SslCertDirectory directives in one of those?

Otto
