### ISSUE TITLE
Possible buffer over-read in RewriteDriver::ParseTextInternal

### ISSUE THREAD

**Issue by cellscape** [apache/incubator-pagespeed-mod#1590]
When `RewriteDriver::ShouldSkipParsing` returns true, `Write` is called with `content` without `size`. This results in conversion of `content` to `StringPiece` and relying on `strlen` to determine size. This could result in buffer over-read if `content` is not NULL-terminated.

https://github.com/pagespeed/mod_pagespeed/blob/32de3d0e12ff357b7a75e1e7e04507d2ccb560c7/net/instaweb/rewriter/rewrite_driver.cc#L2181

**Comment by oschaaf** [comment]
Thanks for the report!

**Comment by oschaaf** [comment]
@cellscape Addressed in https://github.com/pagespeed/mod_pagespeed/pull/1591, let me know if that looks good to you

**Comment by cellscape** [comment]
Looks good, thanks!
