### ISSUE TITLE
ERROR:worker.cc(127)

### ISSUE THREAD

**Issue by dom-de-monte** [apache/incubator-pagespeed-mod#1593]
Hello,
i am using mod_pagespeed 1.12.34.2 and apache prefork 2.4.25.

Many times, daily, i notice following error inside apache error_log:

[Mon Jul 10 13:48:25.513101 2017] [pagespeed:error] [pid 362927] [mod_pagespeed 1.12.34.2-0 @362927] [0710/134825:ERROR:worker.cc(127)] Unable to start worker thread
[Mon Jul 10 13:48:25.523955 2017] [pagespeed:error] [pid 362927] [mod_pagespeed 1.12.34.2-0 @362927] [0710/134825:ERROR:worker.cc(127)] Unable to start worker thread
[Mon Jul 10 13:48:25.524043 2017] [pagespeed:error] [pid 362927] [mod_pagespeed 1.12.34.2-0 @362927] [0710/134825:ERROR:worker.cc(127)] Unable to start worker thread
[Mon Jul 10 13:48:25.527764 2017] [pagespeed:error] [pid 362927] [mod_pagespeed 1.12.34.2-0 @362927] [0710/134825:ERROR:worker.cc(127)] Unable to start worker thread

From reading other posts/issues i already increased following user limits:

max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024000
max user processes              (-u) 1024000
virtual memory          (kbytes, -v) unlimited

vm.max_map_count = 655300

threads-max = 4096000

but no way.

Do you know where can i looking for more information about this error? 

Waiting for your reply

Regards

**Comment by oschaaf** [comment]
I've seen grsec being pointed out as a cause some time ago, in the context of these messages.

**Comment by dom-de-monte** [comment]
Thank you for your answer.

I am not using grsec neither selinux on that server.

I am using CloudLinux OS 6 in this case that could set some limits at kernel level.

 There is no way to enable some sort of debug in order to understand what's going on ? Do you suggest to enable debug at kernel level ?

**Comment by oschaaf** [comment]
Closing this, it doesn't seem to be a problem in mod_pagespeed itself but rather a system configuration issue. 
@Seizetsu if you ended up resolving this, any feedback you post here regarding that could be helpful to others running into the same problem!
