### ISSUE TITLE
Serf status 120171(APR does not understand this error code)

### ISSUE THREAD

**Issue by dom-de-monte** [apache/incubator-pagespeed-mod#1594]
Hello,
after 10 days of test our apache server was serving all request ( all with reply sending status W).

Also when i tried to execute a service httpd stop, next i had to kill manually all httpd processes that were NOT killed by service script.

I checked apache status and access_log but there were no external connection that could fill all slots so during checking error_log i notice many many messages like this:

[pagespeed:error] [pid 158274] [mod_pagespeed 1.12.34.2-0 @158274] Serf status 120171(APR does not understand this error code) polling for 1 threaded fetches for 0.05 seconds

Looking Google i found this https://groups.google.com/forum/#!topic/ngx-pagespeed-discuss/3cfPz35acRM where you refer to disable InPlaceResourceOptimization in that case.

I tried but i can see again those messages inside apache error_log.

Do you know which settings could cause this issue and where can i looking for ?

**Comment by oschaaf** [comment]
Serf 120171 is indicative of "SSL communications related errors." [1]

While https://groups.google.com/forum/#!topic/ngx-pagespeed-discuss/3cfPz35acRM started out mentioning that error code, the discussion went on to a different problem. I don't think disabling `InPlaceResourceOptimization` makes sense in your case.

Instead, maybe taking a close look at https://modpagespeed.com/doc/https_support#https_fetch may be helpful (especially "Configuring SSL Certificates").

[1] https://www.jefftk.com/p/serf-error-codes

**Comment by dom-de-monte** [comment]
Thank you very much.

**Comment by oschaaf** [comment]
Closing this issue, but please re-open if the problem if the problem persists after checking the SSL fetching related docs

**Comment by dom-de-monte** [comment]
I read that now HTTPS fetching is enabled by default so i added few options to exclude some scenario:

ModPagespeedFetchHttps enable,allow_self_signed,allow_unknown_certificate_authority,allow_certificate_not_yet_valid

After this i notice inside error_log following messages that continue to appear but what i notice more is that for some reason page speed try to connect in https to port 80 and not 443 ( if i understand correctly ).

How it could be ? Also i checked that url in order to verify that there are no rewrite rules that do stupid things like redirect from https to http and this is NOT case.

[Thu Jul 13 12:41:30.424469 2017] [pagespeed:warn] [pid 252281] [mod_pagespeed 1.12.34.2-0 @252281] Fetch timed out: https://www.XXXXXXXX.XXXXX/cache/jsn_air_pro/38e8788303e9f38cdaf60f93a81c5ae4.js?c2377ea5ef21c87c5a62d731a56d65d9 (connecting to:X.X.X.X:80) (1) waiting for 50 ms
[Thu Jul 13 12:41:30.425770 2017] [pagespeed:error] [pid 252281] [mod_pagespeed 1.12.34.2-0 @252281] Serf status 120171(APR does not understand this error code) polling for 1 threaded fetches for 0.05 seconds

**Comment by oschaaf** [comment]
Is the site running behind a proxy that terminates SSL?

**Comment by dom-de-monte** [comment]
Yes you are right. It's under CloudFlare. If it terminates SSL or not i do not know. There is a workaround or a particular setting to  consider for this scenario ?

**Comment by oschaaf** [comment]
In that case you may have to configure mod_pagespeed to respect the `X-Forwarded-Proto` request header (see the doc link for https fetching I posted above).
