### ISSUE TITLE
Installed and running...

### ISSUE THREAD

**Issue by Friends4U** [apache/incubator-pagespeed-mod#1595]
But not doing anything with images?
When I test, it's running and adding the header: 

200: OK
server: nginx
date: Sun, 16 Jul 2017 19:06:09 GMT
content-type: text/html; charset=UTF-8
content-length: 25802
connection: close
vary: Accept-Encoding, Accept-Encoding,User-Agent
x-powered-by: PHP/5.6.31
x-mod-pagespeed: 1.12.34.2-0
cache-control: max-age=0, no-cache, no-store, must-revalidate
pragma: no-cache
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-nginx-cache-status: EXPIRED
x-server-powered-by: Engintron

But my images are not getting rescaled...

**Comment by oschaaf** [comment]
Can you check the possible reasons listed at https://modpagespeed.com/doc/faq#not-rewriting ?
Closing this, but feel free to re-open if you can't resolve it with that.
