### ISSUE TITLE
PHP files Forbidden

### ISSUE THREAD

**Issue by Nirjonadda** [apache/incubator-pagespeed-mod#1598]
I am getting error from mod_pagespeed, Please let me know that how i can fixing on this issue?

Forbidden

You don't have permission to access /cometchat/A.cometchatcss.php.pagespeed.cf.Fralu-R33f.css on this server.

**Comment by Nirjonadda** [comment]
How to Disable /cometchat/cometchatcss.php from mod_pagespeed ?

**Comment by oschaaf** [comment]
You can use ModPagespeedDisallow, see https://modpagespeed.com/doc/restricting_urls#disallow

**Comment by Nirjonadda** [comment]
@oschaaf Then this correct ?

``
ModPagespeedDisallow "*/cometchat/cometchatcss.php"
``
