### ISSUE TITLE
Dublicate Content Error because of Url : PageSpeed=noscript 

### ISSUE THREAD

**Issue by oguzcicek** [apache/incubator-pagespeed-mod#1608]
Hello , 
I have the problem of duplicate Meta tag ,  duplicate Meta title because of 
html?PageSpeed=noscript  

Should i add this to robot.txt ? 
Disallow: /*?PageSpeed=noscript 

How can i handle this problem ?

**Comment by oschaaf** [comment]
Embedding the canonical url in the html may help:
https://support.google.com/webmasters/answer/139066?hl=en

Alternatively, you could disable the filters that depend on javascript to render the page correctly, or leave the filters enabled and drop support for clients that do not have javascript enabled. 
(See https://modpagespeed.com/doc/faq#noscript-redirect)
