### ISSUE TITLE
pagespeed adds unwanted index.html if my url ends with /

### ISSUE THREAD

**Issue by zylden** [apache/incubator-pagespeed-mod#1611]
Hi,
We make use of some frameworks which has some .htaccess rules in place. However, if we switch on pagespeed, it adds an   index.html to the back of the url which we dont want. 
for example:
if we call   www.domain.com/          what gets sent to the actual code is  www.domain.com/index.html

as soon as we disable pagespeed this issue is resolved.
Does anyone know why this is happening or how I can avoid it from being done?
thank you

**Comment by jmarantz** [comment]
I don't think it's mod_pagespeed doing this, and I'm not sure why disabling pagespeed would make a difference.  But could you try adding this command?

DirectoryIndex disabled

**Comment by jmarantz** [comment]
note also: this does not occur for http://modpagespeed.com/

please re-open if you have more detailed repro instructions or some reason to believe it's related to MPS.
