### ISSUE TITLE
Weird directories in cache directory

### ISSUE THREAD

**Issue by moritzschramm** [apache/incubator-pagespeed-mod#1617]
This isn't an issue, more like strange behaviour, but I don't know where I should ask this type of question.
I wanted to flush my pagespeed cache by creating a cache.flush file in the cache directory. Before I created the file, I looked inside some directories and found these directories:

- xxx.xxx.xxx.70                        
- https,3A
- 46.108.39.147                                     
- a*****.com
- ceair.com                                         
- opskins.com
- ctrip.com                                         
- proxy-checks.com
- ec2-52-36-223-78.us-west-2.compute.amazonaws.com
- fastmail.es
- free-dom-24.appspot.com                           
- shan-05.appspot.com
- google.com                                        
- z-h-e-n-117.appspot.com
- gtmcom.net                                        
- z-h-e-n-119.appspot.com
- hnair.com

Whereas xxx.xxx.xxx.70 and a***.com are just masked IP/domains (which I own). 
Now my question: Why does pagespeed create these directories? My website has no links to these sites. I used the standard configuration on an ubuntu 16.04 VPS with apache (2.4)

**Comment by oschaaf** [comment]
Entries like /pagespeed_cache/DOMAIN are created when pagespeed processes a request for DOMAIN (or actually hostname) and it needs to remember something about that url.
It looks like your webserver is listening and responding to all incoming hostnames, and it seems someone or something (bots) are performing requests to your server with the hostnames you are seeing in the file cache directory. 

To change that you could:
- Change Apache's configuration to only listen to hostnames that you want to serve (explicitly listing your site's domain name(s)).
- Modify ModPagespeed's configuration to explicitly list what you want to allow. For Example:

```
        ModPagespeedDisallow *
        ModPagespeedAllow *.yourdomain.com
```

Either of these options should fix the unexpected hostnames from showing up in the configured file cache directory.

**Comment by jmarantz** [comment]
Quick clarification.... On the"allow" line you probably want a suffix of "*"

        ModPagespeedAllow *.yourdomain.com*
