### ISSUE TITLE
# ModPagespeedFilters in_place_optimize_for_browser

### ISSUE THREAD

**Issue by deadjdona** [apache/incubator-pagespeed-mod#1623]
hai.

https://github.com/pagespeed/mod_pagespeed/blob/dba56f4b1338a12ba52cbb75da309ac8fb835eb5/install/modpagespeed.com-configuration-example.conf#L209

STR: uncomment it, save file and try _apache2ctl -t_

shouldn't it be # ModPagespeed**Enable**Filters in_place_optimize_for_browser?

**Comment by jmarantz** [comment]
Yes; exactly right.  Good catch.
