### ISSUE TITLE
Compressing image without rewrite it

### ISSUE THREAD

**Issue by ilham9649** [apache/incubator-pagespeed-mod#1625]
Hi, i want to compress image from my website using pagespeed, but i dont want my image url to be rewritten. Because people will know that my website using pagespeed and in my point of view it give too much info to potential attacker. Is there a way to make compress without rewrite it? Thank you

**Comment by oschaaf** [comment]
If you don't want to see any `.pagespeed.` urls in the output for any reason, [OptimizeForBandwidth](https://www.modpagespeed.com/doc/config_filters) mode is what you need.

It is also possible to [preserve urls](https://www.modpagespeed.com/doc/config_filters#preserveurls) for images, css, or js separately.
