### ISSUE TITLE
A bug when i visit my site

### ISSUE THREAD

**Issue by sundogya** [apache/incubator-pagespeed-mod#1631]
My site :http://www.sundogya.online 
Bug page: http://www.sundogya.online/admin
You can see that when i visit the bug page , there're some messy code before the image label .And when i fresh page it's gone.Fresh again ,it appears.How can i solve this problem ?
My server environment:
Ubuntu 16.04.3 LTS
Apache/2.4.18 (Ubuntu)
PHP 5.6.31-4

**Comment by oschaaf** [comment]
You could consider exluding the admin page(s):

```
ModPagespeedDisallow "http://www.sundogya.online/admin*"
```

https://www.modpagespeed.com/doc/restricting_urls

**Comment by sundogya** [comment]
Oh,it works ,thank you !

**Comment by oschaaf** [comment]
Great, closing!
