### ISSUE TITLE
Using S3 / Cloudfront as cache server

### ISSUE THREAD

**Issue by waghanza** [apache/incubator-pagespeed-mod#1637]
Hi,

I have setup `mod_pagespeed` to optimize my wesite content delivery .

I use **ModPagespeedRedisServer** to store all optimized content created by `mod_pagespeed` into a `redis`.

Could I use a S3 / Cloudfront to store / access it ?

Reards,

**Comment by oschaaf** [comment]
I think you can't really get around routing through Apache/mod_pagespeed to get to the optimized assets.
