### ISSUE TITLE
mod_pagespeed directives in htaccess are ignored when requesting a php file

### ISSUE THREAD

**Issue by Tarekajaj** [apache/incubator-pagespeed-mod#1639]
Hello,
First thank you for this amazing module,
I am facing an issue while adding directive to .htaccess related to mod page speed, they get completely ignored but only when requesting a php file, they work normally if the requested file is an html file.

the .htaccess only contains
```
<IfModule pagespeed_module>
  ModPagespeed off
</IfModule>
```

 the module is always loaded for .php files and is turned off for .html file
Please advise.
Regards,

**Comment by oschaaf** [comment]
Looks like this was reported earlier via https://github.com/pagespeed/mod_pagespeed/issues/963
Closing this as a duplicate
