### ISSUE TITLE
Fetching google fonts not working

### ISSUE THREAD

**Issue by waghanza** [apache/incubator-pagespeed-mod#1649]
Hello,

I have a website with an  `AWS issued certificate`.

I want to activate `inline_google_font_css` on *PageSpeed*.

When I allow unknow certificate, I have the expected result :

~~~
ModPagespeedFetchHttps enable,allow_unknown_certificate_authority
ModPagespeedEnableFilters inline_google_font_css
~~~

Regards,

**Comment by oschaaf** [comment]
I think you need to configure mod_pagespeed to inform it about where the CA certificates reside on the filesystem. See "Configuring SSL Certificates" over at https://www.modpagespeed.com/doc/https_support#https_fetch

**Comment by waghanza** [comment]
@oschaaf so quick ... ;-)

unfortunately my `SSL` configuration is not stored on the local machine
I am on a AWS envionment and AWS **best practices** imply having a `SSL` communication only between customer and load balancer (not on apaches behind load balancer)

**Comment by oschaaf** [comment]
mod_pagespeed's inline_google_font_css filter will contact Google Font CSS Api servers to pull resources for optimization purposes.

For mod_pagespeed to verify that is really talking to authentic Google Font CSS Api servers it needs to know where your distribution stores the CA certificates that it trusts.

**Comment by waghanza** [comment]
@oschaaf ok
