### ISSUE TITLE
PreserveURLs not working: preserve names / avoid merges

### ISSUE THREAD

**Issue by rafaelpatro** [apache/incubator-pagespeed-mod#1654]
Hi guys!
I'm trying to disable CSS and JS merges without success.
I'm using _coreFilters_ and want to **preserve URL names**.

My _pagespeed.conf_...
When setting this configuration JS and CSS are merged.

```html
<IfModule pagespeed_module>
    ModPagespeed on
    ModPagespeedInheritVHostConfig on
    AddOutputFilterByType MOD_PAGESPEED_OUTPUT_FILTER text/html
    ModPagespeedFileCachePath            "/var/cache/mod_pagespeed/"
    ModPagespeedLogDir "/var/log/pagespeed"
    ModPagespeedSslCertDirectory "/etc/ssl/certs"
    ModPagespeedFileCacheInodeLimit        500000
    ModPagespeedImageRecompressionQuality 80
    ModPagespeedJpegRecompressionQualityForSmallScreens 65
    ModPagespeedWebpRecompressionQuality 75
    ModPagespeedWebpRecompressionQualityForSmallScreens 65
    ModPagespeedStatisticsLogging on
    ModPagespeedMessageBufferSize 100000
    ModPagespeedDisableRewriteOnNoTransform off
    ModPagespeedEnableFilters resize_mobile_images
    ModPagespeedDisableFilters combine_css,combine_javascript
    ModPagespeedForceCaching on
    ModPagespeedInPlaceResourceOptimization on
    ModPagespeedJsPreserveURLs on
    ModPagespeedCssPreserveURLs on
</IfModule>
```

When I add the directives below CSS and JS filenames are extended.
```
    ModPagespeedMaxCombinedCssBytes 10
    ModPagespeedMaxCombinedJsBytes 10
```

I want to preserve names but avoid merges.

What am I doing wrong?

**Comment by oschaaf** [comment]
For disabling combining, you can use

```
ModPagespeedDisableFilters combine_css,combine_javascript
````

However, to me it sounds like you may want to configure the module to start out in the more conservative OptimizeForBandwidth mode:
https://www.modpagespeed.com/doc/optimize-for-bandwidth

When you start out with that, you can subsequently selectively enable any other filters that you need, and see if they fit your requirements.

**Comment by Lofesa** [comment]
@oschaaf the combine directives are disabled as show in the @rafaelpatro config.
Perhaps related to #1651 ?

**Comment by rafaelpatro** [comment]
Thanks @oschaaf optimizeForBandwidth works for me.
@Lofesa #1651 is exactly we faced. I was experiencing the same issue using ModPagespeedLoadFromFile and http2.
