### ISSUE TITLE
mod_pagespeed still messing with Cache-Control even after uninstall (Debian)

### ISSUE THREAD

**Issue by trashbytes** [apache/incubator-pagespeed-mod#1656]
See the title. I've uninstalled it (deb package) and removed its files from mods-enabled/available, deleted some cache folders, rebooted my server but it STILL messes with Cache Control somehow!

How do I stop this from happening?? I don't want my CSS being cached for a year! None of my visitors will ever get to see updates!

**Comment by oschaaf** [comment]
The idea with mod_pagespeed's cache extending is that it will add a hash to urls. This hash changes automatically when the underlying resource(s) change, busting any caches to prevent the problem you describe. This strategy enables using a one year TTL without the problem you describe.

Could you post the full headers of a css response here with a one-year TTL here? I wonder if there's still a trace of mod_pagespeed in there, or the expiry is set elsewhere. If there is a trace of mod_pagespeed in there, it would also be good to know which version of mod_pagespeed the sever was running.

**Comment by trashbytes** [comment]
It's actually 10 years and I think it's the nginx config which is the culprit here.. That's why I closed the issue just now until I further investigate it. My nginx config sets expires to max. 

It's strange, though, as I don't remember not being able to force a refresh using F5 before..

Usually when I edit CSS I manually refresh the page and it updates the cache, but not this time. Maybe it was like that before ( I've set the server up fairly recently and haven't had much time with it) but it's strange that I encounter it just after messing with mod_pagespeed..

**Comment by oschaaf** [comment]
mod_pagespeed doesn't use a 10 year cache-TTL [1], so we can probably rule it out.

[1] From https://tools.ietf.org/html/rfc7234
```
   Historically, HTTP required the Expires field-value to be no more
   than a year in the future.  While longer freshness lifetimes are no
   longer prohibited, extremely large values have been demonstrated to
   cause problems (e.g., clock overflows due to use of 32-bit integers
   for time values), and many caches will evict a response far sooner
   than that.
```

**Comment by trashbytes** [comment]
Alright, thank you! I was too quick with assumptions and littered the issue tracker, I'm deeply sorry!

Thanks for your time!
