### ISSUE TITLE
opening output file: Permission denied

### ISSUE THREAD

**Issue by balajikaliamoorthy** [apache/incubator-pagespeed-mod#1660]
Hi Team,

We have the Root access for the page speed folder and stats_log_global file. Please let us know  what causing this issue?

[Tue Oct 31 05:47:24.895894 2017] [pagespeed:error] [pid 29137:tid 139956081067776] [mod_pagespeed 1.12.34.2-0 @29137] /var/log/pagespeed/stats_log_global:0: **opening output file: Permission denied**

[Tue Oct 31 05:47:24.895935 2017] [pagespeed:error] [pid 29137:tid 139956081067776] [mod_pagespeed 1.12.34.2-0 @29137] **Error opening statistics lo**g file /var/log/pagespeed/stats_log_global. 
 
Thanks

**Comment by balajikaliamoorthy** [comment]
[Tue Oct 31 06:37:28.247568 2017] [pagespeed:error] [pid 29139:tid 139956064282368] [mod_pagespeed 1.12.34.2-0 @29139] **Failed to delete** file /var/log/pagespeed/stats_log_global: Permission denied

[Tue Oct 31 06:47:28.865612 2017] [pagespeed:error] [pid 29138:tid 139956106245888] [mod_pagespeed 1.12.34.2-0 @29138] **Failed to delete** file /var/log/pagespeed/stats_log_global: Permission denied

**Comment by jmarantz** [comment]
Depending on your distro, the apache child processes run as something like www-user or www-data.  Can you make sure the directories are writeable by that user?
