### ISSUE TITLE
Many messages "Need to check cache size against target"

### ISSUE THREAD

**Issue by bzica** [apache/incubator-pagespeed-mod#1677]
Hi all,

After I upgraded to mod-pagespeed-stable-1.12.34.2-0.x86_64, I'm seeing many of the following message:

    [Wed, 08 Nov 2017 18:10:51 GMT] [Info] [32613] Need to check cache size against target 102400000

Suddenly pagespeed stopped processing static files. At that moment I also saw messages like these:

    [Wed, 08 Nov 2017 17:41:36 GMT] [Error] [32358] AprMemCache::Get error: Internal error (20014) on key prop_page/http://extrastg.globoi.com/tv-e-lazer/teste-de-apelidofavor-nao-apagar-rv2-2-1083607.html?cache=false_BWSDgyJngd@Desktop@beacon_cohort

To make mod_pagespeed normal again I had to restart memcached and httpd services.

does anyone know what those messages mean?

**Comment by oschaaf** [comment]
The first (informational-level) message is emitted by a periodic process that trims the cache to its configured limits. The second one looks like https://github.com/pagespeed/ngx_pagespeed/issues/338, could you try if restarting memcached only resolves the problem? Pagespeed should recover by itself after that.

I hope that helps, for now I am closing this

**Comment by uhlhosting** [comment]
@oschaaf how the values of Need to check cache size against target are changed or enforced? What is a wise action to do when this message occurs intermitently.

**Comment by oschaaf** [comment]
`Need to check cache size against target 102400000` is informational, the best course of action is to ignore it, it is probably nothing to worry about.
