### ISSUE TITLE
cPanel mod_pagespeed error_log

### ISSUE THREAD

**Issue by YorhaX2P** [apache/incubator-pagespeed-mod#1684]
[Thu Nov 16 23:29:41.824448 2017] [pagespeed:error] [pid 19806:tid 139643202823936] [mod_pagespeed 1.11.33.4-0 @19806] Serf status 120171(APR does not understand this error code) polling for 1 threaded fetches for 0.05 seconds
[Thu Nov 16 23:29:46.839034 2017] [pagespeed:warn] [pid 19806:tid 139643202823936] [mod_pagespeed 1.11.33.4-0 @19806] Fetch timed out: https://unknown.com/css.php?css=uix,uix_dark,EXTRA&style=53&dir=LTR&d=1510861004 (connecting to:5.189.142.235:80) (1) waiting for 50 ms

I saw too many errors on error_logs more than 1K.

I've uninstalled EA4 = EasyApache for mod_pagespeed.

**Comment by oschaaf** [comment]
The mentioned css url looks dynamic based on the query parameters that go in. If that changes on nearly every request, and it is not cacheable, that could cause a lot of fetches originating from the module. In that case you could consider excluding them from optimization.
