### ISSUE TITLE
How can I encourage modpagespeed to honour origin maxage/expiry of CSS/JS ?

### ISSUE THREAD

**Issue by ktyak** [apache/incubator-pagespeed-mod#1685]
Hi,

With **modpagespeed off**

> [_]# **curl --head -L https://www.keithbrazil.com/wp-content/plugins/contact-form-7/includes/css/styles.css**
> HTTP/1.1 200 OK
> Date: Tue, 21 Nov 2017 22:17:43 GMT
> Server: Apache
> Last-Modified: Wed, 08 Nov 2017 04:34:23 GMT
> ETag: "646-55d7133b55a7e"
> Accept-Ranges: bytes
> Content-Length: 1606
> Vary: Accept-Encoding
> Cache-Control: max-age=2592000, public
> Expires: Thu, 21 Dec 2017 22:17:43 GMT
> Strict-Transport-Security: max-age=2592000
> Pragma: public
> X-Powered-By: W3 Total Cache/0.9.5.4
> Content-Type: text/css
> 
> [_]# **curl --head -L https://www.keithbrazil.com/wp-content/plugins/contact-form-7/includes/css/styles.css**
> HTTP/1.1 200 OK
> Date: Tue, 21 Nov 2017 22:17:47 GMT
> Server: Apache
> Last-Modified: Wed, 08 Nov 2017 04:34:23 GMT
> ETag: "646-55d7133b55a7e"
> Accept-Ranges: bytes
> Content-Length: 1606
> Vary: Accept-Encoding
> Cache-Control: max-age=2592000, public
> Expires: Thu, 21 Dec 2017 22:17:47 GMT
> Strict-Transport-Security: max-age=2592000
> Pragma: public
> X-Powered-By: W3 Total Cache/0.9.5.4
> Content-Type: text/css

**With modpagespeed on**

> [_]# **curl --head -L https://www.keithbrazil.com/wp-content/plugins/contact-form-7/includes/css/styles.css**
> HTTP/1.1 200 OK
> Date: Tue, 21 Nov 2017 22:01:14 GMT
> Server: Apache
> Expires: Thu, 21 Dec 2017 22:01:14 GMT
> Last-Modified: Wed, 08 Nov 2017 04:34:23 GMT
> Cache-Control: max-age=2592000, s-maxage=10
> X-Content-Type-Options: nosniff
> Vary: Accept-Encoding
> Content-Length: 1606
> Content-Type: text/css
> 
> [_]# **curl --head -L https://www.keithbrazil.com/wp-content/plugins/contact-form-7/includes/css/styles.css**
> HTTP/1.1 200 OK
> Date: Tue, 21 Nov 2017 22:01:18 GMT
> Server: Apache
> Content-Length: 1405
> X-Original-Content-Length: 1606
> Vary: Accept-Encoding
> Etag: W/"PSA-aj-2pQM9TJ6La"
> Expires: Tue, 21 Nov 2017 22:06:18 GMT
> Cache-Control: max-age=300
> X-Content-Type-Options: nosniff
> Content-Type: text/css
> 
> [_]# curl --head -L https://www.keithbrazil.com/wp-content/plugins/contact-form-7/includes/css/styles.css
> HTTP/1.1 200 OK
> Date: Tue, 21 Nov 2017 22:01:44 GMT
> Server: Apache
> Content-Length: 1405
> X-Original-Content-Length: 1606
> Vary: Accept-Encoding
> Etag: W/"PSA-aj-2pQM9TJ6La"
> Expires: Tue, 21 Nov 2017 22:06:44 GMT
> Cache-Control: max-age=300
> X-Content-Type-Options: nosniff
> Content-Type: text/css
> 

With modpagespeed on, having such a short max-age/expiry is causing the different page speed testing tools to claim that I'm not leveraging browser caching on [https://www.keithbrazil.com](https://www.keithbrazil.com) for a significant number of its CSS/JS resources. One of those resources was used in the curl examples above. 

If I turn modpagespeed off then I get a 100% score for Leverage Browser Caching on [https://www.keithbrazil.com](https://www.keithbrazil.com)

Is that right ?  should modpagespeed not be honouring the origin ttl? 

I have LoadFromFile on and have the following defined:
>   | mod_pagespeed on
>   | Filters:
>   | ah	Add Head
>   | cw	Collapse Whitespace
>   | cc	Combine Css
>   | jc	Combine Javascript
>   | gp	Convert Gif to Png
>   | jp	Convert Jpeg to Progressive
>   | jw	Convert Jpeg To Webp
>   | mc	Convert Meta Tags
>   | pj	Convert Png to Jpeg
>   | ws	When converting images to WebP, prefer lossless conversions
>   | db	Debug
>   | dj	Defer Javascript
>   | fc	Fallback Rewrite Css
>   | if	Flatten CSS Imports
>   | hw	Flushes html
>   | ci	Inline Css
>   | ii	Inline Images
>   | il	Inline @import to Link
>   | ji	Inline Javascript
>   | js	Jpeg Subsampling
>   | cj	Move Css Above Scripts
>   | cm	Move Css To Head
>   | pr	Prioritize Critical Css
>   | rj	Recompress Jpeg
>   | rp	Recompress Png
>   | rw	Recompress Webp
>   | rc	Remove Comments
>   | ri	Resize Images
>   | cf	Rewrite Css
>   | jm	Rewrite External Javascript
>   | jj	Rewrite Inline Javascript
>   | cu	Rewrite Style Attributes With Url
>   | is	Sprite Images
>   | cp	Strip Image Color Profiles
>   | md	Strip Image Meta Data
>   |  
>   | Options:
>   | EnableCachePurge (euci) True
>   | EnableRewriting (e) 1
>   | FileCacheInodeLimit (afcl) 500000
>   | FileCacheSizeKb (afc) 1000000
>   | InPlaceRewriteDeadlineMs (iprdm) 40
>   | LoadFromFileCacheTtlMs (lfct) 2592000000
>   | RunExperiment (fur) False
>   | StatisticsLogging (asle) True
>   |  
>   | #NumFlushes            0
>   | #EndDocument after     3449us
>   | #Total Parse duration  3303us
>   | #Total Render duration 63351us
>   | #Total Idle duration   146us
>   | No critical images detected.
>   | The following filters were disabled for this request:
>   | CriticalSelectorFilter: No critical selector info in cache

**Comment by jmarantz** [comment]
Use ModPagespeedLoadFromFileCacheTtlMs.  mod_pagespeed cannot see the HTTP cache-control headers you set at origin because it's not fetching the file via HTTP; it's bypassing the server and reading it from the disk.  So you need to specify the TTL explicitly.  See:

https://www.modpagespeed.com/doc/system#load_from_file_cache_ttl

**Comment by ktyak** [comment]
Hi, @jmarantz,

I am doing that ( i think ) :

The following is mentioned in the debug output (see above)
> | LoadFromFileCacheTtlMs (lfct) 2592000000

and this is in the **/etc/httpd/conf.d/pagespeed.conf**:
_ModPagespeedLoadFromFileCacheTtlMs 2592000000_

**Comment by ktyak** [comment]
Hi @jmarantz ,

As per @oschaaf 's advice in #1686 - installing **1.13.35.1-beta** did indeed resolve this problem. The problem was actually related to **_LoadFromFileCacheTtlMs is not honored (*after* first request)_** #1418 / #1552
 
Thank you 👍
