### ISSUE TITLE
ModPagespeedLoadFromFileCacheTtlMs 2592000000 being ignored? 

### ISSUE THREAD

**Issue by ktyak** [apache/incubator-pagespeed-mod#1686]
Hi, @jmarantz,

Ref your advice on:  #1685 

I am doing that already ( i think ) :

The following is mentioned in the debug output I provided

| LoadFromFileCacheTtlMs (lfct) 2592000000

and this is in the /etc/httpd/conf.d/pagespeed.conf:
ModPagespeedLoadFromFileCacheTtlMs 2592000000

It seems that modpagespeed is ignoring that value. 

[ Apologies for opening a new issue but I didn't know if your closing #1685  meant you wouldn't get to see my response on it to your advice. Sorry if I've broken some sort of netiquette. I'm unfamiliar with github as a platform. ]

**Comment by oschaaf** [comment]
What is the version of mod_pagespeed being used?

**Comment by ktyak** [comment]
X-Mod-Pagespeed: 1.12.34.2-0

**Comment by ktyak** [comment]
Although if I look at the pageadmin information it says this:

**Version: 14: on**

> Filters
> ah	Add Head
> cc	Combine Css
> jc	Combine Javascript
> gp	Convert Gif to Png
> jp	Convert Jpeg to Progressive
> jw	Convert Jpeg To Webp
> mc	Convert Meta Tags
> pj	Convert Png to Jpeg
> ws	When converting images to WebP, prefer lossless conversions
> ec	Cache Extend Css
> ei	Cache Extend Images
> es	Cache Extend Scripts
> fc	Fallback Rewrite Css 
> if	Flatten CSS Imports
> hw	Flushes html
> ci	Inline Css
> ii	Inline Images
> il	Inline @import to Link
> ji	Inline Javascript
> js	Jpeg Subsampling
> rj	Recompress Jpeg
> rp	Recompress Png
> rw	Recompress Webp
> ri	Resize Images
> cf	Rewrite Css
> jm	Rewrite External Javascript
> jj	Rewrite Inline Javascript
> cu	Rewrite Style Attributes With Url
> cp	Strip Image Color Profiles
> md	Strip Image Meta Data
> 
> Options
>   EnableCachePurge (euci)        True
>   EnableRewriting (e)            1
>   FileCacheInodeLimit (afcl)     500000
>   FileCachePath (afcp)           /var/cache/mod_pagespeed/
>   FileCacheSizeKb (afc)          1000000
>   LoadFromFileCacheTtlMs (lfct)  2592000000
>   LogDir (ald)                   /var/log/pagespeed
>   PurgeMethod (pm)               PURGE
>   SslCertDirectory (assld)       /etc/pki/tls/certs
>   SslCertFile (asslf)            /etc/pki/tls/cert.pem
>   StatisticsLogging (asle)       True
> 
> Domain Lawyer
>   http*://*.keithbrazil.com/wp-content/plugins/ Auth
>   http*://*.keithbrazil.com/wp-content/themes/ Auth
>   http*://*.keithbrazil.com/wp-content/uploads/ Auth

If that helps

**Comment by oschaaf** [comment]
I think you may be running into https://github.com/pagespeed/ngx_pagespeed/issues/1418
1.13.35.1-beta includes a fix

**Comment by ktyak** [comment]
Ok I'll see if I can get that installed then.

Thanks for your assistance.

**Comment by ktyak** [comment]
Hi,

Installing 1.13.35.1-beta did indeed resolve that specific problem.

Thank you 👍
