### ISSUE TITLE
deleting manually all cache files "prioritize_critical_css" causes Firefox to render only half of the page

### ISSUE THREAD

**Issue by biiissen** [apache/incubator-pagespeed-mod#1688]
Hello,

my very first post on GitHub. Don't know if it is the right way to ask questions, but... ;-)

Installed mod_pagespeed yesterday and was quite satisfied with the results.
Then I wanted to change some CSS, this wasn't shown in firefox, so wanted to clear pagespeed cache.
`touch /var/cache/mod_pagespeed/cache.flush` didn't seem to work (at least I thought so because the cache wasn't emptied), so I manually deleted the files and restarted apache.

Since that, when I look at my pages in firefox, it somethimes shows me the content correctly, sometimes it doesn't load the images and the layout looks bad too. It looks as if pieces of CSS were missing (only in firefox and edge, chrome works fine) disabling `prioritize_critical_css` results in the page being loaded correctly in firefox (and chrome of course) but still not in edge.
NB: Refreshing the page once helps, but when I click trough the site and come back to these pages the problem reoccurs.

my pagespeed.conf looks like this:
```
ModPagespeed on
ModPagespeedRewriteLevel PassThrough
ModPagespeedEnableFilters collapse_whitespace
ModPagespeedEnableFilters remove_comments
ModPagespeedEnableFilters rewrite_css
ModPagespeedEnableFilters combine_css
# ModPagespeedEnableFilters prioritize_critical_css
```
the rest of the values are untouched (default). BTW: Apache version is 2.4.10

Might it have to do, with me deleting the cache files? Is there a way to get pagespeed to regenerate them?

Anyway, trying to figure it out for some hours now, but can't find a clue online.
So thanks a lot for your help!

Regards, biiissen

**Comment by Lofesa** [comment]
Have you [configured](https://www.modpagespeed.com/doc/system) the cache directives?
Try to use `?PageSpeedFilters=+debug` with your url, this filter inject debug comments in the html code, perhaps you get any clue reading it (viewing the code of the page)

**Comment by oschaaf** [comment]
Also, to properly purge the cache, see
https://www.modpagespeed.com/doc/system#purge_cache


Otto

**Comment by biiissen** [comment]
Thanks a lot for your hints!
I'll try it and see what it gives me.

**Comment by biiissen** [comment]
Mea culpa, mea maxima cupla!
Sorry for wasting your time guys.
`<script **async** src="//code.jquery.com/jquery....js"></script>`
Turned out to be the problem.
Thanks for helping me anyway. Got the browser interface configured now. Read most of the documentation. Purged once more correctly. Removed the `async` and everything seems to work properly.
Will have to review the settings at some point, when I have more people visiting my site to optimize de last bit. For now pingdom.com says: Performance grad A/93 and faster than 90% of the tested sites. Not that bad to start with I would say.

And congratulations for this more than useful mod!

Thanks again!
Bye, biiissen
