### ISSUE TITLE
Pagespeed cannot be built using the way described in the docs

### ISSUE THREAD

**Issue by hmbusch** [apache/incubator-pagespeed-mod#1736]
The documentation for compiling pagespeed reads:

> To compile mod_pagespeed, run the commands below. You should to omit the AR arguments for latest-beta.
>  cd ~/mod_pagespeed/src
>  make AR.host=`pwd`/build/wrappers/ar.sh AR.target=`pwd`/build/wrappers/ar.sh BUILDTYPE=Release

Yet there is no folder 'src' and there is no 'ar.sh' in the whole project, even after completing all the previous steps. 

So how do I build pagespeed from source correctly?

**Comment by oschaaf** [comment]
https://www.modpagespeed.com/doc/build_mod_pagespeed_from_source#checkout states that for 1.12 and up the build procedure looks like:
```
  git clone -b latest-stable --recursive https://github.com/apache/incubator-pagespeed-mod.git
  cd mod_pagespeed
  python build/gyp_chromium --depth=.
  make BUILDTYPE=Release mod_pagespeed_test pagespeed_automatic_test
```

Hope that helps!

**Comment by hmbusch** [comment]
Thanks for the quick reply! On my machine, the _.so_ is not generated when I run 

_make BUILDTYPE=Release mod_pagespeed_test pagespeed_automatic_test_

However, it is generated when I just run

_make BUILDTYPE=Release_ (which is equal to _make BUILDTYPE=Release all_)

Perhaps it should be clarified in the manual that you need to run the make command with an additional _mod_pagespeed_.

_make BUILDTYPE=Release mod_pagespeed mod_pagespeed_test pagespeed_automatic_test_
