### ISSUE TITLE
Server crashing every hour or so returning a 500 error

### ISSUE THREAD

**Issue by onlymushu** [apache/incubator-pagespeed-mod#1742]
Hey there,

My server "4 GB Memory / 80 GB Disk / TOR1 - Ubuntu 16.04.2 x64" was working fine until I've installed the page speed module for Apache: https://www.digitalocean.com/community/tutorials/how-to-get-started-with-mod_pagespeed-with-apache-on-an-ubuntu-and-debian-cloud-server. I didn't install the Nginx module since my web server is apache.

I didn't change anything else, kept all the default settings, but since then, all the websites on the server crash every hour or so ... then when I restart Apache everything works for another hour. Am I missing something here? By crashing I mean, when I go to the website, it returns a 500 error.

I've installed Vesta CP on the server. What I find weird is that I can still access the cpanel when the other websites are down, which indicates that the server is not down itself but something that has to do with the virtual hosts.

Maybe one of you have had that problem before.

Thanks in advance.

**Comment by oschaaf** [comment]
Is there anything noteworthy in the server logs? Also, do you have the admin pages running? Those may offer diafnostic value too: https://www.modpagespeed.com/doc/admin

**Comment by onlymushu** [comment]
Thanks for mentioning the log, 
I just took a peak and indeed I'm getting a bunch of errors from page spead, mostly permission denies 

`[Mon Feb 05 14:40:06.652342 2018] [pagespeed:error] [pid 11277] [mod_pagespeed 1.12.34.2-0 @11277] Failed to mkdir /var/cache/mod_pagespeed/!clean!lock!: Permission denied
[Mon Feb 05 14:40:06.652535 2018] [pagespeed:error] [pid 11277] [mod_pagespeed 1.12.34.2-0 @11277] Failed to make directory /var/cache/mod_pagespeed/v3: Permission denied
[Mon Feb 05 14:40:06.652551 2018] [pagespeed:error] [pid 11277] [mod_pagespeed 1.12.34.2-0 @11277] Could not create directories for file /var/cache/mod_pagespeed/v3/mysite.com/http,3A/,2Fmysite.com/assets/js/jquery/ui/autocomple$
[Mon Feb 05 14:40:06.652567 2018] [pagespeed:error] [pid 11277] [mod_pagespeed 1.12.34.2-0 @11277] /var/cache/mod_pagespeed/v3/mysite.com/http,3A/,mysite.com/assets/js/jquery/ui/autocomplete.min.js,.tempCRNqkJ:0: opening temp $`

What should I do?

**Comment by oschaaf** [comment]
Permissions on /var/cache/mod_pagespeed need to be tweaked so that the module has read/write access to it. There are a couple of possible resolutions here:
https://github.com/apache/incubator-pagespeed-mod/issues/345

Closing this, but please re-open if you fail to solve it with that.
