### ISSUE TITLE
Hide or Remove X-Mod-Pagespeed and X-Page-Speed headers

### ISSUE THREAD

**Issue by ghost** [apache/incubator-pagespeed-mod#1755]
Hide or Remove X-Mod-Pagespeed and X-Page-Speed headers

i try all i cant hide that headers please help me .
i am using nginx and downstream varnish 5

**Comment by jmarantz** [comment]
See https://www.modpagespeed.com/doc/configuration#XHeaderValue
and https://github.com/apache/incubator-pagespeed-mod/issues/321

**Comment by ghost** [comment]
its only changing value i want complety hide mate.

**Comment by jmarantz** [comment]
There's a note in the doc for XHeaderValue:

Note: You cannot suppress the injection of this header. This is because it is used to prevent infinite loops and unnecessary rewrites when PageSpeed fetches resources from an origin that also uses PageSpeed.

**Comment by ghost** [comment]
understood. thank you
