### ISSUE TITLE
MapProxyDomain don't rewrite nor proxy pictures included in javascript

### ISSUE THREAD

**Issue by eldk** [apache/incubator-pagespeed-mod#1761]
Hello,

I've done some more test (cf https://groups.google.com/forum/#!topic/mod-pagespeed-discuss/DZD-mv6A3WE).

a - local pictures included in JS are rewrited and/or browser optimized (webp)
b - if included in javascript - here inline in one local html page to test, remote pictures, on a map proxy domain are not, even if there is no cache-control to prevent it (cf https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9.3)
c - same pictures/urls from a map proxy domain but included in one local HTML page are processed : rewrites then proxyed.

I have build a test-case page, I should give URL by mail.

Should you give some clue on the sources that may be concern ?

Thanks,
Eric

PS : as c is ok, I don't think it's a config matter.

**Comment by eldk** [comment]
Hello,

For case a, it seems like picture is delivered through IPRO (url is not rewritten with mod_pagespeed stuff - headers are the same as IPRO delivered pictures) : 

```
cache-control: max-age=31098734
content-length: 7440
content-type: image/webp
date: Sun, 01 Apr 2018 15:10:54 GMT
etag: W/"PSA-aj-HGZ0HD23a-"
expires: Wed, 27 Mar 2019 13:43:08 GMT
server: Apache/2.4.29
status: 200
vary: User-Agent,Save-Data
x-content-type-options: nosniff
x-original-content-length: 18195
```

Same picture when included in HTML :

```
cache-control: max-age=31536000
content-length: 7440
content-type: image/webp
date: Sun, 01 Apr 2018 15:10:54 GMT
etag: W/"0"
expires: Mon, 01 Apr 2019 14:48:50 GMT
last-modified: Sun, 01 Apr 2018 14:48:50 GMT
link: <https://domain.tld/IMG/picture.jpg>; rel="canonical"
server: Apache/2.4.29
status: 200
x-original-content-length: 18195
```
https://github.com/apache/incubator-pagespeed-mod/blob/c78d8e85622fe8d451ef29d21f89c68f21067fe6/pagespeed/automatic/system_tests/rel_canonical.sh

**Comment by eldk** [comment]
Headers of one picture to be proxyed through js inline in html - case b   : 

```
Accept-Ranges: bytes
Access-Control-Allow-Methods: GET, POST
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 43200
Cache-Control: max-age=43200
Connection: keep-alive
Content-Length: 24426
Content-Type: image/jpeg
Date: Sun, 01 Apr 2018 15:10:55 GMT
Expires: Mon, 02 Apr 2018 03:10:55 GMT
Last-Modified: Mon, 08 Jan 2018 15:04:22 GMT
Server: nginx
wl-original-content-type: image/jpeg
```

**Comment by eldk** [comment]
Result is the same when proxying https://www.gstatic.com/psa/static/1.gif

case b : KO
case c : OK

**Comment by eldk** [comment]
https://github.com/apache/incubator-pagespeed-mod/issues/1099
https://github.com/apache/incubator-pagespeed-mod/issues/1350

**Comment by eldk** [comment]
Hello,

I have modified /mod_pagespeed_example/proxy_external_resource.html - https://github.com/eldk/mod_pagespeed/commit/b2a5b4df975d1fe12772a1ff1eb71c059c2fde7a 

As described in my own test :

- local picture, added with one inline javascript is optimized through IPRO - see Etag and headers below.
- remote picture, from a map_proxy_domain, added with one inline javascript is not

Local picture response headers : 
```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=557
Connection: Keep-Alive
Content-Length: 98051
Content-Type: image/jpeg
Date: Fri, 27 Apr 2018 16:02:07 GMT
Etag: W/"PSA-aj-YsUBdV-i_6"
Expires: Fri, 27 Apr 2018 16:11:25 GMT
Keep-Alive: timeout=60, max=96
Server: Apache/2.4.26 (Unix) mod_fcgid/2.3.10-dev OpenSSL/1.1.0h
X-Content-Type-Options: nosniff
X-Extra-Header: 1
X-Original-Content-Length: 241260
```

The same remote picture is well map_proxyed when inserted in html.

**Comment by jmarantz** [comment]
This is expected behavior.   Pagespeed does not attempt to rewrite URLs embedded in JavaScript.

**Comment by eldk** [comment]
Hello,

So the solution, as IPRO will optimize local pictures included in javascript, is to proxy remote pictures using a third party tool, and include proxyed urls in javascript.

I have implemented it with openlayers, tiles (png or jpg pictures) ... are optimized, served on browser capability (WEBP ...) and memcached throught mod_pagespeed.

Thanks.

Eric
