### ISSUE TITLE
Cache is reset to 5 minutes, even with extend_cache

### ISSUE THREAD

**Issue by djixas** [apache/incubator-pagespeed-mod#1767]
Hello,

There is a weird issue on all sites, latest mod page speed version. From time to time, webp will revert from long expiration headers to 5 minutes

I do have set rules in htaccess webp, jpg etc +extend_cache + Force Caching, yet form time to time, my page speed score drops from 90 to 70 due to his:

Leverage browser caching for the following cacheable resources

> https://www.airyhair.com/ xx -350x350.jpg.pagespeed.ic.OMo14cyjTf.jpg (5 minutes)
> https://www.airyhair.com/ xx 350x350.jpg.pagespeed.ic.p34FxkL-Sn.jpg (5 minutes)
> https://www.airyhair.com/ xx s-curly.jpg.pagespeed.ic.tcWeei4fGg.jpg (5 minutes)
> https://www.airyhair.com/ xx raight_1.jpg.pagespeed.ic.Zz1VUCA0ki.jpg (5 minutes)
> https://www.airyhair.com/ xx yweave_1.jpg.pagespeed.ic.7TDVLgwyKx.jpg (5 minutes)

Clearing all page speed cache solves the issue, at least temporary. 

With page speed tool it gets even more random, first time it is always 79/100 but if you rerun, it is 90+, always

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.airyhair.com%2Ftape-in-hair-extensions.html&tab=mobile

Any ideas?

**Comment by oschaaf** [comment]
Sounds like normal module opration, but fortunately it is possible to get a steadier optimization state
for sites with little traffic, see: https://www.modpagespeed.com/doc/faq#varying-results

Also, you should probably bump FinderPropertiesCacheExpirationTimeMs:
https://www.modpagespeed.com/doc/config_filters#FinderPropertiesCacheExpirationTimeMs

(copied from https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mod-pagespeed-discuss/GU_cviYVLqI/LMkziyOnBwAJ)

**Comment by djixas** [comment]
Thank you. What would be your recommended ModPagespeedFinderPropertiesCacheExpirationTimeMs setting?
Is 86400000 okay? Around 24 hours

 As well as:

ModPagespeedFileCachePath
ModPagespeedFileCacheSizeKb          x
ModPagespeedFileCacheCleanIntervalMs x
ModPagespeedFileCacheInodeLimit      x

Disk usage is not a problem.

--

**EDIT: Tried and apache wont start?**

Apr 24 12:41:58 host.lotosus.com restartsrv_httpd[13436]: AH00526: Syntax error on line 30 of /usr/local/apache/conf/pagespeed.conf:
Apr 24 12:41:58 host.lotosus.com restartsrv_httpd[13436]: Invalid command 'ModPagespeedFinderPropertiesCacheExpirationTimeMs

**Comment by oschaaf** [comment]
A disk cache sized to around 3-4 times the size of the original site would be able to fit all the derived optimized resources. In terms of expiration timings I'd say that's up to you. 

With regard to ModPagespeedFinderPropertiesCacheExpirationTimeMs and httpd not starting up:
that makes me think that either you're not running the latest version, or the directive is specified in a wrong location (I think it only can be specified at the top or vhost level).

**Comment by djixas** [comment]
Thank you, again.

Figuring that one out.

ModPagespeedFinderPropertiesCacheExpirationTimeMs  default is 2h, right? Does it mean that every 2h it deletes cached page? Or ?

**Comment by oschaaf** [comment]
That means that the module will attempt to figure out what resources are
and aren't critical on-page
every 5 minutes. While it is figuring that out, you may see partially
optimized responses, correspoding
to the lower scores on PSI that you observed.

Otto
