### ISSUE TITLE
Redis DB index aliasing

### ISSUE THREAD

**Issue by jmarantz** [apache/incubator-pagespeed-mod#1771]
Looking at the code, I believe that if two different VirtualHosts in the same config construct redis caches that differ only DB-index then the first one will win, and the second db-index will be ignored.

n #1627 I think the db-index needs to be concatenated into the key used to lookup cache objects to be shared between multiple servers, in this block code in system_caches.cc:

```
    spec_signature =
        StrCat("r;", config->redis_server().ToString(), ";",
               IntegerToString(config->redis_reconnection_delay_ms()), ";",
               IntegerToString(config->redis_timeout_us()));
```

**Comment by oschaaf** [comment]
Ugh, looks like you are right, nice catch.
