### ISSUE TITLE
collapse_whitespace in <code>

### ISSUE THREAD

**Issue by Dreamsorcerer** [apache/incubator-pagespeed-mod#1772]
The documentation says:

> ..is normally ignored by the browser outside of tags like &lt;pre> and <textarea>, one can use CSS properties such as "white-space: pre" to make the browser preserve whitespace within a portion of the document..

It would be nice if collapse_whitespace would also ignore &lt;code> tags, as these are quite a common case for "white-space: pre".

Additionally, MDN says:

> The HTML &lt;code> element displays its contents styled in a fashion intended to indicate that the text is a short fragment of computer code.

Based on that description, it's plausible that a browser may choose to pay attention to whitespace, where it normally wouldn't (given that, for example, Python code without the whitespace would be invalid code).

So, skipping &lt;code> content would make this filter a fair bit safer to use.

**Comment by oschaaf** [comment]
Sounds reasonable to me,  and looks like it's easy to accomplish. It looks like it is just a matter of adding `<code>` to `kSensitiveTags`  here:

https://github.com/apache/incubator-pagespeed-mod/blob/master/pagespeed/kernel/html/collapse_whitespace_filter.cc#L39
