### ISSUE TITLE
How to use mod_pagespeed on multiple virtual host on same server

### ISSUE THREAD

**Issue by rahulthackkar** [apache/incubator-pagespeed-mod#1786]
Hello,
I am using one linux server as shared hosting for 50+ clients (Software as a Service), and I want to configure mod_pagespeed on my server with separate file cache location and clearing mechanism for each virtual host, and also I want to use only file cache, not memory cache.
I am trying since 4-5 days but I am not sure what configuration I need to do for this.
Can you please guide me with this.

**Comment by oschaaf** [comment]
I think https://www.modpagespeed.com/doc/system explains this best.
It's possible to configure distinct caches per vhost by specifying them at that level.
Hope that helps!
