### ISSUE TITLE
Invalid command 'ModPagespeedRedisServer'

### ISSUE THREAD

**Issue by windsofchange** [apache/incubator-pagespeed-mod#1789]
Hello,

Redis is configured and working fine in localhost. However defining in ModPagespeedRedisServer as localhost:6379 or 127.0.0.1:6379 results in apache crashing with 

`H00526: Syntax error on line 159 of /etc/apache2/conf.modules.d/456_pagespeed.conf:
restartsrv_httpd[91897]: Invalid command 'ModPagespeedRedisServer', perhaps misspelled or defined by a module not included in the server configuration
`
I have checked the code spelling, it's accurate. I've set the ::1 in redis.conf, but the pagespeed just will not connect to redis!

Any thought are welcome, TIA

**Comment by Lofesa** [comment]
Hi @windsofchange 
1.- You are using a IP6 notation in redis.conf and a IP4 notation in pagespeed.
2.- Are you sure the pagespeed module is loaded?
3.- Are you using a pagespeed version > 1.12.34.1?

**Comment by windsofchange** [comment]
Hi @Lofesa 

> 1.- You are using a IP6 notation in redis.conf and a IP4 notation in pagespeed.
redis.conf `bind 127.0.0.1 ::1`
pagespeed.conf `ModPagespeedRedisServer "localhost:6379"`

> 2.- Are you sure the pagespeed module is loaded?
Yes, works fine with ModPagespeedRedisServer commented out

> 3.- Are you using a pagespeed version > 1.12.34.1?
`version 1.11.33.4-0`

Ouch! my bad. it not supported on version version 1.11.33.4-0

Thanks for help.
