### ISSUE TITLE
Css_combine does't work even for the link provided in documentation

### ISSUE THREAD

**Issue by asennoussi** [apache/incubator-pagespeed-mod#1796]
Hi, 
On this page, you can find a link to a page supposed to demonstrate the css combination:
https://www.modpagespeed.com/doc/filter-css-combine
Unfortunately, even the link provided shows that it's not working. 
![image](https://user-images.githubusercontent.com/5939429/45252740-eaef2a00-b353-11e8-97ea-5402033a0dd3.png)

I would like to know if it's a known bug and if there is an ETA to fix that. 
Thanks a lot.

**Comment by oschaaf** [comment]
That is not a known issue.  Does the output improve after a couple of browser page reloads?

**Comment by asennoussi** [comment]
Hi, 
Even a force refresh did not combine the CSS files.

**Comment by oschaaf** [comment]
The ssl certs recently got updated, maybe that has something to do with it. In any case I'll take a look and update here

**Comment by asennoussi** [comment]
Alright, thank you, guys.

**Comment by oschaaf** [comment]
Fixed on both modpagespeed.com and ngxpagespeed.com:
the installed ssl cert was incomplete.

**Comment by oschaaf** [comment]
Oh, and @Sshuichi thanks for reporting!

**Comment by asennoussi** [comment]
No worries at all :-)
