### ISSUE TITLE
Empty CSS files not removed by combine_css

### ISSUE THREAD

**Issue by milux** [apache/incubator-pagespeed-mod#1799]
Hello everyone,
I just did my first experiments with mod_pagespeed, and so far it's working great!
However, it seems that there is one little bug, not catastrophic, yet annoying:
We're using Joomla with a custom template, which provides its own bootstrap css. However, Joomla always loads two files, `bootstrap-responsive.min.css` and `bootstrap-extended.css`. Removing them reliably altogether is difficult, so we use media overrides to make those links point to empty placeholder files instead.
I would expect the `combine_css` to remove the link elements pointing to these files from the page's HTML, but it doesn't. This causes PageSpeed Insights and other tools to rightfully complain about this waste of requests.
Is there anything we can do to get rid of the link elements for these style sheets?

**Comment by Lofesa** [comment]
Hi @milux 
Try this

ModPagespeedDisallow wildcard_spec

wildcar_spec can be the name of the files. You can use more than one directive.

**Comment by jmarantz** [comment]
Hi -- can you paste fragments of the HTML or CSS that references the bootstrap CSS files, both before & after mod_pagespeed runs?

If they are really empty I'd expect them to be inlined away, assuming the files are small and the *inline_css* filter is enabled.

**Comment by milux** [comment]
> Hi @milux
> Try this
> 
> ModPagespeedDisallow wildcard_spec
> 
> wildcar_spec can be the name of the files. You can use more than one directive.

Isn't that quite the opposite of the thing I was asking for? 😕

**Comment by milux** [comment]
> Hi -- can you paste fragments of the HTML or CSS that references the bootstrap CSS files, both before & after mod_pagespeed runs?

Sure! This is how the relevant section of the `<head></head>` looks with mod_pagespeed **turned off**:
```html
[...]
<link href="/components/com_jcomments/tpl/default/style.css?v=3002" rel="stylesheet" />
<link href="/templates/royalrangers2012/css/jui/bootstrap.min.css?3404d7d288ac1337c98ee29d164d0cf1" rel="stylesheet" />
<link href="/templates/royalrangers2012/css/jui/bootstrap-responsive.min.css?3404d7d288ac1337c98ee29d164d0cf1" rel="stylesheet" />
<link href="/templates/royalrangers2012/css/jui/bootstrap-extended.css?3404d7d288ac1337c98ee29d164d0cf1" rel="stylesheet" />
<link href="/templates/royalrangers2012/css/style.css?3404d7d288ac1337c98ee29d164d0cf1" rel="stylesheet" />
[...]
```
And this is how the relevant section of the `<head></head>` looks with mod_pagespeed:
```html
[...]
<style> /* lots of inlined stuff here... */ </style>
<link href="/templates/royalrangers2012/css/jui/bootstrap-responsive.min.css?3404d7d288ac1337c98ee29d164d0cf1" rel="stylesheet"/>
<link href="/templates/royalrangers2012/css/jui/bootstrap-extended.css?3404d7d288ac1337c98ee29d164d0cf1" rel="stylesheet"/>
<style> /* lots of inlined stuff yet again... */ </style>
[...]
```

> If they are really empty I'd expect them to be inlined away, assuming the files are small and the _inline_css_ filter is enabled.

I totally agree, but reality seems to be different...
We use CoreFilters plus these extra directives:
```
ModPagespeedEnableFilters prioritize_critical_css
ModPagespeedDisallow "*/piwik/*"
ModPagespeedAllow "*/piwik/piwik.js"
```

**Comment by jmarantz** [comment]
Can you try enabling the 'debug' filter and looking at the HTML again? That filter annotates some of the decisions mod_pagespeed by injecting HTML comments.

One thing that can block combination is media tags, though I didn't see any in the fragments you pasted.

**Comment by milux** [comment]
Did so, but for whatever weird reason the issue has disappeared. 😕 
First found out that I can fix this temporarily with `ModPagespeedAllow "*/bootstrap-*.css*"`, and now, with `debug` Filter enabled or disabled, the issue is gone.
Thanks for your help & inspiration, I will close this for now and let you know if this issue re-appears.
