### ISSUE TITLE
Completely remove mod_pagespeed for HTTPD (Centos 7.0)

### ISSUE THREAD

**Issue by cchamnab** [apache/incubator-pagespeed-mod#1804]
After install mod_pagespeed on my server, The web pages is displayed incorrectly. Is there a way to complete remove it from HTTPD ? I've tried to disable module but can't find in conf.module.d ? I wonder where this module is load from.

**Comment by jmarantz** [comment]
How did you install it? E.g. if by "yum" can't you uninstall by "yum"?

In any case, try

```
ModPagespeed unplugged
```

in your pagespeed.conf or .htaccess.
