### ISSUE TITLE
Mod_pagespeed on browser refresh shows different page source and errors

### ISSUE THREAD

**Issue by Jonras78** [apache/incubator-pagespeed-mod#1847]
I launched newest version of mod_pagespeed on my VPS several days ago.
Seems it working , websites has boost in speed.
Anyway , on Google Speed Insights i have vary speed results on Mobile - from 80 to 95 every test is different.

So i looked at mydomain.com/?PageSpeedFilters=+debug

1. One time i see like this in page source:

--CSS not inlined since it&#39;s bigger than 3072 bytes--><link href='https://fonts.googleapis.com/css?family=Arimo:400,700,400italic,700italic&amp;subset=latin,latin-ext'

(as seen below in my config i set it to 5000000 bytes ???)

--CSS rewrite failed: Parse error in https://www.mydomain.com/cb-builder/theme/robo-black/assets/css/style.css

<link href="https://www.mydomain.com/cb-builder/theme/robo-black/assets/css/style.css" rel="stylesheet" type="text/css"/>

--Summary computation status for CriticalSelectorFilter
Resource 0 https://www.mydomain.com/cb-builder/theme/robo-black/assets/css/bootstrap.min.3.3.6.css: Computed OK
Resource 1 https://www.mydomain.com/cb-builder/theme/robo-black/assets/css/normalize.3.0.3.css: Resource removed by another filter
Resource 2 https://www.mydomain.com/cb-builder/theme/robo-black/assets/css/style.css: Unrecoverable CSS parse error or resource contains closing style tag
Resource 3 https://www.mydomain.com/cb-builder/theme/robo-black/assets/css/font-awesome.min.css: Computed OK
Resource 4 https://www.mydomain.com/cb-builder/theme/robo-black/assets/smoothness/jquery-ui.css: Resource removed by another filter
Resource 5 https://www.mydomain.com/cb-builder/theme/robo-black/assets/css/back-to-top.css: Resource removed by another filter
Resource 6 https://www.mydomain.com/:22: Computed OK
Resource 7 https://www.mydomain.com/cb-builder/theme/robo-black/assets/css/jquery.share.css: Computed OK
Resource 8 https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700: Cannot create resource: either its domain is unauthorized and InlineUnauthorizedResources is not enabled, or it cannot be fetched (check the server logs)
Resource 9 https://fonts.googleapis.com/css?family=Arimo:400,700,400italic,700italic&amp;subset=latin,latin-ext: Cannot create resource: either its domain is unauthorized and InlineUnauthorizedResources is not enabled, or it cannot be fetched (check the server logs)

2. Second time after browser refresh i did not have any errors in source and all JS and CSS are inlined , combined and so on. After another refresh in several minutes i have again these or similar errors as mentioned in 1. As i noticed, errors are only on CSS , JS are ok.
And almost on every refresh i have different page source.
My js and css files are static. 

Is this normal ?

My mod_pagespeed config

ModPagespeed on

ModPagespeedStatistics on
ModPagespeedStatisticsLogging on
ModPagespeedLogDir /var/log/pagespeed
<Location /pagespeed_admin>
  Order allow,deny
  Allow from localhost
  Allow from 127.0.0.1
  SetHandler pagespeed_admin
</Location>

ModPagespeedFetchHttps enable
ModPagespeedSslCertDirectory /etc/pki/tls/certs
ModPagespeedSslCertFile /etc/pki/tls/cert.pem

ModPagespeedMemcachedServers localhost:11211 #(i had set 2048Mb on memcached for cache since i have 16Gb ram on vps)
ModPagespeedFileCacheSizeKb 2048000
ModPagespeedMaxCombinedCssBytes 5000000
ModPagespeedMaxCombinedJsBytes 5000000
ModPagespeedCssInlineMaxBytes 5000000
ModPagespeedJsInlineMaxBytes 5000000

ModPagespeedRespectXForwardedProto on

ModPagespeedDomain https://fonts.googleapis.com
ModPagespeedDomain https://www.mydomain.com
ModPagespeedDomain https://www.anotherdomain.com
ModPagespeedDomain https://www.anotherdomain2.com

ModPagespeedRewriteLevel CoreFilters

ModPagespeedEnableFilters prioritize_critical_css
ModPagespeedEnableFilters sprite_images
ModPagespeedEnableFilters rewrite_images
ModPagespeedEnableFilters recompress_png
ModPagespeedEnableFilters convert_png_to_jpeg,convert_jpeg_to_webp
ModPagespeedEnableFilters collapse_whitespace,remove_comments
ModPagespeedEnableFilters inline_import_to_link 
ModPagespeedEnableFilters flatten_css_imports 
ModPagespeedEnableFilters combine_css 
ModPagespeedEnableFilters rewrite_css 
ModPagespeedEnableFilters defer_javascript
ModPagespeedEnableFilters combine_javascript 
ModPagespeedEnableFilters rewrite_javascript 
ModPagespeedEnableFilters move_css_to_head 
ModPagespeedEnableFilters move_css_above_scripts 
ModPagespeedEnableFilters lazyload_images
ModPagespeedEnableFilters inline_google_font_css

ModPagespeedLoadFromFile "https://www.mydomain.com/" "/home/mydomain/public_html"
ModPagespeedLoadFromFile "https://www.anotherdomain.com/" "/home/anotherdomain/public_html"
ModPagespeedLoadFromFile "https://www.anotherdomain2.com/" "/home/anotherdomain2/public_html"
  

ModPagespeedLoadFromFileRuleMatch disallow .*

ModPagespeedLoadFromFileRuleMatch allow \.css$
ModPagespeedLoadFromFileRuleMatch allow \.jpe?g$
ModPagespeedLoadFromFileRuleMatch allow \.png$
ModPagespeedLoadFromFileRuleMatch allow \.gif$
ModPagespeedLoadFromFileRuleMatch allow \.js$
ModPagespeedLoadFromFileRuleMatch allow \.svg$

**Comment by oschaaf** [comment]
This was answered on the list, closing
