### ISSUE TITLE
Feature Request: Defer CSS for the current HTML page.

### ISSUE THREAD

**Issue by jblevins1991** [apache/incubator-pagespeed-mod#1874]
Just as in lighthouse and page insights suggests developers to defer css, I think that this is a great task for pagespeed.

**Comment by oschaaf** [comment]
Well, there is https://www.modpagespeed.com/doc/filter-prioritize-critical-css, does that look like what you need?

**Comment by jblevins1991** [comment]
Absolutely is! Thank you. I will play around with that filter.
