### ISSUE TITLE
1397BC53640DB551 key expired.

### ISSUE THREAD

**Issue by gmkey** [apache/incubator-pagespeed-mod#1875]
It appears that google has (for the second year running) forgot to update the apt signing key. Apparently this has been fixed for several repositories, but the pagespeed repos are still unsigned.

**Comment by gmkey** [comment]
GPG error: http://dl.google.com/linux/mod-pagespeed/deb stable Release: The following signatures were invalid: EXPKEYSIG 1397BC53640DB551 Google Inc. (Linux Packages Signing Authority) <linux-packages-keymaster@google.com>

The repository 'http://dl.google.com/linux/mod-pagespeed/deb stable Release' is not signed.

**Comment by IZSkiSurfer** [comment]
Same problem :(
