### ISSUE TITLE
Properly size images - What am I doing wrong?

### ISSUE THREAD

**Issue by conandrum** [apache/incubator-pagespeed-mod#1884]
I enabled everything to get pagespeed insights to stop compaining, 
but it is still compaining! http://134.209.247.233/

   ModPagespeedRewriteLevel CoreFilters
   ModPagespeedEnableFilters responsive_images
   ModPagespeedEnableFilters responsive_images_zoom
   ModPagespeedEnableFilters insert_image_dimensions

What am i doing wrong?

**Comment by oschaaf** [comment]
Well, like every other user-agent, Insights may need a few tests before it receives the fully optimized responses. 

ps; these type of questions are better suited for the [discussion list](https://groups.google.com/forum/#!forum/mod-pagespeed-discuss), the purpose of this tracker is actually  more for, well, actual bug/issue tracking :-).

**Comment by conandrum** [comment]
I get it, but I already tried starting a new topic there, and nothing seems to be posted.
Is there a process of admin review before my post shows up over there?

**Comment by oschaaf** [comment]
Yup; that is correct.
