### ISSUE TITLE
Lazyload filter not working

### ISSUE THREAD

**Issue by BarbzYHOOL** [apache/incubator-pagespeed-mod#1893]
Hello,

How can I verify if lazyload filter is working?

I have a page with tons of small images in display: none, and we must scroll the page + scroll inside the divs with overflow.

But when I check the page info, the media shows all the images are already loaded and when I scroll they seem already loaded (no micro loading).

So is it working? I guess not

**Comment by Lofesa** [comment]
Hi
The filter for lazyload fires an event on load that load all images. The reason for this is that in mobile devices is a cost to stablish a new connection but the payload is downloading bytes that maaybe never seen.
Try to use ModPagespeedLazyloadImagesAfterOnload off to disable this feature

**Comment by BarbzYHOOL** [comment]
I have set this to off too and same result. I have left default settings for everything else.

```
ModPagespeedEnableFilters lazyload_images
ModPagespeedLazyloadImagesAfterOnload off
```

In fact, the problem might also come from the fact that the page completely freezes after 2 seconds because it doesn't load my Jquery script (1.12). The browser says "the script is not responding, continue or abort" and if I continue it still pops again after few seconds

PS: Also I do'nt understand this `The filter for lazyload fires an event on load that load all images.`. It means it's not lazyloading at all if it loads all images o_0

**Comment by Lofesa** [comment]
Hi
I know your feel about this, but is stated in the [doc](https://www.modpagespeed.com/doc/filter-lazyload-images) "The lazyload_images filter defers loading of images until they become visible in the client's viewport **or the page's onload event fires**.".
You can use https://yousite.com/?PagespeedFilters=+debug and take a look in the html code. This inject debug messages, and maybe some talk about why don´t lazyload don´t work.

I don´t klnow too much about this fillter cause i don´t use it. Instead i use [lazysizes](https://github.com/aFarkas/lazysizes) script to do this.

EDIT:
Have you enabled critical image beaconing?

**Comment by BarbzYHOOL** [comment]
> or the page's onload event fires

Don't understand

`https://yousite.com/?PagespeedFilters=+debug` so I can change the conf of any site on the web? o_0

Thank you for the lazysizes script, I spent hours trying to find one, I'll try this one. I just thought that the apache mod would work much better and doesn't require me to specify each image one by one.

And no about critical image beaconing, what is that?

**Comment by Lofesa** [comment]
Hi
The onload is an event in the browser side, like on scroll or on click, and is fired when all elements (html,css,js,,,) on a page are loaded.
With these url parameters you can change the config of the pagespeed module for these request, you can enable or disabe filters, even disable pagespeed module (?PageSpeed=off) so you don´t need to change the conf file to see how a filter work in a request. 
A beacon is a javascript snipet that is injected in the page by pagespeed, this snipet return to the server info about the image (Is the image in the viewport? What size have the image rendered?...) . For example if you use ModPagespeedEnableFilters resize_rendered_image_dimensions the module must know what dimensions the image has when rendered to shrinks the image to these dimensions.

This can be enabled with:
ModPagespeedCriticalImagesBeaconEnabled true

**Comment by BarbzYHOOL** [comment]
> With these url parameters you can change the config of the pagespeed module for these request, you can enable or disabe filters, even disable pagespeed module (?PageSpeed=off) so you don´t need to change the conf file to see how a filter work in a request.

So anybody can change my settings o_0

I can't test anything for now because of this issue https://github.com/apache/incubator-pagespeed-mod/issues/1894 @Lofesa

**Comment by BarbzYHOOL** [comment]
ok that kinda works I guess, but apparently images in divs with display:none are not loaded by default (no need for mod_pagespeed)

and if you open up the page info/media it loads all images from the page (even display:none)


For the beacon thing, I guess it's by default in the by image filter right ?

**Comment by BarbzYHOOL** [comment]
I'll reopen if I see this bug again
