### ISSUE TITLE
Any filter crashes the site / not responding

### ISSUE THREAD

**Issue by BarbzYHOOL** [apache/incubator-pagespeed-mod#1894]
I'm on Linux, debian 9 in a Vm

I tried `?ModPagespeed=on&ModPagespeedFilters=` it works fine

As soon as I add any filter, the website stops responding after a few seconds (in client browser)

`?ModPagespeed=on&ModPagespeedFilters=+debug` = stuck
`?ModPagespeed=on&ModPagespeedFilters=+combine_css` = stuck

If I set CoreFilters, then the javascripts stop responding

So all in all it's 100% not working for me

**Comment by oschaaf** [comment]
Is there anything of interest in the apache logs?

**Comment by BarbzYHOOL** [comment]
No error, but I can't reproduce, I'll retry tomorrow, this is weird during 2 days it didn't work and now suddenly it works...

How can I put back default conf to retest?

**Comment by Lofesa** [comment]
Hi
I don´t know if this matter, but if you have Modpagespeed on in your conf file you don´t need to have it in the url params.
Any chance you post a url to test it?

**Comment by BarbzYHOOL** [comment]
I uninstalled the module and reinstalled and it works fine. I don't know what happened previously (tried on two browsers).

When I purged it, it didn't remove the cache in /var/cache though, could it be related?

**Comment by BarbzYHOOL** [comment]
I'll reopen if I see this bug again
