### ISSUE TITLE
Build all third party libraries using bazel

### ISSUE THREAD

**Issue by ashishk-1** [apache/incubator-pagespeed-mod#1909]
- [ ] apr
- [ ] aprutil
- [x] base64
- [ ] boringssl
- [x] brotli
- [ ] chromium
- [ ] closure
- [ ] closure_library
- [ ] css_parser
- [ ] domain_registry_provider
- [ ] gflags
- [ ] giflib
- [ ] google-sparsehash
- [ ] grpc
- [x] hiredis
- [ ] httpd
- [ ] httpd24
- [x] icu
- [x] jsoncpp
- [ ] libjpeg_turbo
- [x] libpng
- [x] libwebp
- [ ] mod_fcgid
- [ ] modp_b64
- [ ] nghttp2
- [ ] optipng
- [x] protobuf
- [x] rdestl
- [x] re2
- [ ] redis-crc
- [ ] serf
- [x] zlib

**Comment by ashishk-1** [comment]
Adding list of all pagespeed 3rd party libraries so to better track its progress.

**Comment by oschaaf** [comment]
Closing this, as all deps are either building or have been sanitized.
