### ISSUE TITLE
XMLHttpRequest got not rewritten

### ISSUE THREAD

**Issue by MrTschi** [apache/incubator-pagespeed-mod#1944]
Content (HTML) which is loaded with ajax request (Header x-requested-with:XMLHttpRequest) got not rewritten. Its plain HTML so why does this not work?

**Comment by Lofesa** [comment]
I think is for the same as the files loaded by javascript are not rewriten

**Comment by MrTschi** [comment]
Isn‘t it possible to whitelist a specific ajax request?

**Comment by Lofesa** [comment]
Hi @MrTschi 
I think no, as far as the ajax request is made in the client side so is out of the pagespeed scope.

**Comment by MrTschi** [comment]
@Lofesa please have a look here: https://bit.ly/2ZCrYc8
The main page html is loaded by AJAX. This content also includes images. These images got claimed in the pagespeed report as "images are not in a modern format" because mod_pagespeed hasn't improved the ajax request.

**Comment by Lofesa** [comment]
Hi @MrTschi 
No, the images are not improved by pagespeed cause are loaded by a javascript file, by this file `https://www.living-zone.de/web/cache/1567160279_1d1d56bc30bec72e62c1982a79ec358e.js`.
In other hand you had <picture> elements so you need to use UrlValuedAttribute to get these images optimized.

**Comment by MrTschi** [comment]
@Lofesa thanks for your help.
What still confuses me is the fact, that normal images got rewritten by pagespeed when requested as "XMLHttpRequest" but divs with style "background-image" with image-url will not get optimized:

**Simulate AJAX-Request with curl:**
```
$ curl --silent 'https://www.living-zone.de/widgets/emotion/index/emotionId/19/controllerName/index' -XGET -H 'X-Requested-With: XMLHttpRequest'
```
Result: Pagespeed does not rewrite background images
```
[...]
<div [...] style="background-image:url(https://www.living-zone.de/media/image/2c/4f/02/Gartebnmobel-topseller.jpg)">
[...]
```
But rewrites normal <img> images so it does something:
```
<img src="https://www.living-zone.de/media/image/84/f9/9a/xedelstahl_essgruppe_bilbao_8_160_220_schwarz_01_420x420.jpg.pagespeed.ic.bm9NefcOzU.jpg" [...]/>
```

**"Normal" page calls without the XMLHttpRequest header will work:**
```
$ curl --silent 'https://www.living-zone.de/widgets/emotion/index/emotionId/19/controllerName/index' -XGET |grep background-image
```
Result: Pagespeed will also rewrite background images:
```
[...]
<div [...] style="background-image:url(https://www.living-zone.de/media/image/7f/26/d6/xGartenmobel-Ausverkauf.jpg.pagespeed.ic.WKw6ZP9R7j.jpg)">
[...]
```

**Comment by Lofesa** [comment]
Hi @MrTschi 
This page ( https://www.living-zone.de/widgets/emotion/index/emotionId/19/controllerName/index) has 2 cache-control headers, 1 is cache-control: no-cache, private this prevent pagespeed to optimize the page. You need to investigate from where come this header and delete it.
I can see some strange behaviour in you web site.
In this page I can see a header related to pagespeed ( x-mod-pagespeed: 1.13.35.2-0 ) , this make me think is an apache web server, but in the server header I see nginx..... In the subresources (images,css files...) I can´t see any x-mod-pagespeed header nor x-pagespeed (this one is the header for pagespeed on a nginx server) but have etag header that are set by pagespeed (W/"0").
And last... I get these image rewrited
![Captura](https://user-images.githubusercontent.com/22342793/64487310-0f1c6a00-d239-11e9-813e-8ee77ff7dd21.PNG)

The question is Have you a nginx cache in front of an apache server? If that is the config then you have to configure a downstream cache ([doc](https://www.modpagespeed.com/doc/downstream-caching))
