### ISSUE TITLE
Running pagespeed with mpm_itk_module (each vhost as different user)

### ISSUE THREAD

**Issue by adrianTNT** [apache/incubator-pagespeed-mod#1963]
I am using `mpm_itk_module` that allows me to specify a different user for each apache vhost:

```
<VirtualHost *:80>
    ServerName www.example1.com
<IfModule mpm_itk_module>
    AssignUserId example1 example1
</IfModule>

<VirtualHost *:80>
    ServerName www.example2.com
<IfModule mpm_itk_module>
    AssignUserId example2 example2
</IfModule>
```

But when enabling `mod_pagespeed`, the cache folders (inside `/var/cache/mod_pagespeed`) are created as `apache:apache` and then it cannot write to them. 

It is like the initial pagespeed folders are created as default apache user, but later it tries to write as the individual vhost user(s) and fails.

If I make `/var/cache/mod_pagespeed` writable as 0777 then the folders are created by first user that writes cache (example1 or example2), but then the second user cannot write there anymore.

Is it uncommon to use different groups for these users ? Should I run all the virtual hosts as same group like `www` ?  `example1:www and example2:www` ? 

I can specify different cache folder for each vhost, but they still share some common folder(s) like `shm_metadata_cache` and permissions and ownership is still a problem.

Or maybe mod_pagespeed has an option for users setup ?!

**Comment by Lofesa** [comment]
Hi @adrianTNT 
As far as I know pagespeed creates folders and files with the user:group that runs the main apache/nginx process.
So are you runing the main apache as apache:apache? and then changing the userid in a vhost basis?
I think thi´s not usual, but... with what permission are folders created?
Maybe you can add all the users to the group apache and directories got read/write permissions to group.
Example:
Pagespeed creates /var/cache/mod_pagespeed with apache:apache rwxrw----
example1 belongs to groups example1 and apache
example2 belongs to groups example2 and apache

**Comment by adrianTNT** [comment]
Hi.
Yes, in main apache conf, the user and group is apache:apache, then example1 and example2 in the vhosts config.

Users example1 and example2 were already part of `apache` additional group.

Directories are created like this:
```
drwxr-xr-x 4 apache apache 80 Nov 26 20:49 /var/cache/mod_pagespeed
```
Inside it:
```
ls -lh /var/cache/mod_pagespeed
drwxr-xr-x 2 apache  apache  40 Nov 26 16:55 example1.com
drwxr-xr-x 2 apache  apache  40 Nov 26 16:55 example2.com
```
but it cannot write to them.
IF I made the main folder writable, e.g 0777 (just to test), it creates the shm_metadata_cache as belonging to ... the first user that attempted to create it, in this case `example2`:

```
ls -lh /var/cache/mod_pagespeed
drwxr-xr-x 2 apache  apache  40 Nov 26 16:55 example1.com
drwxr-xr-x 2 apache  apache  40 Nov 26 16:55 example2.com
drwxr-xr-x 3 example2 example2 60 Nov 26 16:55 shm_metadata_cache
```
"Great", now only example2 can write there, in what I think is a common folder (shm_metadata_cache). So I am a bit lost. 
The example1.com and example2.com directories cannot be written, they remain empty and it shows the write error in logs:

```
[pagespeed:error] [pid 4502] [mod_pagespeed 1.13.35.2-0 @4502] Could not create directories for file /var/cache/mod_pagespeed/example2.com/v3/example2.com/https,3A/,2Fwww.example2.com/thumbs/some_images.jpg,.temp
```

**Comment by adrianTNT** [comment]
I mentioned above that if main directory `/var/cache/mod_pagespeed` is missing, it is created as root:root, I was wrong, it was a bad temporary config, I edited that part. 
The rest should be valid.

**Comment by adrianTNT** [comment]
Even if I would run the vhosts as `example1:apache` and `example2:apache`, still the cache folders are created as `drwxr-xr-x` so the `apache` cannot write there, no ?!

**Comment by jmarantz** [comment]
Bottom line I don't think PageSpeed works well with ITK, at least for resource optimization. However there are some things you can do:

 - you can try using memcached or redis as your cache, and those may work better
 - you can still do HTML minification, as well as minification of inline CSS and JS, as those don't require a cache. Same goes for inserting DNS prefetch statements and possibly a few other optimizations.

Closing this for now. Please re-open if you have other questions.

**Comment by jmarantz** [comment]
Sorry, one more thing to try: you could try deploying a mod_pagespeed in a proxy layer in front of your ITK module. I don't know why I didn't think of that before. It may be possible to do that in your one apache instance; just disable ITK in mod_pagespeed, and add mod_proxy. Then have that proxy to a new port where ITK runs.

Does that seem reasonable?

**Comment by Lofesa** [comment]
Hi @adrianTNT 
The main problem is `drwxr-xr-x`.
I don´t know what linux distro you use but in red hat or centos there is a file called `/etc/tmpfiles.conf`
In this file you can "create" temporary directories like /ramdisk/mod_pagespeed with the permissions you choose. The goal must be create directories with `drwxrwxr-x` and all user belongs to group apache

**Comment by adrianTNT** [comment]
@Lofesa you mean it is like a template for future files that are created ? I can specify permission codes in advance ? 
I am on Centos 7

> Sorry, one more thing to try: you could try deploying a mod_pagespeed in a proxy layer in front of your ITK module. I don't know why I didn't think of that before. It may be possible to do that in your one apache instance; just disable ITK in mod_pagespeed, and add mod_proxy. Then have that proxy to a new port where ITK runs.
> 
> Does that seem reasonable?

That would probably work, but I can't do it with this setup, it would cause some unnecessary complications. 
I was about to optimize resources on this server and use a proxy server for some of the sites, I wanted the reverse proxy servers to have the resources already optimized so they don't need to work much :) 

Now I am trying running apache normally as apache:apache because these permission issues with different apache users scared me :)

**Comment by Lofesa** [comment]
Hi @adrianTNT 
Yes. You can create directories or files at startup, for example in a ram disk (`/var/ru`n in centos).
You can see more [here](https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html)
