### ISSUE TITLE
Only serves Brotli when `Accept-Encoding` header demands it exclusively

### ISSUE THREAD

**Issue by tomayac** [apache/incubator-pagespeed-mod#1975]
Chrome sends the following `Accept-Encoding` header: `accept-encoding: gzip, deflate, br`. This leads mod-pagespeed to serve `gzip` instead of `br`:

```bash
$ curl -I -s -H 'Accept-Encoding: gzip, deflate, br' https://blog.tomayac.com/css/main.css | grep content-encoding
content-encoding: gzip
```
However, when Brotli is requested *exclusively*, then `br` is correctly returned: 

```bash
$ curl -I -s -H 'Accept-Encoding: br' https://blog.tomayac.com/css/main.css | grep content-encoding
content-encoding: br
```

Brotli should probably always be favored if the server *and* the client support it, even if for compatibility reasons other additional encoding formats are requested by the client.

**Comment by jmarantz** [comment]
PageSpeed does not currently have any support built in for automatically serving Brotli (although I agree that it should). https://github.com/apache/incubator-pagespeed-mod/issues/1148 tracks this.

There must be something else in your server-stack that's converting to Brotli (eg mod_brotli?).

**Comment by tomayac** [comment]
Thanks for the reply! I indeed have mod_brotli installed. What confuses me is that if I request https://blog.tomayac.com/static/sun.svg with `accept-encoding: gzip, deflate, br`, the server returns `br`. It may well be something with my server configuration, but I thought it was mod-pagespeed interfering.

If mod-pagespeed knows the server supports Brotli, could it then maybe rewrite the request header to remove `deflate` and `gzip` for commonly compressable resources?

**Comment by jmarantz** [comment]
That seems feasible for you to add your apache configuration without pagespeed? I know I've used some apache conf magic to do these sorts of conditional transformations, but it's been a while so I don't recall the syntax.

Just watch your server CPU time because at least in the past, Brotli was more time-consuming to compress on-the-fly than gzip. It might have improved since I looked carefully.

The reason I thought it would make sense for PageSpeed to support it directly is that PageSpeed could cache the compressed versions and serve those without re-compressing on the fly.

**Comment by Lofesa** [comment]
@tomayac  What compression level have you enebled in the pagespedd config?
If you enable pagespeed compression then pagespeed stored the optimized resource gziped and serve it as gzip. By default pagespeed has enabled the compression to level 9, try to disable it:
ModPagespeedHttpCacheCompressionLevel 0

**Comment by tomayac** [comment]
Sorry for the radio silence, and thanks(!) for the answers!

> ModPagespeedHttpCacheCompressionLevel 0

Effectively disabling gzip with the above setting together with enabling the mod_brotli module on the server did the trick. Now everything is Brotli-compressed. 🎉
