### ISSUE TITLE
my website stops working when installing PageSpeed Insights module apache

### ISSUE THREAD

**Issue by informaticamayes** [apache/incubator-pagespeed-mod#1978]
my website stops working when installing PageSpeed Insights module apache

**Comment by informaticamayes** [comment]
It does not generate any error, it just stops working all the pages hosted in plesk

**Comment by Lofesa** [comment]
Some link to test?

**Comment by oschaaf** [comment]
Maybe ask over at https://support.plesk.com/hc/en-us?

**Comment by oschaaf** [comment]
Closing this, as I don't think anyone is going to look into this. 
In an attempt to at least be a little helpful: on Windows, I know from experience that Plesk locks down on security post install, which breaks some IIS modules when their install in not tuned to mind Plesk (from the top of my head, the plesk configs needed some sort of whitelisting for certain files and directories there). Possibly something similar is what is going on here.
