### ISSUE TITLE
Combine Css and javascript not combining all js/css files.

### ISSUE THREAD

**Issue by sathyamahes** [apache/incubator-pagespeed-mod#1984]
Hi,
I am new to this page speed configuration setup.
I have enabled pagespeed on the pagespeed.conf file inside the apache server. And enabled the following filters.
`ModPagespeedEnableFilters combine_javascript,combine_css`
I am able to see some of my CSS and js file are combining but rest all are loading individually.
Is there any additional config I need to do? And I need to know why certain files alone get affect and  rest all not?

**Combine css:**
![combine_css](https://user-images.githubusercontent.com/30695458/74829356-e1cefe80-5336-11ea-9e28-c110bbeab902.png)

**Combine js:**
![defer_js](https://user-images.githubusercontent.com/30695458/74829388-f1e6de00-5336-11ea-906f-2cf13d7437fa.png)

**Comment by oschaaf** [comment]
It might be worth reading up over at the [FAQ](https://www.modpagespeed.com/doc/faq).
