### ISSUE TITLE
Uncacheable content, preventing rewriting of...

### ISSUE THREAD

**Issue by nicolauria** [apache/incubator-pagespeed-mod#1986]
I am running an AWS Lightsail Bitnami instance. It comes configured with pagespeed. Several filters are already enabled: 

inline_images,combine_css,combine_javascript,rewrite_javascript,rewrite_css,inline_css,lazyload_images

My css and js files are not being combined and lazy_loading images is not working as well. When I append '?PageSpeedFilters= debug' to my url I get the following:

Uncacheable content, preventing rewriting of http://18.237.178.106/wp-includes/js/wp-embed.min.js?ver=5.3.2

I have enabled caching on the instance in '/opt/bitnami/apps/wordpress/conf/htaccess.conf' and my files appear to be cached. Do you have any suggestions on how I can resolve this problem?

This is the url I am testing: http://18.237.178.106

**Comment by Lofesa** [comment]
Hi... This issue is not related to any cache.
Uncacheable content is related to the http headers cache-control, this header must permit the asset be cached brownser side.
Pagespeed need to work these resources referenced in the html code get public cacheable, some like
cache-control: max-age=604800,public
Pagespeed need some hits to work, if you put a cache in front of the web (like varnish), this cache stores the 1st hit, and serves it witout fechting the background server, so resources get not optimized. This kind of thing need other config you can see here: https://www.modpagespeed.com/doc/downstream-caching.

When you says you hable enabled caching in the htaccess.conf what do you mean?

EDIT: I´m unable to get debug messages when /PaageSpeed=+debug is used.

**Comment by nicolauria** [comment]
Hello Lofesa,

Thank you for your response. When I say I have enabled caching I mean that I added the following code to my '/opt/bitnami/apps/wordpress/conf/htaccess.conf' file:
```
# 1 YEAR
<FilesMatch "\.(flv|ico|pdf|avi|mov|ppt|doc|mp3|wmv|wav|woff|woff2|ttf|eot)$">
Header set Cache-Control "max-age=31536000, public"
</FilesMatch>

# 1 WEEK
<FilesMatch "\.(jpg|jpeg|png|gif|swf)$">
Header set Cache-Control "max-age=604800, public"
</FilesMatch>

# 1 WEEK
<FilesMatch "\.(txt|xml|js|css)$">
Header set Cache-Control "max-age=604800, public"
</FilesMatch>
```
I am not using Varnish. If you visit this url: [http://52.40.93.103](http://52.40.93.103) and inspect the network tab and select a file you should see that caching headers have been enabled. Any additional help you can provide as to why I am encountering this error is appreciated.

**Comment by Lofesa** [comment]
Hi @nicolauria 
Where have you set the config parameters?
Seems like the assets don´t go through the pagespeed `module.
Can you post your config? Anonimized, off course

EDIT: What rewrite rules have you set?

EDIT2: I found you have set the header `Vary: Cookie`, this header prevent caching

**Comment by nicolauria** [comment]
Hi Lofesa,

The only config parameters I have set is the caching in '/opt/bitnami/apps/wordpress/conf/htaccess.conf'. I have not changed anything else. The pagespeed module is definitely enabled so I'm not sure why assets wouldn't be served by pagespeed. Is there a way to verify this? You asked me to post my config. Config for which file?

By rewrite rules do you mean filters? These are the pagespeed filters I have enabled:

ModPagespeedEnableFilters inline_images,combine_css,combine_javascript,rewrite_javascript,rewrite_css,inline_css,fallback_rewrite_css_urls

Regarding the `Vary: Cookie` header. How do I change this?

Thank you again for your help.

**Comment by Lofesa** [comment]
Hi
Apache uses a main cnfig file, usually called http.conf. In this file Virtual domains, directories and other stuff is configured. Other file is used too, .htaccess. The main config file may be located in a /etc suddir, the exact location depend on what pakcage are you using, The .htaccess is in the root directory of the web server, where the files served start,
headers can be set on both files, an rewrite rules too. Apache has rewrite rules like:

```
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
```
These rules I have posted serve a static file or directory or run the index.php file.

**Comment by nicolauria** [comment]
Thank you Lofesa. I'm aware of the httpd.conf and the .htaccess file. This AWS Lightsail instance uses bitnami which means the configuration for the .htaccess file is actually in:

'/opt/bitnami/apps/wordpress/conf/htaccess.conf'

I was able to enable caching using this file but the 'Uncacheable content, preventing rewriting of...' error persists.

**Comment by Lofesa** [comment]
And in these file, you can´t see any directive like
`Header set vary: cookie`
Don´t have any file httpd.conf?
I found these issues in bitnami comunity:
1 not solved, with the same issue you have
https://community.bitnami.com/t/pagespeed-not-processing-anything/50751/3
1 to unset the header
https://community.bitnami.com/t/how-to-disable-vary-header/52899/4

But I think that the header is set in some config file, so comment the directive, you don´t need to unset it in a later step.
And have found this document
https://docs.bitnami.com/bch/apps/wordpress/get-started/understand-config/
about apache config files in bitnami and thi, how to config pagespeed in bitnami
https://docs.bitnami.com/general/apps/wordpress//administration/use-pagespeed/

I don´t have any knowledge about how bitnami works or is configured, but reading the 1st link seems that you are not the only with the same probled, maybe searching in the bitnami comunity

**Comment by nicolauria** [comment]
Thank you so much Lofesa. The second link your provided which details how to disable the the Vary Header solved the problem for me. My js and css files are now being combined. For anyone else who might read this, I also had to remove the ids from my link tags which were preventing the combining of css files. Added to functions.php:

```
function remove_style_id($link) {
  return preg_replace("/id='.*-css'/", "", $link);
}
add_filter('style_loader_tag', 'remove_style_id');
```

**Comment by Lofesa** [comment]
Hi 
Glad to see you have solved the issue in some way.
For the css id´s maybe you need to put other pagespeed directive:
[ModPagespeedPermitIdsForCssCombining](https://www.modpagespeed.com/doc/filter-css-combine#permit-ids-for-css-combining)

**Comment by nicolauria** [comment]
That's definitely a better way of handling the css combining. Thank you Lofesa.

**Comment by nicolauria** [comment]
Sorry to bother you again Lofesa. Now I am running into another issue regarding pagespeed and ssl. I read this post: [https://github.com/apache/incubator-pagespeed-mod/issues/1897](https://github.com/apache/incubator-pagespeed-mod/issues/1897) but was unable to resolve the problem. This is the error I am getting: '4xx status code, preventing rewriting of...'. I've tried adding the following directives to my pagespeed.conf file:
```
ModPagespeedFetchHttps enable
ModPagespeedMapOriginDomain "http://domain.com" "https://www.domain.com"
ModPagespeedSslCertDirectory /etc/letsencrypt/live/domain.com
ModPagespeedSslCertFile cert.pem
```
with 'domain' replaced with the appropriate domain. This did not resolve the issue. Do you have any suggestions?

**Comment by Lofesa** [comment]
Not bother at all.
These directives are wrong:
```
ModPagespeedSslCertDirectory /etc/letsencrypt/live/domain.com
ModPagespeedSslCertFile cert.pem
```
The certificates you need here are NOT the let´s encrypt certificates you are using in your site.
Thing in a browser, when you take a look at the certificates you can see a lot of "upper" level certificates, these are from the CA sites. Rigth?
These CA certificates are needed for validate the let´s encrypt cert that you use in your site. Rigth?
Well, pagespeed module uses a headless browser (called Serf, you can see this word in your logs as a User agent text) so these browser need to have CA certificates to validate the let`s encrypt.
I can see you use both directives, so I may think you use a redhat-centos linux distro, so the rigth directives are:

```
ModPagespeedSslCertDirectory /etc/pki/tls/certs
ModPagespeedSslCertFile /etc/pki/tls/cert.pem
```
If the site respond to https request you don´t need to rewrite the domain.
For SEO purposes you need some  apache rewrite rules to redirect http to https, some like:

```
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R=301,L] 
```
In this way your site only do https request

**Comment by nicolauria** [comment]
The instance is running a linux/unix ubuntu 16.04 distro. I don't see a `/etc/pki` folder. I do see a `/etc/ssl/certs` directory with a `ca-certificates.crt` file. I've tried using this folder and file in my directives but no luck. Also, should I be adding these directives to my `.htaccess` file:
```
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R=301,L]
```
I can also provide you ssh access to one of our test instances if you think that would help locate where the correct cert folder/file is.

**Comment by Lofesa** [comment]
Hi
If you have `/etc/ssl/certs`  your distro is a debian/ubuntu, and you only need to set 
`pagespeed SslCertDirectory etc/ssl/certs`
don´t need to set the file. See the [doc](https://pagespeed.apache.org/doc/https_support#configuring_ssl_certificates)

Yes, you need to set the apache rewite rules in .htacces. these rewrite rules make you go to the https version of the site if you put http in the url bar, so you don´t 2 web versions, the http and the https.
Check if you have any `RewriteEngine On` directive in your .htacces and then add these rules or make a new section if don´t have any,

Ah! and make wordpress htttps ready.

**Comment by nicolauria** [comment]
Thank you Lofesa. I should have read the documentation more carefully. That resolved the issue.
