### ISSUE TITLE
NO_FCP for mod_pagespeed

### ISSUE THREAD

**Issue by vardan-karapetyan** [apache/incubator-pagespeed-mod#1997]
I installed mod_pagespeed on Apache, everything works fine. The site works quickly without problems 100-150 ms. But when I try to check the speed of the site - it gives me "Lighthouse returned error: NO_FCP.". But when I turn off mod_pagespeed everything works https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fsolidwatches.ru%2F&tab=mobile.
This my filters: ModPagespeedRewriteLevel PassThrough
ModPagespeedEnableFilters collapse_whitespace,remove_comments,inline_css,inline_javascript,rewrite_css,rewrite_javascript,combine_css,combine_javascript.
But even with the filters turned off, I get the same error when only ModPagespeed on
CentOS 7
Apache 2.4.6
PHP 7.2
Pagespeed 1.13.35.2-0

**Comment by oschaaf** [comment]
I feel this question doesn't really belong here, as it seems specific to Lighthouse.
Maybe there's a reason listed in here:
https://stackoverflow.com/questions/55826735/how-to-fix-lighthouse-returned-error-no-fcp-when-running-google-page-speed-t

**Comment by vardan-karapetyan** [comment]
> I feel this question doesn't really belong here, as it seems specific to Lighthouse.
> Maybe there's a reason listed in here:
> https://stackoverflow.com/questions/55826735/how-to-fix-lighthouse-returned-error-no-fcp-when-running-google-page-speed-t

I read this question and not a single answer helped me. I think that this is somehow connected with mod_pagespeed, because after turning it off, the error disappears immediately, immediately after switching on it appears.

**Comment by Lofesa** [comment]
@vardan-karapetyan When Pagespeed is on aka url are rewrited your site returns intermitent 404 for resources, getting a blank page for a big amount of secons, this delay maybe considered by Ligthouse as a non response.
The NO_FCP is when Ligthouse don´t receive nothing in an amount of time...
![Captura](https://user-images.githubusercontent.com/22342793/85285854-eac10f80-b491-11ea-91c4-443dcd364e2e.jpg)

But when all resources get a 200, the PSI works w/ bad scores

![Captura](https://user-images.githubusercontent.com/22342793/85286244-90747e80-b492-11ea-81e4-3585ec3f641a.jpg)

So, I think, you need to assure your site ever returns a 200 in all resources, and make it run as faster you can

**Comment by vardan-karapetyan** [comment]
> @vardan-karapetyan When Pagespeed is on aka url are rewrited your site returns intermitent 404 for resources, getting a blank page for a big amount of secons, this delay maybe considered by Ligthouse as a non response.
> The NO_FCP is when Ligthouse don´t receive nothing in an amount of time...
> ![Captura](https://user-images.githubusercontent.com/22342793/85285854-eac10f80-b491-11ea-91c4-443dcd364e2e.jpg)
> 
> But when all resources get a 200, the PSI works w/ bad scores
> 
> ![Captura](https://user-images.githubusercontent.com/22342793/85286244-90747e80-b492-11ea-81e4-3585ec3f641a.jpg)
> 
> So, I think, you need to assure your site ever returns a 200 in all resources, and make it run as faster you can

but my site is loading normally and returns 200 for everything. What should I do in this case?
![1](https://user-images.githubusercontent.com/67158195/85288569-9ec89780-b49e-11ea-8694-5552623e19f4.jpg)
![2](https://user-images.githubusercontent.com/67158195/85288576-9ff9c480-b49e-11ea-9cd5-a798210655fc.jpg)
In all browsers, with both enabled pagespeed and disabled, everything loads well and returns 200
