### ISSUE TITLE
Safari 14 will support webp

### ISSUE THREAD

**Issue by eldk** [apache/incubator-pagespeed-mod#2038]
Hello,

It seems like Safari 14 will support webp.

The Safari 14 Beta release note :

https://developer.apple.com/documentation/safari-release-notes/safari-14-beta-release-notes

```
Media
New Features
Added WebP image support.
```

Thanks,

Eric

**Comment by Lofesa** [comment]
As far as I can see, Safari UA is not blacklisted for webp, so if the browser send image/webp as a navigational header, pagespeed will send the webp image

**Comment by Poseidonas** [comment]
> Hello,
> 
> It seems like Safari 14 will support webp.
> 
> The Safari 14 Beta release note :
> 
> https://developer.apple.com/documentation/safari-release-notes/safari-14-beta-release-notes
> 
> ```
> Media
> New Features
> Added WebP image support.
> ```
> 
> Thanks,
> 
> Eric

Great news! 

@Lofesa  The pagespeed can server webp to any client but the problem is that the Safari cannot read webp. In other words you have to enable the UserAgent Append to ensure that your users can see your webp content successfully --as jpeg ofc and NOT as webp.

**Comment by Lofesa** [comment]
Well... you can configure pagespeed to serve webp to all clients.... or not.
`pagespeed ServeRewrittenWebpUrlsToAnyAgent off;` that is the default.
When this parameter is off, pagespeed only serve webp images to those browser that send a navigational header image/webp. If the browser don´t send ths header, no webp is served.
I don´t know how Safari does this.

**Comment by jmarantz** [comment]
I'm trying to understand this thread. I think, as Lofessa said, that if Safari can read webp, and sends Accept:image/webp in its request header, then PageSpeed will send webp to Safari. No customization on the PageSpeed side need to be done.
I did not understand @Poseidonas  response "Safari cannot read webp", which contradicts the premise of this issue.

But in any case I don't think there's any bug here.
