### ISSUE TITLE
Rewrite images doest work

### ISSUE THREAD

**Issue by ph1823** [apache/incubator-pagespeed-mod#2053]
Hello !
I using Symfony framework for my ebsite with webpack to generate CSS and JavaScript.
I have install the pagespeed mod to optimize the load of my website, but the image is doest'n convert to webP.

On HTML tag i have: `onload="pagespeed.CriticalImages.checkImageForCriticality(this);"` and `data-pagespeed-url-hash="902389122"` but the url of image doest'n change.

In stats logs pagespeed i have:
```
image_rewrite_uses: 0
image_rewrites: 0
``` 

My page speed configuration:
```
<IfModule pagespeed_module>
    # Turn on mod_pagespeed. To completely disable mod_pagespeed, you
    # can set this to "off".
    ModPagespeed on

    # Direct Apache to send all HTML output to the mod_pagespeed
    # output handler.
    AddOutputFilterByType MOD_PAGESPEED_OUTPUT_FILTER text/html

    # If you want mod_pagespeed process XHTML as well, please uncomment this
    # line.
    # AddOutputFilterByType MOD_PAGESPEED_OUTPUT_FILTER application/xhtml+xml

    # The ModPagespeedFileCachePath directory must exist and be writable
    # by the apache user (as specified by the User directive).
    ModPagespeedFileCachePath            "/var/cache/mod_pagespeed/"

    # LogDir is needed to store various logs, including the statistics log
    # required for the console.
    ModPagespeedLogDir "/var/log/pagespeed"

    # Explicitly enables specific filters. This is useful in
    # conjuction with ModPagespeedRewriteLevel. For instance, filters
    # not included in the CoreFilters may be enabled using this
    # directive. This directive contains a comma-separated list of
    # filter names, and can be repeated.
    #
    ModPagespeedEnableFilters rewrite_javascript,rewrite_css,rewrite_images,resize_rendered_image_dimensions


    # ModPagespeedDomain
    # authorizes rewriting of JS, CSS, and Image files found in this
    # domain. By default only resources with the same origin as the
    # HTML file are rewritten. For example:
    #
    ModPagespeedDomain *.datahosting.fr
    ModPagespeedDomain *.datatips.me
	
    ModPagespeedFetchHttps enable,allow_self_signed
	

    # Limit the number of inodes in the file cache. Set to 0 for no limit.
    # The default value if this paramater is not specified is 0 (no limit).
    ModPagespeedFileCacheInodeLimit        0

    ModPagespeedEnableFilters in_place_optimize_for_browser

    <Location /pagespeed_admin>
	   Order allow,deny
           Deny from all
        #SetHandler pagespeed_admin
    </Location>
    <Location /pagespeed_global_admin>
	Order allow,deny
	Deny from all
        #SetHandler pagespeed_global_admin
    </Location>

    # Enable logging of mod_pagespeed statistics, needed for the console.
    ModPagespeedStatisticsLogging on

    ModPagespeedMessageBufferSize 100000
</IfModule>

<IfModule !mod_version.c>
  LoadModule version_module /usr/lib/apache2/modules/mod_version.so
</IfModule>

<IfVersion < 2.4>
  LoadModule pagespeed_module /usr/lib/apache2/modules/mod_pagespeed.so
</IfVersion>
<IfVersion >= 2.4.2>
  LoadModule pagespeed_module /usr/lib/apache2/modules/mod_pagespeed_ap24.so
</IfVersion>
```

I think it is because symfony rewrites the image path (the images are in /public/img but symfony displays as path/img) I don't know how to fix this, do you have a solution?

Thank for your help !

**Comment by jmarantz** [comment]
Can you try enabling the 'debug' filter? You can do this in the URL itself without editing the config by vising YOURSITE?PageSpeedFilters=+debug.

Then the HTML will be annotated with comments describing for each image describing why PageSpeed was not able to optimize it.

I am not familiar with Symfony so I don't have any insight into its compatibility with mod_pagespeed. The path change you describe doesn't sound like a problem to me so far.

**Comment by ph1823** [comment]
It's very strange. I activated the filter, and I went to my site but no comments, so I add `?PageSpeedFilters=+debug` to the url, same no comments. I tested on the other site that I had on my apache server, the only one where there are comments is the one where there is not a valid SSL certificate. I just migrated to cloudflare like the other domains, I think I got the same result.

I didn't specify it, but I'm using cloudflare with full (but not strict) encryption as well as automatic HTML / CSS / JS minification.I just deactivated this option, and it returns me:
```<!--4xx status code, preventing rewriting of https://skybusiness.me/images/stonks792x446.jpg-->```
I search this error on google ans i find i can add this:
```ModPagespeedFetchHttps enable,allow_self_signed,allow_unknown_certificate_authority,allow_certificate_not_yet_valid```
But doest work  now i have:
```<!--deadline_exceeded for filter CacheExtender-->```
And i have wait, now that work.
But if a enable minify HTML on cloudflare, modpage doest change url.
That a bug or that normal modpage speed is not compatible with cloudflare minify ?

**Comment by jmarantz** [comment]
RE not seeing comments in HTML: Cloudflare's HTML minification probably strips those out.

RE Cloudflare/mod_pagespeed compatibility: I am not aware of any specific issues, but mod_pagespeed and Cloudflare both do many of the same things. It's probably confusing if you have similar features enabled for both.

Another thing I think might be confusing things is if Cloudflare is caching your HTML. That can make mod_pagespeed's HTML modification harder to reason about by delaying its visibility. Also you should be aware that the first time mod_pagespeed sees a page, it optimizes it in the background, storing the results in its server-side cache, and serves unoptimized or partially optimized HTML until the background optimizations complete. This can further confuse the apparent behavior if you have a caching CDN saving you HTML.

RE "deadline exceeded": that is the background optimization at work for you, and is perfectly normal. Refresh the page and you should see optimized results.

**Comment by Lofesa** [comment]
@ph1823 please, re-read the config you have posted here. 
Where are the convert image filters?
But I have tested https://datahosting.fr and the webp images are here.

Note: About fecht https, you need to configure [certificates](https://www.modpagespeed.com/doc/https_support#configuring_ssl_certificates) too. I can´t see it in the config you have posted but maybe you have done in the working config.

**Comment by ph1823** [comment]
@jmarantz 
> Another thing I think might be confusing things is if Cloudflare is caching your HTML. That can make mod_pagespeed's HTML modification harder to reason about by delaying its visibility. Also you should be aware that the first time mod_pagespeed sees a page, it optimizes it in the background, storing the results in its server-side cache, and serves unoptimized or partially optimized HTML until the background optimizations complete. This can further confuse the apparent behavior if you have a caching CDN saving you HTML.

I think so too, thanks for your help!




@Lofesa thank for your reply but that normal, i have resolve problem !
