### ISSUE TITLE
Optimization doesn't happen on images loaded via "Load More"

### ISSUE THREAD

**Issue by dayeggpi** [apache/incubator-pagespeed-mod#2054]
Hi,

I am using pagespeed with Apache, and I enabled the "InPlaceResourceOptimization" option.
I have, on my wordpress, a gallery.
When loading the page, few first images appear, and they are optimized (I can see the 'pagespeed' in the filenames, as well as the right header).
I have a "Load More" button. When I press it, it loads additional images, but the pagespeed doesn't affect them and those images are 'untouched'.

Is there a way to fix that ? 

thanks for your help

**Comment by Lofesa** [comment]
Hi
Maybe these images are loaded by javascript, and then not processed by pagespeed module... unless by IPRO.
Images optimized by IPRO don´t change the url or the headers, but are optimized in some way, not fully opitmized.
How you can test it´s IPRO optimized... by the Etag headers you must see some like Etag: "PSA/xxxxx" and maybe the conten-type header is set to image/webp but the file extensions remain as jpg.

**Comment by dayeggpi** [comment]
oh wow, you are right ! 
images that are loaded once i press the "load more" button (hence, via ajax), have the filename unchanged (unlike the first ones who have the filename changed to something like "image.jpg.pagespeed.ic.qRBF-wROiM.webp"), and in the headers of the loaded images via ajax (in below example it is "image2.jpg"), I can see :
`content-type: image/webp
etag: W/"PSA-aj-j17OKP5Yp5"` 
so i guess IPRO is working...

thank you and sorry for the false alarm, i could not find any documentation on that, and your answer gave all the right details away.
