### ISSUE TITLE
configure SlowFileLatencyUs to change threshold

### ISSUE THREAD

**Issue by ashishkpal** [apache/incubator-pagespeed-mod#2055]
i am getting the below error on the nginx error log file

2021/01/20 10:32:29 [error] 1305#1305: [ngx_pagespeed 1.13.35.2-0] Slow ReadFile operation on file /var/cache/ngx_pagespeed/v3/xxxxx/http,3A/,xxxxx,2Cqv=1.pagespeed.ic.i1sENDyBR7.png,: 120.302ms; configure SlowFileLatencyUs to change threshold

**Comment by oschaaf** [comment]
Sure, but what is your question? :-)

**Comment by ashishkpal** [comment]
mine question is should i worry about this error and if yes then how do i configure SlowFileLatencyUs

**Comment by oschaaf** [comment]
Closing this, you either need to follow up on the implied suggestion of the message, or ensure faster (disk) i/o. Using memcached or larger caches for pagespeed may reduce disk pressure.
