### ISSUE TITLE
หน้าเว็บไซต์ ไม่ผ่านการประเมิน Core Web Vitals 

### ISSUE THREAD

**Issue by kriskhunthong** [apache/incubator-pagespeed-mod#2057]
สวัสดีครับ ก่อนอื่นต้องบอกว่า มือใหม่มากๆ อยากรบกวนผู้มีประสบการณ์แนะนำ หรือ แก้ไข หน้าเว็บไซต์[ ]( https://medhubnews.com/ )

ซึ่งมีปัญหา หน้าเว็บไซต์ ไม่ผ่านการประเมิน Core Web Vitals 

โปรดให้คำแนะนำกับเรา 

คริษฐ์ ขันทอง 

kris_nong@hotmail.com 

เจ้าของ เว็บไซต์ข่าวสาร [](https://medhubnews.com/)

**Comment by oschaaf** [comment]
As with the other issue, it is probably best to as around over at https://github.com/GoogleChrome/Lighthouse/issues
