### ISSUE TITLE
ModPagespeed Slow TTFB w/ Brotli Compression enabled on pages with more HTML

### ISSUE THREAD

**Issue by jk2625** [apache/incubator-pagespeed-mod#2058]
We're seeing issues (across multiple websites with different content) with ModPagespeed v1.13.35.2-0 on Apache/2.4.6 causing significant TTFB delays (~600-700ms in total) on websites with somewhat larger HTML content (> 100kb or so).

This only happens when:
1. ModPagespeed is turned on (disabling via ?ModPagespeed=off fixes this)
2. Brotli compression via mod_brotli is on and compressing the HTML 

Normal TTFB is roughly 100-200ms in total.

This happens regardless of what filters are enabled - setting it to pass through and/or disabling all active filters still causes the same delay. 

ModPagespeedHttpCacheCompressionLevel 0 has been tried too.

/var/cache/mod_pagespeed/v3 is currently 93M, 
/var/cache/mod_pagespeed/shm_metadata_cache is currently 5.3M

Both are local filesystems - not using Memcache.

Relevant configuration directives:

ModPagespeedRewriteDeadlinePerFlushMs 10
ModPagespeedCreateSharedMemoryMetadataCache ~51M
ModPagespeedFileCacheSizeKb          102400
ModPagespeedFileCacheCleanIntervalMs 3600000
ModPagespeedLRUCacheKbPerProcess     1024
ModPagespeedLRUCacheByteLimit        16384

With debug: https://pastebin.com/EPBFa9hj

#NumFlushes            0
#EndDocument after     26133us
#Total Parse duration  5849us
#Total Render duration 1330us
#Total Idle duration   20284us
The following filters were disabled for this request:
	SupportNoscript

No pagespeed errors in /var/log/httpd/error_log
Happens on both PHP & static HTML files
Kernel: 3.10.0-1160.11.1.el7.x86_64
CentOS 7

**Comment by oschaaf** [comment]
I don't have it on top of mind, but I think it is worth investigating the `FlushHtml` options and directives around that. The buffering by PageSpeed may hurt a little bit more when brotli runs in front of it. Of course, forcing PageSpeed to flush earlier may also result in lost optimization opportunities for that module, as it has to forego context of bytes that already on the wire, that  in retrospect could have been rewritten in a better way as the module learns about what came next. Alternatively, don't apply brotli compression to the html or use a lower compression level for that. Maybe some experimenting will learn with what works best.

**Comment by jk2625** [comment]
Turns out tinkering with the compression level helped a whole lot. Totally blew past me this morning. 

Oddly enough, any brotli compression level below 10 had very little impact on Pagespeed - using 10 or 11 caused the issue. I guess this makes sense given 10's a lot more aggressive.

If anyone else encounters this issue - just lower your Brotli Compress level directive to 9 or so. It's not an issue on ngx_pagespeed either so that can also be used.

Thanks @oschaaf

**Comment by oschaaf** [comment]
Great, no problem. Closing this issue.
