### ISSUE TITLE
28 วันที่ผ่านมาประสบการณ์โดยรวมของเพจทั้งหมดที่ให้บริการจากจุดเริ่มต้นนี้ไม่ผ่านการประเมิน Core Web Vitals 

### ISSUE THREAD

**Issue by kriskhunthong** [apache/incubator-pagespeed-mod#2059]
ในช่วงระยะเวลาการรวบรวม 28 วันที่ผ่านมาประสบการณ์โดยรวมของเพจทั้งหมดที่ให้บริการจากจุดเริ่มต้นนี้ไม่ผ่านการประเมินCore Web Vitals หากต้องการดูคำแนะนำที่ปรับให้เหมาะกับแต่ละหน้าให้วิเคราะห์ [URL ของแต่ละหน้า](https://medhubnews.com/)

เช่น การเปลี่ยนแปลงเค้าโครงสะสม 

คริษฐ์ ขันทอง

**Comment by Lofesa** [comment]
You can post this on core web vitals (Ligthouse) here https://github.com/GoogleChrome/Lighthouse/issues
