### ISSUE TITLE
cloning went wrong

### ISSUE THREAD

**Issue by eilandert** [apache/incubator-pagespeed-mod#2060]
Hello,

git clone -b latest-stable --depth=1 -c advice.detachedHead=false --recursive https://github.com/apache/incubator-pagespeed-mod.git

Cloning into 'third_party/apr/src'...
fatal: reference is not a tree: a194e7afd16d2bd88c5394dfb6d066614161b1ed

I am not a git hero, does anybody know what I am doing wrong? It used to work before.

**Comment by Lofesa** [comment]
Seems that hash in the apr repository has changed.
I can see the 1.6.2 version of apr as https://github.com/apache/apr/tree/53d0de8f5ae536a6b3be9ff7e3d9db7fbbdb7dba
But https://github.com/apache/apr/tree/a194e7afd16d2bd88c5394dfb6d066614161b1ed still visible....
@oschaaf can you take alook?

**Comment by eilandert** [comment]
Thanks, I think it was a github glitch or something. I came back after couple of hours and it mysteriously worked.
