### ISSUE TITLE
ฉันมีปัญหาเกี่ยวกับdevelopers ต้องการเร่งสปีด และ แก้ไขจุดบกพร่อง 

### ISSUE THREAD

**Issue by kriskhunthong** [apache/incubator-pagespeed-mod#2075]
เว็บไซต์ https://medhubnews.com/  ของฉันมีปัญหาเกี่ยวกับความเร็ว ฉันไม่รู้ว่าต้องทำอย่างไรบ้าง และ ปัญหาอีกมากมาย ที่ต้องการความช่วยเหลือ 

คริษฐ์ ขันทอง 
kris_nong@hotmail.com 
0891620808

**Comment by oschaaf** [comment]
This doesn't look like a question or issue directly related to the module, closing this.
