### ISSUE TITLE
ModPagespeed* options in .htaccess don't work for fastcgi processes (PHP-FPM, php-cgi, etc)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [apache/incubator-pagespeed-mod#963]
```
What steps will reproduce the problem?
1. Configure ModPagespeed* options in .htaccess (i.e., it is defaulted off, 
enable it with "ModPagespeed on" and then set some options)
2. Load page, check headers / resulting page
3. Headers (and resulting page) will not indicate Pagespeed was activated, if 
the page was generated via fastcgi (etc) method, but will via DSO (i.e. mod_php)

What is the expected output? What do you see instead?
X-Mod-Pagespeed header should be set (and page speed should be optimizing the 
page). Instead, no X-Mod-Pagespeed header, no optimization. 

What version of the product are you using (please check X-Mod-Pagespeed
header)?
1.7.30.5-3847
1.8.31.4-4058

On what operating system?
CentOS 6.5 x86_64

Which version of Apache?
Apache 2.2.27 (MPM Worker w/ PHP-FPM 5.4.30, mod_pagespeed 1.8.31.4-4058)
Apache 2.2.15 (MPM Prefork w/ mod_php 5.3.25 and php-cgi 5.4.24 mod_pagespeed 
1.7.30.5-3847)

Which MPM?
both Prefork and Worker (see above)

URL of broken page:
We don't currently have a publicly accessible page to demonstrate this, but 
we've verified it in two different environments. Since it's a case of Pagespeed 
either running at all or not, rather than breaking, this shouldn't really 
matter. 

In both configurations listed above, when using some form of CGI (PHP-FPM or 
php-cgi via fastcgi, etc), ModPagespeed* commands in .htaccess cannot enable / 
configure ModPagespeed. However, when using a DSO method for PHP (mod_php) 
instead, this works fine. 

To make CGI methods work, we must specify the options in the virtualhost 
configuration, rather than .htaccess, which is inconvenient both from a testing 
/ optimizing perspective as well as maintenance, since that means for hosted 
environments we have to get the hosting provider support team to make changes 
for us.

Since everything else such as rewrites and expires and so forth work regardless 
of the method of invoking PHP (other than php_* commands themselves, which 
makes sense because PHP isn't part of Apache in the cgi case - we use the PECL 
extension htscanner to enable this functionality though), it would seem this is 
either a bug or limitation within Pagespeed itself that could (and we believe, 
should) be remedied. 
```

Original issue reported on code.google.com by `jonat...@creatuity.com` on 23 Jul 2014 at 1:36

**Comment by ci2014** [comment]
Is there any solution yet?

**Comment by Tarekajaj** [comment]
No solution yet?

**Comment by oschaaf** [comment]
@Tarekajaj 
I don't think anyone has looked into this yet

**Comment by xclntdesign** [comment]
I have a real world example to show the issue:

.htaccess
`ModPagespeed off`

ismodpagespeedworking.com results:
bonfiremhp.com/index.php

> 200: OK
> date: Tue, 28 Nov 2017 15:04:04 GMT
> server: Apache
> expires: Thu, 19 Nov 1981 08:52:00 GMT
> cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0, max-age=0, no-cache, s-maxage=10
> pragma: no-cache
> set-cookie: PHPSESSID=nlvovddgv5u1bc17t2sfjtu8t7; path=/
> x-mod-pagespeed: 1.12.34.2-0
> vary: Accept-Encoding
> content-length: 10133
> connection: close
> content-type: text/html

bonfiremhp.com/test.html

> 200: OK
> date: Tue, 28 Nov 2017 15:04:50 GMT
> server: Apache
> last-modified: Mon, 27 Nov 2017 18:01:26 GMT
> accept-ranges: bytes
> content-length: 5
> connection: close
> content-type: text/html

**Comment by feyll** [comment]
Hello everyone, does anyone know if this has been solved?

**Comment by cukier49** [comment]
the problem occurs all the time. Can you expect to repair it?

**Comment by theadoria** [comment]
Any updates on this? Would be nice to have some more information in any case, even if this isn't something that can be addressed soon :)

**Comment by jmarantz** [comment]
To enable `.htaccess` processing, add
```
  AllowOverride All
```
to your global configuration.  See https://www.linode.com/docs/web-servers/apache/how-to-set-up-htaccess-on-apache/ for details.

**Comment by coralsnake** [comment]
I have "ModPagespeedEnableFilters remove_comments" in my .htaccess and when I run the php script the comment are actualy missing if I view the html code , maybe it is working now ?
